import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { afterEach, expect, it } from 'vitest';
import { createEvidenceFixture } from './helpers/evidence.js';
import { createCompilerProposalToolset } from '../src/compiler/proposal-tools.js';
import { SourceAnnotationStore } from '../src/compiler/annotations.js';
import { createSourceAnnotationRetrievalTools } from '../src/compiler/annotation-retrieval.js';
import { readKnowledgeRepairQuotations } from '../src/compiler/knowledge-repair.js';
const roots: string[]=[];
afterEach(async()=>{for(const root of roots.splice(0))await fs.rm(root,{recursive:true,force:true});});
it('retrieves committed quoted text and recovers a bare ID without inventing refs or quotes',async()=>{
 const root=await fs.mkdtemp(path.join(os.tmpdir(),'nwh-quote-recovery-'));roots.push(root);
 const text='所有的读取、移动和存储，都直接点击完成。';
 const fixture=await createEvidenceFixture(root,`EVA said: “${text}”\n`);
 const toolset=createCompilerProposalToolset(root);await toolset.beginBatch([fixture.segmentId],'quote-batch',fixture.source.id);
 await toolset.tools.find(t=>t.name==='propose_quotation')!.execute('quote',{proposal_id:'quote-proposal',annotation_id:'quote-instruction',selector:{segment_id:fixture.segmentId,exact:text},mode:'direct',addressee_mention_ids:[],attribution_confidence:1} as never,undefined,undefined,{} as never);
 const tools=createSourceAnnotationRetrievalTools(root,()=>fixture.source.id);
 const call=async(name:string,args:unknown)=>{const result=await tools.find(t=>t.name===name)!.execute(name,args as never,undefined,undefined,{} as never);return JSON.parse((result.content[0] as {text:string}).text);};
 const pending=await call('find_source_annotations',{query:'读取、移动',annotation_type:'quotation'});
 expect(pending.results[0].ref).toBe('pending:quote-proposal');
 await new SourceAnnotationStore(root).commitProposals(fixture.source.id,['quote-proposal']);
 await expect(call('read_source_annotation',{ref:'quote-instruction'})).rejects.toThrow('not found');
 const found=await call('find_source_annotations',{query:'quote-instruction',annotation_type:'quotation'});
 expect(found.totalMatches).toBe(1);
 const read=await call('read_source_annotation',found.results[0].readArguments);
 expect(JSON.parse(read.chunk).exactText).toBe(text);
 const byText=await call('find_source_annotations',{query:'读取、移动',annotation_type:'quotation',status:'committed'});
 expect(byText.results[0].ref).toBe(found.results[0].ref);
 const host=await readKnowledgeRepairQuotations(root,fixture.source.id,['quote-instruction','absent']);
 expect(host[0]).toEqual({annotationId:'quote-instruction',available:true,readArguments:{ref:found.results[0].ref},exactText:text});
 expect(host[1]).toEqual({annotationId:'absent',available:false});
 const other=await createEvidenceFixture(root,'Other source without the quotation.\n');
 expect(await readKnowledgeRepairQuotations(root,other.source.id,['quote-instruction'])).toEqual([{annotationId:'quote-instruction',available:false}]);
});
