import { assertReconciliationDeferralsReviewed, reviewReconciliationDeferrals } from "../src/compiler/reconciliation-review-ledger.js";
import { ActorModelStore } from "../src/world/actors.js";
import { InitialWorldStore } from "../src/world/initial.js";
import fs from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { afterEach, expect, it } from "vitest";
import { reconciliationReviewIssues, reconciliationAuditResults } from "../src/compiler/reconciliation-review.js";
import { buildWorldReconciliationPrompt, reconciliationReviewTargets } from "../src/compiler/reconcile-world.js";
import { auditCompiler } from "../src/compiler/audit.js";
import { CanonicalModelStore } from "../src/world/canonical-model.js";
import { createCompilerProposalToolset } from "../src/compiler/proposal-tools.js";
import { CompilerFinishReceipts } from "../src/compiler/finish-receipts.js";
import { createEvidenceFixture } from "./helpers/evidence.js";

const roots: string[] = [];
afterEach(async () => { for (const root of roots.splice(0)) await fs.rm(root, { recursive: true, force: true }); });
const review = { target: "event:arrival", disposition: "proposed" as const, evidence_segment_ids: ["segment"], summary: "Time repaired; effect remains unsupported." };
it("rejects missing, duplicate, foreign and unbacked target reports", () => {
  const proposals = new Map([["p", { kind: "canonical-event", payload: { id: "arrival" } }]]);
  expect(reconciliationReviewIssues(["event:arrival", "character:hero"], [review], proposals)).toEqual(["Account exactly once for target character:hero."]);
  expect(reconciliationReviewIssues(["event:arrival"], [review, review], proposals)).not.toEqual([]);
  expect(reconciliationReviewIssues(["character:hero"], [{ ...review, target: "character:hero" }], proposals).join()).toContain("requires an active proposal");
  expect(reconciliationReviewIssues(["event:arrival"], [review], new Map()).join()).toContain("requires an active proposal");
  expect(reconciliationReviewIssues(["event:arrival"], [{ ...review, disposition: "unsupported" }], proposals).join()).toContain("active proposals require");
  expect(reconciliationReviewIssues(["event:arrival"], [review], proposals)).toEqual([]);
});

it("requires every planned target at real finish, freezes deferrals in the receipt, and keeps audit gaps unresolved", async () => {
  const root = await fs.mkdtemp(path.join(os.tmpdir(), "nwh-target-review-")); roots.push(root);
  const fixture = await createEvidenceFixture(root, "Hero arrives.\n");
  const canon = new CanonicalModelStore(root);
  await canon.putEntity({ id: "hero", kind: "character", canonicalName: "Hero", aliases: [], evidence: fixture.evidence("Hero") });
  await canon.putEvent({ id: "arrival", title: "Hero arrives", participants: ["hero"], storyTime: { kind: "unknown" }, preconditions: [], observedOutcome: { version: 1, operations: [] }, evidence: fixture.evidence("Hero arrives."), causalParents: [], confidence: 1 });
  await new ActorModelStore(root).putModel({ actorId: "hero", traits: {}, decisionBiases: {}, evidence: fixture.evidence("Hero") });
  await new InitialWorldStore(root).put({ version: 1, delta: { version: 1, operations: [] }, evidence: fixture.evidence("Hero arrives."), checkpoint: { mode: "chronological", storyTime: { kind: "ordinal", label: "Opening", orderHint: 0 }, rationale: "Opening" } });
  const audit = await auditCompiler(root, { sourceId: fixture.source.id });
  const namespace = "target-review-test";
  const prompt = await buildWorldReconciliationPrompt(root, fixture.source.id, { ...audit, coverage: { ...audit.coverage, autonomousDriverCoverage: 0 }, semanticRepairTargets: { ...audit.semanticRepairTargets, characterIds: ["hero"] } }, 1, { proposalIdSuffixTail: namespace });
  const context = JSON.parse(prompt.match(/<reconciliation-context>\n([\s\S]+)\n<\/reconciliation-context>/u)![1]!);
  expect(context.weakCharacterCandidates[0]).toMatchObject({ needsExecutableDriver: true, needsOntologyMigration: true, requiredOntologyVersion: "character-v1" });
  expect(context.openingDriverContext).toMatchObject({ readOnly: true, ref: "canonical:initial-world:singleton", storyTime: { orderHint: 0 }, delta: { operations: [] } });
  const batch = `reconcile-${fixture.source.id}-bounded-${namespace}-1`;
  const targets = (await reconciliationReviewTargets(root, fixture.source.id, batch))!;
  expect(targets).toContain("event:arrival");
  const toolset = createCompilerProposalToolset(root);
  await toolset.beginBatch([], batch, fixture.source.id);
  const finish = toolset.tools.find(tool => tool.name === "finish_compiler_batch")!;
  const call = (input: unknown) => finish.execute("finish", input as never, undefined, undefined, {} as never);
  const input = { outcome: "no-artifacts", reviewed_segments: [], summary: "Insufficient source for typed effects." };
  await expect(call(input)).rejects.toThrow("Account exactly once");
  expect(await new CompilerFinishReceipts(root, fixture.source.id, batch).read()).toBeUndefined();
  const reports = targets.map(target => ({ target, disposition: "capability-gap" as const, evidence_segment_ids: [fixture.segmentId], summary: "The cited arrival text does not name a location; the missing location must be reviewed by the host." }));
  const result = await call({ ...input, target_reviews: reports });
  expect(JSON.stringify(result)).toContain('"compilerBatchFinished":true');
  const receipt = await new CompilerFinishReceipts(root, fixture.source.id, batch).read();
  expect(receipt?.identity.input.target_reviews).toEqual(reports);
  await new CompilerFinishReceipts(root, fixture.source.id, batch).verify(receipt!);
  await expect(assertReconciliationDeferralsReviewed(root, fixture.source.id)).rejects.toThrow("host source review");
  const decision = { sourceId: fixture.source.id, batchId: batch, finishFingerprint: receipt!.fingerprint, reviewedAt: new Date().toISOString(), reviews: targets.map(target => ({ target, reason: "Host reviewed immutable evidence; no invented effects authorized.", auditRef: "test-audit" })) };
  await expect(reviewReconciliationDeferrals(root, { ...decision, reviews: [] })).rejects.toThrow("every deferred target");
  await reviewReconciliationDeferrals(root, decision);
  await expect(assertReconciliationDeferralsReviewed(root, fixture.source.id)).resolves.toBeUndefined();
  const results = reconciliationAuditResults(targets, reports, audit);
  expect(results.find(result => result.target === "event:arrival")).toMatchObject({ status: "unresolved", hostReviewRequired: true });
  expect(reconciliationAuditResults(targets, [{ ...review, evidence_segment_ids: [fixture.segmentId] }], audit)[0]?.status).toBe("unresolved");
});
