import { WorldRuntime } from "../src/world/runtime.js";
import { buildNwhToolRecoveryAdvice } from "../src/agent/tool-recovery.js";
import fs from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { afterEach, expect, it } from "vitest";
import { createEvidenceFixture } from "./helpers/evidence.js";
import { CanonicalModelStore } from "../src/world/canonical-model.js";
import { canonicalEventSchema, propositionSchema, type EvidenceAssertion } from "../src/world/model.js";
import { contentHash } from "../src/world/canonical.js";
import { utteranceExpressionSchema, validateUtteranceExpression, validateUtteranceExpressionEvidence, validateExpressionAcquisition } from "../src/world/utterance-expression.js";
import { SourceAnnotationStore, quotationSchema, entityMentionSchema } from "../src/compiler/annotations.js";
import { EntityResolutionStore, identityResolutionSchema } from "../src/compiler/entity-resolution.js";
import { textAnchorForByteRange } from "../src/compiler/text-anchors.js";
import { createCompilerProposalToolset, compilerToolAllowedInSemanticStage } from "../src/compiler/proposal-tools.js";
import { convergeWorldProposals } from "../src/compiler/converge.js";
import { CompilerBatchStore, prepareCompilerBatches } from "../src/compiler/batches.js";
import { PreparedNovelCache } from "../src/compiler/prepared-cache.js";
import { EvidenceAssertionStore } from "../src/compiler/evidence-assertions.js";
import { InitialWorldStore } from "../src/world/initial.js";
import { buildPreparedClosure } from "../src/compiler/closure.js";
import { WorldContextStore } from "../src/world/context.js";
import { WorldEngine } from "../src/world/engine.js";
import { loadCompilerArtifactRecords } from "../src/compiler/artifact-retrieval.js";
import { validateUtteranceExpressionTrace } from "../src/compiler/utterance-expression-trace.js";
const roots: string[] = [];
afterEach(async () => { for (const root of roots.splice(0)) await fs.rm(root, { recursive: true, force: true }); });
const scenes = [
  { speaker: "Ada", listener: "Bo", subject: "gate", quote: "the gate is shut", tail: "I do not know", text: 'Ada tells Bo: "the gate is shut". Later Ada tells Bo: "I do not know".' },
  { speaker: "宁", listener: "维", subject: "码头", quote: "码头已经关闭", tail: "我不知道", text: '宁对维说：“码头已经关闭”。潮水涌起。后来宁对维说：“我不知道”。' },
];
async function setup(scene: typeof scenes[number]) {
  const root = await fs.mkdtemp(path.join(os.tmpdir(), "nwh-expression-")); roots.push(root);
  const source = await createEvidenceFixture(root, scene.text), canon = new CanonicalModelStore(root);
  const bytes = Buffer.from(scene.text);
  const anchor = (text: string) => { const start = bytes.indexOf(Buffer.from(text)); return textAnchorForByteRange(source.source.id, bytes, start, start + Buffer.byteLength(text)); };
  for (const [id, canonicalName, kind] of [["speaker", scene.speaker, "character"], ["listener", scene.listener, "character"], ["place", scene.subject, "location"]] as const) await canon.putEntity({ id, kind, canonicalName, aliases: [], evidence: source.evidence(canonicalName) });
  const derivation = { runId: "test", worker: "test", ontologyVersion: "observation-v1" } as const;
  const mentions = [["speaker", scene.speaker], ["listener", scene.listener]].map(([id, text]) => entityMentionSchema.parse({ version: 1, id: `mention-${id}`, sourceId: source.source.id, derivation, annotationType: "entity-mention", anchor: anchor(text!), surface: text, form: "proper", kindCandidates: ["character"], confidence: 1 }));
  const quotation = quotationSchema.parse({ version: 1, id: "quotation", sourceId: source.source.id, derivation, annotationType: "quotation", anchor: anchor(scene.quote), mode: "direct", speakerMentionId: "mention-speaker", addresseeMentionIds: ["mention-listener"], attributionConfidence: 1 });
  await new SourceAnnotationStore(root).replaceCurrent(source.source.id, [...mentions, quotation]);
  await new EntityResolutionStore(root).replaceCurrent(source.source.id, mentions.map(mention => identityResolutionSchema.parse({ version: 1, id: `resolution-${mention.id}`, sourceId: source.source.id, mentionId: mention.id, status: "resolved", entityId: mention.id.slice(8), candidates: [{ entityId: mention.id.slice(8), confidence: 1, basisMentionIds: [mention.id], evidenceAssertionIds: [], rationale: "Explicit named speaker/addressee" }], rationale: "Explicit named speaker/addressee", derivation: { runId: "test", worker: "test", ontologyVersion: "entity-resolution-v1" } })));
  const proposition = propositionSchema.parse({ id: "content", subjectEntityId: "place", relationId: "is-shut", object: { kind: "literal", value: true }, polarity: "positive", modality: "asserted", evidence: source.evidence(scene.quote) });
  await canon.putProposition(proposition);
  const event = canonicalEventSchema.parse({ id: "utterance", title: "A warning", participants: ["speaker", "listener"], participantPresence: [{ entityId: "speaker", mode: "physical" }, { entityId: "listener", mode: "physical" }], storyTime: { kind: "unknown" }, preconditions: [], observedOutcome: { version: 1, operations: [{ op: "set", entityId: "speaker", field: "character.plan", value: "warned" }] }, causalParents: [], confidence: 1, evidence: source.evidence(scene.text) });
  await canon.putEvent(event);
  await canon.putClaim({ id: "claim", subject: "place", predicate: "is-shut", object: true, epistemicType: "character-claim", evidence: source.evidence(scene.quote) });
  await canon.putAttribution({ id: "report", propositionId: "content", holderKind: "character", holderEntityId: "speaker", attitude: "asserts", certainty: 1, quotationIds: [quotation.id], evidence: source.evidence(scene.text) });
  const expression = utteranceExpressionSchema.parse({ ontologyVersion: "utterance-expression-v1", id: "expression", canonicalEventId: event.id, speakerId: "speaker", addresseeIds: ["listener"], modality: "speech", quotation: { quotationId: quotation.id, revisionHash: contentHash(quotation), anchor: quotation.anchor }, fragments: [{ anchor: quotation.anchor, text: scene.quote }], propositionId: proposition.id, propositions: [{ propositionId: proposition.id, revisionHash: contentHash(proposition), snapshot: proposition }], evidence: source.evidence(scene.text) });
  const paths = ["/canonicalEventId", "/speakerId", "/addresseeIds/0", "/modality", "/quotation/quotationId", "/propositionId", ...["subjectEntityId", "relationId", "polarity", "modality", "object/value"].map(key => `/propositions/0/snapshot/${key}`)];
  const operation = { op: "learn", actorId: "listener", claimId: "claim", propositionId: "content", attributionId: "report", expressionId: "expression", acquisitionMode: "told", sourceActorId: "speaker", status: "heard", confidence: 1 } as const;
  return { root, source, canon, anchor, mentions, quotation, proposition, event, expression, paths, operation };
}

it.each(scenes)("compiles and freezes a real expression through finish, closure, rebuild, acquisition and replay: $speaker", async scene => {
  const { root, source, canon, anchor, quotation, proposition, event, expression, paths, operation } = await setup(scene);
  const toolset = createCompilerProposalToolset(root); await toolset.beginBatch([], "expression-batch", source.source.id);
  const propose = toolset.tools.find(item => item.name === "propose_utterance_expression")!;
  expect(compilerToolAllowedInSemanticStage(propose.name, "semantic")).toBe(true);
  expect(compilerToolAllowedInSemanticStage(propose.name, "observation")).toBe(false);
  await canon.removeCurrent("events", event.id);
  const { evidence: _eventEvidence, ...eventPayload } = event;
  await toolset.tools.find(item => item.name === "propose_canonical_event")!.execute("occurrence", { proposal_id: "occurrence-proposal", payload: eventPayload, evidence_segment_ids: [source.segmentId] } as never, undefined, undefined, {} as never);
  await toolset.tools.find(item => item.name === "propose_canonical_event")!.execute("later", { proposal_id: "later-proposal", payload: { ...eventPayload, id: "later-event", title: "Later uncertainty", storyTime: { kind: "relative", relation: "after", anchorEventId: event.id } }, evidence_segment_ids: [source.segmentId] } as never, undefined, undefined, {} as never);
  const { evidence: _evidence, ...payload } = expression;
  const input = { proposal_id: "expression-proposal", payload: { ...payload, quotation: { quotationId: quotation.id }, propositions: [{ propositionId: proposition.id }], fragments: [{ segment_id: source.segmentId, exact: scene.quote }] }, evidence_segment_ids: [source.segmentId], evidence_selectors: paths.map(target_path => ({ segment_id: source.segmentId, exact: scene.quote, target_path, relation: "supports", strength: "explicit" })) };
  await expect(propose.execute("bad", { ...input, evidence_selectors: input.evidence_selectors.slice(0, -1) } as never, undefined, undefined, {} as never)).rejects.toThrow("EXPRESSION_CONTENT_MISSING");
  await propose.execute("correct", input as never, undefined, undefined, {} as never);
  const { evidence: _reportEvidence, ...reportPayload } = await canon.getAttribution("report");
  await toolset.tools.find(item => item.name === "propose_attribution")!.execute("bind-report", { proposal_id: "report-expression-proposal", payload: { ...reportPayload, expressionIds: [expression.id] }, evidence_segment_ids: [source.segmentId] } as never, undefined, undefined, {} as never);
  await toolset.tools.find(item => item.name === "finish_compiler_batch")!.execute("finish", { outcome: "complete", reviewed_segments: [], summary: "Exact expression edge; content truth remains unasserted" } as never, undefined, undefined, {} as never);
  expect((await convergeWorldProposals(root, source.source.id)).canonical.blocked).toEqual([]);
  const stored = (await canon.listUtteranceExpressions())[0]!;
  expect((await canon.getAttribution("report")).expressionIds).toEqual([stored.id]);
  expect(stored.propositions).toEqual(expression.propositions);
  expect((await loadCompilerArtifactRecords(root, source.source.id)).some(item => item.kind === "utterance-expression" && item.logicalId === stored.id)).toBe(true);
  const initial = { version: 1 as const, operations: [{ op: "set" as const, entityId: "speaker", field: "character.plan", value: "warn" }, { op: "set" as const, entityId: "speaker", field: "character.alive", value: true }, { op: "set" as const, entityId: "listener", field: "character.alive", value: true }] };
  await new InitialWorldStore(root).put({ version: 1, evidence: source.evidence(scene.text), delta: initial, participantPresence: event.participantPresence });
  await new CompilerBatchStore(root).replaceCompleted(source.source.id, (await prepareCompilerBatches(root, source.source)).map(item => item.id));
  const cacheRoot = path.join(root, "cache"), cache = new PreparedNovelCache(root, cacheRoot);
  const bundle = await cache.candidateSnapshot(source.source), archived = await cache.archiveCandidate(source.source);
  expect(bundle.canonical.utteranceExpressions).toEqual([stored]);
  const closure = buildPreparedClosure(bundle), node = closure.nodes.find(item => item.kind === "utterance-expression")!;
  expect(node.dependsOn).toEqual(expect.arrayContaining([expect.objectContaining({ kind: "event", id: event.id }), expect.objectContaining({ kind: "proposition", id: proposition.id, revisionHash: contentHash(proposition) }), expect.objectContaining({ kind: "annotation", id: quotation.id, revisionHash: contentHash(quotation) })]));
  const cloneRoot = await fs.mkdtemp(path.join(os.tmpdir(), "nwh-expression-clone-")); roots.push(cloneRoot);
  const cloneSource = await createEvidenceFixture(cloneRoot, scene.text);
  await new PreparedNovelCache(cloneRoot, cacheRoot).restoreCompilerCheckpoint(cloneSource.source, archived.bundleHash!);
  expect(await new CanonicalModelStore(cloneRoot).listUtteranceExpressions()).toEqual([stored]);
  const contexts = new WorldContextStore(cloneRoot), context = await contexts.captureCurrent(cloneSource.source.id);
  const engine = new WorldEngine(cloneRoot, context);
  const head = await engine.createBranch("main", "Before speech", initial, undefined, undefined, undefined, [], {}, { realizesCanonicalEventIds: [] });
  await new WorldRuntime(engine, () => []).forkBranch("main", head, "silent", "No expression yet");
  const learn = { proposalId: "learn", branchId: "main", expectedParentCommit: head, source: "actor", title: "Receive the report", actorId: "listener", participants: ["listener", "speaker"], preconditions: [], proposedTime: { kind: "unknown" }, proposedDelta: { version: 1, operations: [] }, proposedKnowledge: { version: 1, operations: [operation] }, causalParents: [], evidence: [] };
  const { expressionId: _removed, ...missingExpression } = operation;
  expect((await engine.commitProposal({ ...learn, proposedKnowledge: { version: 1, operations: [missingExpression] } } as never)).report.errors.some(item => item.code === "ACQUISITION_EXPRESSION_REQUIRED")).toBe(true);
  expect((await engine.commitProposal(learn as never)).report.errors.some(item => item.code === "ACQUISITION_EXPRESSION_NOT_REALIZED")).toBe(true);
  const coincident = await engine.createBranch("coincident", "Matching outcome is not a speech occurrence", { ...initial, operations: [...initial.operations, ...event.observedOutcome!.operations] });
  expect((await engine.commitProposal({ ...learn, branchId: "coincident", expectedParentCommit: coincident } as never)).report.errors.some(item => item.code === "ACQUISITION_EXPRESSION_NOT_REALIZED")).toBe(true);
  const spoke = await engine.commitProposal({ ...learn, proposalId: "speak", actorId: "speaker", proposedKnowledge: undefined, possibilityId: "canon-utterance", proposedDelta: event.observedOutcome, spokenUtterances: [{ speakerId: "speaker", addresseeIds: ["listener"], content: scene.quote, channel: "audible" }] } as never);
  expect(spoke.report.errors).toEqual([]);
  const learned = await engine.commitProposal({ ...learn, expectedParentCommit: spoke.newHead } as never);
  expect(learned.report.errors).toEqual([]);
  expect((await engine.commitProposal({ ...learn, branchId: "silent" } as never)).report.errors.some(item => item.code === "ACQUISITION_EXPRESSION_NOT_REALIZED")).toBe(true);
  const projection = await engine.projections.project(learned.newHead, { fresh: true, useCheckpoints: false });
  expect(projection.knowledge.actors.listener?.claim).toMatchObject({ expressionId: stored.id, status: "heard" });
  expect(projection.state.values.place?.["location.is-shut"]).toBeUndefined();
  expect((await engine.projections.project(head, { fresh: true, useCheckpoints: false })).knowledge.actors.listener?.claim).toBeUndefined();
  expect((await contexts.load(context.canonicalSnapshotHash!)).utteranceExpressions?.get(stored.id)).toEqual(stored);
  const bindings = new EvidenceAssertionStore(root), binding = await bindings.bindingForArtifact("utterance-expression", stored.id);
  await bindings.replaceForArtifact("utterance-expression", stored.id, contentHash(stored), []);
  await expect(cache.candidateSnapshot(source.source)).rejects.toThrow("Utterance expression exact evidence");
  await bindings.replaceForArtifact("utterance-expression", stored.id, contentHash(stored), binding!.assertions);
  const changed = { ...quotation, anchor: anchor(scene.tail) };
  await new SourceAnnotationStore(root).replaceCurrent(source.source.id, [...(await new SourceAnnotationStore(root).list(source.source.id)).filter(item => item.id !== quotation.id), changed]);
  await expect(cache.candidateSnapshot(source.source)).rejects.toThrow("exact current quotation revision");
  expect((await contexts.load(context.canonicalSnapshotHash!)).utteranceExpressions?.get(stored.id)).toEqual(stored);
  expect((await validateUtteranceExpressionTrace(root, stored)).some(item => item.code === "EXPRESSION_QUOTATION_REVISION_MISMATCH")).toBe(true);
  expect(validateUtteranceExpression(stored, { entities: context.entities, events: context.events!, propositions: new Map([[proposition.id, { ...proposition, object: { kind: "literal", value: false } }]]) }).some(item => item.code === "EXPRESSION_PROPOSITION_REVISION_MISMATCH")).toBe(true);
});

it.each(scenes)("requires this occurrence's content and conjunctive anchors; legacy stays unverified: $speaker", async scene => {
  const { root, expression, anchor, paths, operation } = await setup(scene);
  const own = paths.map((jsonPointer, i) => ({ version: 1, id: `proof-${i}`, target: { artifactKind: "utterance-expression", artifactId: expression.id, jsonPointer }, anchors: [anchor(scene.quote)], relation: "supports", strength: "explicit", derivation: { runId: "test", worker: "test", ontologyVersion: "evidence-v1" } })) as EvidenceAssertion[];
  expect(validateUtteranceExpressionEvidence(expression, own)).toEqual([]);
  expect(validateUtteranceExpressionEvidence(expression, [])).not.toEqual([]);
  const content = own.at(-1)!;
  expect(validateUtteranceExpressionEvidence(expression, [...own.slice(0, -1), { ...content, anchors: [anchor(scene.quote), anchor(scene.tail)] }])).not.toEqual([]);
  expect(validateUtteranceExpressionEvidence(expression, [...own, { ...content, id: "alternative", anchors: [anchor(scene.tail)] }])).toEqual([]);
  expect(validateUtteranceExpressionEvidence(expression, own.map(item => ({ ...item, target: { ...item.target, artifactKind: "proposition", artifactId: "content" } })))).not.toEqual([]);
  expect(validateExpressionAcquisition({ ...operation, acquisitionMode: "observed", sourceActorId: undefined } as never, new Map([[expression.id, expression]]))).not.toEqual([]);
  const { expressionId: _absent, ...legacy } = operation;
  expect(validateExpressionAcquisition(legacy, new Map())).toEqual([]);
  expect(legacy).not.toHaveProperty("expressionId");
  const invented = structuredClone(expression); invented.fragments[0]!.text = scene.tail;
  expect(utteranceExpressionSchema.safeParse(invented).success).toBe(false);
  const wrongHash = structuredClone(expression); wrongHash.fragments[0]!.anchor.prefixHash = "0".repeat(64);
  expect(await validateUtteranceExpressionTrace(root, wrongHash)).not.toEqual([]);
});

it.each(scenes)("checks nested reference AND content; preserves disjoint source fragments: $speaker", async scene => {
  const nestedQuote = `${scene.listener} suspects ${scene.quote}`;
  const fixture = { ...scene, text: scene.text.replace(scene.quote, nestedQuote), quote: nestedQuote };
  const { root, source, expression, anchor, proposition, paths } = await setup(fixture);
  const child = { ...proposition, id: "child", evidence: source.evidence(scene.quote) };
  const parent = { ...proposition, subjectEntityId: "listener", relationId: "suspects", object: { kind: "proposition" as const, propositionId: child.id } };
  const nested = utteranceExpressionSchema.parse({ ...expression, propositions: [parent, child].map(snapshot => ({ propositionId: snapshot.id, revisionHash: contentHash(snapshot), snapshot })) });
  const allPaths = [...paths.filter(pointer => !pointer.endsWith("/object/value")), "/propositions/0/snapshot/object/propositionId", ...["subjectEntityId", "relationId", "polarity", "modality", "object/value"].map(key => `/propositions/1/snapshot/${key}`)];
  const proofs = allPaths.map((jsonPointer, index) => ({ version: 1, id: `nested-${index}`, target: { artifactKind: "utterance-expression", artifactId: nested.id, jsonPointer }, anchors: [anchor(nestedQuote)], relation: "supports", strength: "explicit", derivation: { runId: "test", worker: "test", ontologyVersion: "evidence-v1" } })) as EvidenceAssertion[];
  expect(validateUtteranceExpressionEvidence(nested, proofs)).toEqual([]);
  for (const omitted of ["/propositions/0/snapshot/object/propositionId", "/propositions/1/snapshot/object/value"]) expect(validateUtteranceExpressionEvidence(nested, proofs.filter(item => item.target.jsonPointer !== omitted))).not.toEqual([]);
  const cyclicChild = { ...child, object: { kind: "proposition" as const, propositionId: parent.id } };
  const cycle = utteranceExpressionSchema.parse({ ...nested, propositions: [parent, cyclicChild].map(snapshot => ({ propositionId: snapshot.id, revisionHash: contentHash(snapshot), snapshot })) });
  expect(validateUtteranceExpressionEvidence(cycle, proofs).some(item => item.code === "EXPRESSION_PROPOSITION_CYCLE")).toBe(true);
  const fragments = [{ anchor: anchor(`${scene.listener} suspects`), text: `${scene.listener} suspects` }, { anchor: anchor(scene.quote), text: scene.quote }];
  const separated = utteranceExpressionSchema.parse({ ...nested, fragments });
  const separatedProofs = proofs.map(item => ({ ...item, anchors: fragments.map(fragment => fragment.anchor) }));
  expect(await validateUtteranceExpressionTrace(root, separated)).toEqual([]);
  expect(validateUtteranceExpressionEvidence(separated, separatedProofs)).toEqual([]);
  // An assertion spanning the omitted separator cannot masquerade as in-fragment support.
  expect(validateUtteranceExpressionEvidence(separated, proofs)).not.toEqual([]);
  expect(utteranceExpressionSchema.safeParse({ ...separated, fragments: [{ anchor: nested.quotation.anchor, text: fragments.map(item => item.text).join("") }] }).success).toBe(false);
  expect(utteranceExpressionSchema.safeParse({ ...separated, fragments: [...fragments].reverse() }).success).toBe(false);
  // Two occurrences of one proposition remain separate records; content revisions alone grant no proof.
  const second = { ...expression, id: "second", quotation: { ...expression.quotation, anchor: anchor(scene.tail) }, fragments: [{ anchor: anchor(scene.tail), text: scene.tail }] };
  expect(validateUtteranceExpressionEvidence(second, proofs.map(item => ({ ...item, target: { ...item.target, artifactId: second.id } })))).not.toEqual([]);
});

it("provides bounded expression recovery without turning missing evidence into certification", () => {
  const missing = buildNwhToolRecoveryAdvice("propose_utterance_expression", "EXPRESSION_QUOTATION_MISSING");
  expect(missing.suggestedCall?.tool).toBe("find_source_annotations");
  expect(missing.steps.join(" ")).toContain("results[].readArguments.ref");
  expect(missing.retryCondition).toContain("one");
  expect(buildNwhToolRecoveryAdvice("finish_compiler_batch", "EXPRESSION_PROPOSITION_MISSING").suggestedCall?.arguments.kind).toBe("proposition");
  expect(buildNwhToolRecoveryAdvice("finish_compiler_batch", "EXPRESSION_QUOTATION_REVISION_MISMATCH").retryable).toBe(false);
  expect(buildNwhToolRecoveryAdvice("propose_state_delta", "ACQUISITION_EXPRESSION_NOT_REALIZED").retryable).toBe(false);
});

it.each(scenes)("reads a written expression from its document without giving the document actor agency: $speaker", async scene => {
  const writingScene = { ...scene, text: `${scene.speaker} writes a notice for ${scene.listener}: "${scene.quote}". Later: "${scene.tail}".` };
  const { root, source, canon, expression, event, paths, operation } = await setup(writingScene);
  await canon.putEntity({ id: "notice", kind: "artifact", canonicalName: "notice", aliases: [], evidence: source.evidence("notice") });
  await canon.putEvent({ ...event, participants: [...event.participants, "notice"] });
  await canon.putAttribution({ ...await canon.getAttribution("report"), holderKind: "document", holderEntityId: "notice" });
  const toolset = createCompilerProposalToolset(root); await toolset.beginBatch([], "written-expression", source.source.id);
  const { evidence: _evidence, ...base } = expression;
  await toolset.tools.find(item => item.name === "propose_utterance_expression")!.execute("write", { proposal_id: "written", payload: { ...base, modality: "writing", documentId: "notice", quotation: { quotationId: "quotation" }, propositions: [{ propositionId: "content" }], fragments: [{ segment_id: source.segmentId, exact: scene.quote }] }, evidence_segment_ids: [source.segmentId], evidence_selectors: [...paths, "/documentId"].map(target_path => ({ segment_id: source.segmentId, exact: target_path === "/documentId" ? "notice" : scene.quote, target_path, relation: "supports", strength: "explicit" })) } as never, undefined, undefined, {} as never);
  await toolset.tools.find(item => item.name === "finish_compiler_batch")!.execute("finish", { outcome: "complete", reviewed_segments: [], summary: "Written expression with separate author and document" } as never, undefined, undefined, {} as never);
  expect((await convergeWorldProposals(root, source.source.id)).canonical.blocked).toEqual([]);
  await canon.putAttribution({ ...await canon.getAttribution("report"), expressionIds: [expression.id] });
  const context = await new WorldContextStore(root).captureCurrent(source.source.id), engine = new WorldEngine(root, context);
  const initial = { version: 1 as const, operations: [{ op: "set" as const, entityId: "speaker", field: "character.alive", value: true }, { op: "set" as const, entityId: "listener", field: "character.alive", value: true }] };
  const head = await engine.createBranch("read", "Before the writing", initial, undefined, undefined, undefined, [], {}, { realizesCanonicalEventIds: [] });
  const { sourceActorId: _noSpeakerSource, ...reading } = { ...operation, acquisitionMode: "read" as const };
  const proposal = { proposalId: "read", branchId: "read", expectedParentCommit: head, source: "actor", title: "Read the notice", actorId: "listener", participants: ["listener", "notice"], preconditions: [], proposedTime: { kind: "unknown" }, proposedDelta: { version: 1, operations: [] }, proposedKnowledge: { version: 1, operations: [reading] }, causalParents: [], evidence: [] };
  expect((await engine.commitProposal(proposal as never)).report.errors.some(item => item.code === "ACQUISITION_EXPRESSION_NOT_REALIZED")).toBe(true);
  const written = await engine.commitProposal({ ...proposal, proposalId: "write", actorId: "speaker", title: "Write the notice", participants: ["speaker", "listener", "notice"], possibilityId: "canon-utterance", proposedDelta: event.observedOutcome, proposedKnowledge: undefined } as never);
  expect(written.report.errors).toEqual([]);
  const read = await engine.commitProposal({ ...proposal, expectedParentCommit: written.newHead } as never);
  expect(read.report.errors).toEqual([]);
  const replay = await engine.projections.project(read.newHead, { fresh: true, useCheckpoints: false });
  expect(replay.knowledge.actors.listener?.claim).toMatchObject({ expressionId: expression.id, acquisitionMode: "read", status: "heard" });
  expect(replay.knowledge.actors.notice).toBeUndefined();
});

it.each(scenes)("reuses a proposition with independent proof for the second occurrence: $speaker", async scene => {
  const { validateCommittedAttributionTrace } = await import("../src/compiler/attribution-trace.js");
  const text = `${scene.text} ${scene.speaker} repeats to ${scene.listener}: "${scene.quote}".`;
  const { root, source, canon, anchor, quotation, expression, paths, proposition } = await setup({ ...scene, text });
  const bytes = Buffer.from(text), start = bytes.lastIndexOf(Buffer.from(scene.quote));
  const secondAnchor = textAnchorForByteRange(source.source.id, bytes, start, start + Buffer.byteLength(scene.quote));
  const secondQuotation = { ...quotation, anchor: secondAnchor };
  const annotations = new SourceAnnotationStore(root);
  await annotations.replaceCurrent(source.source.id, [...(await annotations.list(source.source.id)).filter(item => item.id !== quotation.id), secondQuotation]);
  const second = utteranceExpressionSchema.parse({ ...expression, quotation: { quotationId: quotation.id, revisionHash: contentHash(secondQuotation), anchor: secondAnchor }, fragments: [{ text: scene.quote, anchor: secondAnchor }] });
  await canon.putUtteranceExpression(second);
  const assertions = paths.map((jsonPointer, index) => ({ version: 1, id: `second-${index}`, target: { artifactKind: "utterance-expression", artifactId: second.id, jsonPointer }, anchors: [secondAnchor], relation: "supports", strength: "explicit", derivation: { runId: "test", worker: "test", ontologyVersion: "evidence-v1" } })) as EvidenceAssertion[];
  const evidence = new EvidenceAssertionStore(root);
  await evidence.replaceForArtifact("utterance-expression", second.id, contentHash(second), assertions);
  await evidence.replaceForArtifact("proposition", proposition.id, contentHash(proposition), [{ ...assertions[0]!, id: "first-proof", target: { artifactKind: "proposition", artifactId: proposition.id, jsonPointer: "/object/value" }, anchors: [anchor(scene.quote)] }]);
  const legacy = await canon.getAttribution("report");
  expect((await validateCommittedAttributionTrace(root, source.source.id, legacy)).join(" ")).toContain("outside its cited quotation");
  expect(await validateCommittedAttributionTrace(root, source.source.id, { ...legacy, expressionIds: [second.id] })).toEqual([]);
  await evidence.replaceForArtifact("utterance-expression", second.id, contentHash(second), []);
  expect((await validateCommittedAttributionTrace(root, source.source.id, { ...legacy, expressionIds: [second.id] })).join(" ")).toContain("EXPRESSION_CONTENT_MISSING");
});

it.each(scenes)("does not let expression grouping legalize temporal dependency cycles: $speaker", async scene => {
  const { root, source, canon, event, expression, paths } = await setup(scene);
  const toolset = createCompilerProposalToolset(root); await toolset.beginBatch([], "cycle", source.source.id);
  const { evidence: _eventEvidence, ...eventPayload } = event;
  for (const [id, anchorEventId] of [[event.id, "cycle-event"], ["cycle-event", event.id]]) await toolset.tools.find(item => item.name === "propose_canonical_event")!.execute(id!, { proposal_id: `proposal-${id}`, payload: { ...eventPayload, id, storyTime: { kind: "relative", relation: "after", anchorEventId } }, evidence_segment_ids: [source.segmentId] } as never, undefined, undefined, {} as never);
  const { evidence: _evidence, ...base } = expression;
  await toolset.tools.find(item => item.name === "propose_utterance_expression")!.execute("expression", { proposal_id: "expression", payload: { ...base, quotation: { quotationId: "quotation" }, propositions: [{ propositionId: "content" }], fragments: [{ segment_id: source.segmentId, exact: scene.quote }] }, evidence_segment_ids: [source.segmentId], evidence_selectors: paths.map(target_path => ({ segment_id: source.segmentId, exact: scene.quote, target_path, relation: "supports", strength: "explicit" })) } as never, undefined, undefined, {} as never);
  await expect(toolset.tools.find(item => item.name === "finish_compiler_batch")!.execute("finish", { outcome: "complete", reviewed_segments: [], summary: "A temporal cycle cannot become source ordering" } as never, undefined, undefined, {} as never)).rejects.toThrow("CAUSAL_CYCLE");
  expect(await canon.listUtteranceExpressions()).toEqual([]);
  expect(await canon.getEvent(event.id)).toEqual(event);
});
