export { auditCompiler, type CompilerAuditReport } from "./compiler/audit.js";
export { prepareCompilerBatches, runCompilerBatches, CompilerBatchStore, type CompilerBatch } from "./compiler/batches.js";
export { convergeWorldProposals, type WorldConvergenceProgress, type WorldProposalConvergence } from "./compiler/converge.js";
export { EvidenceVerifier, type EvidenceInspection, type EvidenceVerification } from "./compiler/evidence.js";
export { PossibilityCommitService, type PossibilityValidation } from "./compiler/possibility-commit.js";
export { PreparedNovelCache, type PreparedCacheResult, type PreparedCacheRevision, type PreparedNovelBundle } from "./compiler/prepared-cache.js";
export { CompilerProposalService, type CompilerProposalKind } from "./compiler/proposals.js";
export { CompilerCommitService, CompilerValidator, type CompilerConvergenceProgress, type CompilerValidation } from "./compiler/validator.js";
export { evaluateCompilerAgainstGold, compilerGoldSchema, type CompilerEvaluationReport, type CompilerGold, type SetMetric } from "./eval/compiler-eval.js";
export { inspectPreparation, type PreparationInspection, type PreparationStage } from "./workflow/prepare.js";
export { ingestWorkspaceContent, ingestWorkspaceSource } from "./commands/ingest.js";
export { readSourceMaterial, sourceMaterialIdentity, SourceMaterialStore, type SourceMaterialIdentity } from "./storage/source-material-store.js";
export { WorkspaceStore, type SourceDocument, type StoredProject } from "./storage/workspace-store.js";

export { ActorModelStore, deterministicActorProposalSource, type CharacterGoal, type CharacterModel } from "./world/actors.js";
export { commitKnowledgeAwareAction, knowledgeAwareActionSchema, validateActionKnowledge, type ActionGateReport, type KnowledgeAwareAction } from "./world/action-gate.js";
export { CanonicalModelStore, ProposalStore, type CanonicalKind, type CanonicalRevisionRef } from "./world/canonical-model.js";
export { canonicalEventToPossibility } from "./world/canon-runtime.js";
export { loadWorldContext, pinBranchPreparationContexts, WorldContextStore, type CanonicalSnapshot } from "./world/context.js";
export { diffWorldBranches, diffWorldStates, type HistoryDifference, type KnowledgeDifference, type StateDifference, type WorldBranchDiff } from "./world/diff.js";
export { WorldEngine, WorldProjector, validateEventProposal, type ResolvedWorldModelContext, type WorldContextResolver, type WorldModelContext } from "./world/engine.js";
export { fsckWorld, type FsckIssue, type WorldFsckReport } from "./world/fsck.js";
export { buildFrontier, evaluatePossibility, selectEligible, type Frontier, type PossibilityStatus, type SchedulerFactors } from "./world/frontier.js";
export { InitialWorldStore, initialWorldSchema, type InitialWorld } from "./world/initial.js";
export { KnowledgeProjector, type ActorWorldView } from "./world/knowledge.js";
export { isNarrativeInterpretation, NarrativeMetaView, type NarrativeObservation, type NarrativeMetaKind } from "./world/meta.js";
export { modelActorProposalSource, actorActionTemplateSchema, type ActorActionTemplate, type ActorReasoner, type ActorReasoningInput } from "./world/model-actor-policy.js";
export * from "./world/model.js";
export { NarrativeRenderer, type ActorNarrativeFrame, type NarrativeAdapter, type NarrativeEvent, type NarrativeFrame, type NarrativeStyle, type OmniscientNarrativeFrame } from "./world/narrative.js";
export { PossibilityTemplateStore, possibilityTemplateSchema, type PossibilityTemplate } from "./world/possibility-model.js";
export { buildActorScopedActionContext, playerActionCandidateSchema, playerActionToKnowledgeAwareAction, playerTurnInputSchema, PlayerTurnService, validatePlayerActionScope, type ActorScopedActionContext, type PlayerActionCandidate, type PlayerActionTranslator, type PlayerTurnInput, type PlayerTurnResult } from "./world/player-action.js";
export { PlaySessionStore, activePlaySessionSchema, type ActivePlaySession } from "./world/play-session.js";
export { inspectPlayExperience, listPlayableCharacters, performPlayTurn, resolveCharacter, resolveNovelSource, selectPlayExperience, type PlayExperienceCatalog, type PlayableCharacter, type PlayInstanceSummary, type PlayTurnOutcome, type SelectedPlayExperience } from "./world/play-experience.js";
export { runCanonReplay, runIsolatedCanonReplay, verifyHistoryReplay, type CanonReplayResult, type IsolatedCanonReplayResult, type ReplayDiagnostic } from "./world/replay.js";
export { WorldRuntime, adjudicateActorCandidates, type MoveInput, type MoveResult } from "./world/runtime.js";
export { WorldSnapshotStore, type WorldSnapshot } from "./world/snapshot.js";
export { StateSchemaRegistry, DEFAULT_STATE_FIELDS, applyStateDelta, evaluatePredicate, validateEngineInvariants } from "./world/state.js";
export { BranchStore, WorldObjectStore } from "./world/store.js";
export { openWorkspaceWorld, type WorkspaceWorld } from "./world/workspace-runtime.js";
