export { auditCompiler, type CompilerAuditReport } from "./compiler/audit.js";
export { prepareCompilerBatches, runCompilerBatches, CompilerBatchStore, type CompilerBatch } from "./compiler/batches.js";
export { convergeWorldProposals, type WorldProposalConvergence } from "./compiler/converge.js";
export { EvidenceVerifier, type EvidenceVerification } from "./compiler/evidence.js";
export { PossibilityCommitService, type PossibilityValidation } from "./compiler/possibility-commit.js";
export { CompilerProposalService, type CompilerProposalKind } from "./compiler/proposals.js";
export { CompilerCommitService, CompilerValidator, type CompilerValidation } from "./compiler/validator.js";
export { evaluateCompilerAgainstGold, compilerGoldSchema, type CompilerEvaluationReport, type CompilerGold } from "./eval/compiler-eval.js";

export { ActorModelStore, deterministicActorProposalSource, type CharacterGoal, type CharacterModel } from "./world/actors.js";
export { CanonicalModelStore, ProposalStore } from "./world/canonical-model.js";
export { canonicalEventToPossibility } from "./world/canon-runtime.js";
export { loadWorldContext } from "./world/context.js";
export { WorldEngine, WorldProjector, validateEventProposal, type WorldModelContext } from "./world/engine.js";
export { fsckWorld, type WorldFsckReport } from "./world/fsck.js";
export { buildFrontier, evaluatePossibility, selectEligible, type Frontier } from "./world/frontier.js";
export { InitialWorldStore, initialWorldSchema, type InitialWorld } from "./world/initial.js";
export { KnowledgeProjector, type ActorWorldView } from "./world/knowledge.js";
export { NarrativeMetaView, type NarrativeObservation, type NarrativeMetaKind } from "./world/meta.js";
export { modelActorProposalSource, actorActionTemplateSchema, type ActorReasoner, type ActorReasoningInput } from "./world/model-actor-policy.js";
export * from "./world/model.js";
export { NarrativeRenderer, type NarrativeAdapter, type NarrativeFrame, type NarrativeStyle } from "./world/narrative.js";
export { PossibilityTemplateStore, possibilityTemplateSchema, type PossibilityTemplate } from "./world/possibility-model.js";
export { runCanonReplay, type CanonReplayResult } from "./world/replay.js";
export { WorldRuntime, adjudicateActorCandidates, type MoveInput, type MoveResult } from "./world/runtime.js";
export { WorldSnapshotStore, type WorldSnapshot } from "./world/snapshot.js";
export { StateSchemaRegistry, DEFAULT_STATE_FIELDS, applyStateDelta, evaluatePredicate, validateEngineInvariants } from "./world/state.js";
export { BranchStore, WorldObjectStore } from "./world/store.js";
export { openWorkspaceWorld, type WorkspaceWorld } from "./world/workspace-runtime.js";
