import fs from 'node:fs/promises';
import { CanonicalModelStore, ProposalStore } from '../../src/world/canonical-model.js';
import { characterEntryCheckpointSchema } from '../../src/world/model.js';
import { worldStorageRoot } from '../../src/world/paths.js';
import { contentHash } from '../../src/world/canonical.js';
import { WorkspaceStore } from '../../src/storage/workspace-store.js';
import { SourceMaterialStore } from '../../src/storage/source-material-store.js';
import { inspectCompilerStatus } from '../../src/compiler/status.js';
import { CompilerFinishReceipts } from '../../src/compiler/finish-receipts.js';
import { EvidenceAssertionStore } from '../../src/compiler/evidence-assertions.js';
import { createCompilerProposalToolset } from '../../src/compiler/proposal-tools.js';
import { convergeWorldProposals } from '../../src/compiler/converge.js';
import { assertReconciliationDeferralsReviewed } from '../../src/compiler/reconciliation-review-ledger.js';
import { compilerFailureCauseFingerprint } from '../../src/runtime/codex-compile-loop.js';
import { withWorkspaceOperationLock } from '../../src/util/workspace-lock.js';
const root=process.cwd(),dir=new URL('./',import.meta.url);
await withWorkspaceOperationLock(root,'compiler',async()=>{
 const state=JSON.parse(await fs.readFile(new URL('state.json',dir),'utf8')),review=JSON.parse(await fs.readFile(new URL('host-review-cousin-bedroom-entry-checkpoint.json',dir),'utf8'));
 if(state.attempt!==66||contentHash(state)!==contentHash(review.priorState))throw Error('Incident changed');
 const canon=new CanonicalModelStore(root),events=await canon.listEvents(),entities=await canon.listEntities(),store=new ProposalStore(root);
 const pending=await Promise.all((await store.list('pending',state.sourceId)).map(p=>store.readEnvelope('pending',p.id)));
 const draft=pending.find(p=>p.id==='entity-lu-cousins-bedroom-host-v1'),eventDraft=pending.find(p=>p.id==='event-cousin-bedroom-host-checkpoint-v1');
 if(pending.length!==2||!draft||!eventDraft)throw Error('Draft inventory changed');
 const batch=`host-cousin-bedroom-entry-${state.sourceId}-v1`,segment='a28585b1cf867f3e3a16-00003-5c70d7864d11';
 const source=await WorkspaceStore.openReadOnly(root).getSource(state.sourceId);if(!source)throw Error('Source missing');const bytes=await new SourceMaterialStore().read(source);if(!bytes)throw Error('Source missing');
 const exact='他和路明非共同的卧室',prefix='路鸣泽走进';if(!bytes.toString('utf8').includes(prefix+exact))throw Error('Source changed');
 const correction={reviewedAt:new Date().toISOString(),batch,originalReview:review,pending,diagnostic:'UNSUPPORTED_ENTITY_CANONICAL_NAME and missing resolved mention',reason:'The first finish rejected a descriptive normalization absent from the source and an untraced location identity. Read committed annotations and pending inventory: no bedroom mention exists. Preserve the logical location ID and unchanged event draft. Replace only the defective entity draft with source-exact 他和路明非共同的卧室, add that exact nominal mention with the explicit preceding cousin cue, and resolve it as the new location. Retain withdrawn draft and failed finish history. Retry the identical finish only once after all named dependencies are repaired; stop if it fails.'};
 await fs.writeFile(new URL('host-review-cousin-bedroom-trace-correction.json',dir),JSON.stringify(correction,null,2),{flag:'wx'});
 const toolset=createCompilerProposalToolset(root);await toolset.beginBatch([],batch,state.sourceId);const call=(name:string,input:unknown)=>toolset.tools.find(t=>t.name===name)!.execute(name,input as never,undefined,undefined,{} as never);
 const location={...review.location,canonicalName:exact};
 await call('propose_entity',{proposal_id:'entity-lu-cousins-bedroom-exact-host-v1',payload:location,evidence_segment_ids:[segment],evidence_selectors:['/canonicalName','/kind'].map(target_path=>({segment_id:segment,exact,prefix,target_path,relation:'supports',strength:'explicit'}))});
 await call('withdraw_compiler_proposal',{proposal_id:draft.id,reason:'Correct only defective entity draft after failed finish: exact source name and missing resolved mention. Same logical location, preserved event draft and history.'});
 const mention='em-lu-cousins-bedroom-host-v1';
 await call('propose_entity_mention',{proposal_id:mention,annotation_id:mention,selector:{segment_id:segment,exact,prefix},surface:exact,form:'nominal',kind_candidates:['location'],confidence:1});
 await call('propose_entity_resolution',{proposal_id:'res-lu-cousins-bedroom-host-v1',resolution_id:'res-lu-cousins-bedroom-host-v1',mention_id:mention,status:'new-entity',entity_id:location.id,candidates:[{entity_id:location.id,confidence:1,basis_mention_ids:[mention],evidence_assertion_ids:[],rationale:'Exact nominal bedroom mention with preceding cousin name establishes the shared room; no prior bedroom entity exists.'}],rationale:'Host source-reviewed new shared bedroom location, preserving cousin/boy distinction.'});
 await call('finish_compiler_batch',{outcome:'complete',reviewed_segments:[],summary:'Source-reviewed shared bedroom entity and pre-voice-coaching cousin location checkpoint; Lumingfei checkpoint unchanged.'});
 const receipts=new CompilerFinishReceipts(root,state.sourceId,batch),receipt=await receipts.read();if(receipt?.state!=='completed')throw Error('Finish incomplete');await receipts.verify(receipt);
 const result=await convergeWorldProposals(root,state.sourceId);if(result.canonical.blocked.length||result.possibilities.blocked.length)throw Error(JSON.stringify(result));
 const current=await canon.listEvents();for(const e of events)if(contentHash(current.find(c=>c.id===e.id))!==contentHash(e.id===review.original.id?review.next:e))throw Error('Unexpected event change');
 const updated=await canon.listEntities();if(updated.length!==entities.length+1||updated.find(e=>e.id===location.id)?.canonicalName!==exact)throw Error('Entity missing');for(const e of entities)if(contentHash(updated.find(c=>c.id===e.id))!==contentHash(e))throw Error('Existing entity changed');
 const predecessor=new CompilerFinishReceipts(root,state.sourceId,review.originalBatch),old=await predecessor.read();if(!old||old.fingerprint!==review.originalReceipt)throw Error('Original receipt changed');await predecessor.verify(old);
 let gate=false;try{await assertReconciliationDeferralsReviewed(root,state.sourceId);}catch(e){if(String(e).includes('host source review'))gate=true;else throw e;}if(!gate)throw Error('Review gate lost');
 state.appliedRepairHistory.push(state.appliedRepair);state.appliedRepair={repairId:'cousin-source-reviewed-bedroom-checkpoint-v1',failureFingerprint:compilerFailureCauseFingerprint({category:'missing-source-backed-cousin-bedroom-entry',targetIds:['char-lumingze'],dependencyIds:[review.original.id]}),reviewPath:'run-records/2026-09-11-codex-compile-loop/host-review-cousin-bedroom-entry-checkpoint.json',correctionPath:'run-records/2026-09-11-codex-compile-loop/host-review-cousin-bedroom-trace-correction.json',appliedAt:new Date().toISOString()};
 await fs.writeFile(new URL('host-review-cousin-bedroom-entry-checkpoint-result.json',dir),JSON.stringify({receipt:receipt.fingerprint,gateRetained:gate,unchangedEventDraft:true,sourceExactLocation:true}));
 await fs.writeFile(new URL('state.tmp.json',dir),JSON.stringify(state,null,2));await fs.rename(new URL('state.tmp.json',dir),new URL('state.json',dir));console.log(JSON.stringify({ready:true,receipt:receipt.fingerprint,gateRetained:gate}));
});
