import fs from 'node:fs/promises';
import { CanonicalModelStore } from '../../src/world/canonical-model.js';
import { characterEntryCheckpointSchema } from '../../src/world/model.js';
import { contentHash } from '../../src/world/canonical.js';
import { WorkspaceStore } from '../../src/storage/workspace-store.js';
import { SourceMaterialStore } from '../../src/storage/source-material-store.js';
import { inspectCompilerStatus } from '../../src/compiler/status.js';
import { CompilerFinishReceipts } from '../../src/compiler/finish-receipts.js';
import { EvidenceAssertionStore } from '../../src/compiler/evidence-assertions.js';
import { createCompilerProposalToolset } from '../../src/compiler/proposal-tools.js';
import { convergeWorldProposals } from '../../src/compiler/converge.js';
import { assertReconciliationDeferralsReviewed } from '../../src/compiler/reconciliation-review-ledger.js';
import { compilerFailureCauseFingerprint } from '../../src/runtime/codex-compile-loop.js';
import { withWorkspaceOperationLock } from '../../src/util/workspace-lock.js';
import { CompilerProposalObligations } from '../../src/compiler/proposal-obligations.js';
const root=process.cwd(),dir=new URL('./',import.meta.url);
await withWorkspaceOperationLock(root,'compiler',async()=>{
 const state=JSON.parse(await fs.readFile(new URL('state.json',dir),'utf8'));if(state.attempt!==52||state.status!=='needs-review')throw Error('Incident changed');
 const review=JSON.parse(await fs.readFile(new URL('host-review-breakfast-entry-checkpoints.json',dir),'utf8'));
 const canon=new CanonicalModelStore(root),events=await canon.listEvents(),event=events.find(e=>e.id===review.original.id)!,next=review.next;
 if(contentHash(event)!==contentHash(review.original))throw Error('Event changed after failed proposal');
 const batch=`host-breakfast-pre-entry-${state.sourceId}-v1`,reviewPath='run-records/2026-09-11-codex-compile-loop/host-review-breakfast-entry-checkpoints.json';
 const ledger=new CompilerProposalObligations(root,state.sourceId,batch),tool='propose_canonical_event',proposalId='event-breakfast-host-checkpoints-v1',history=ledger.history(tool,proposalId),failed=history.at(-1)!;
 if(failed?.status!=='failed'||new Set(history.filter(a=>a.status==='failed').map(a=>a.inputHash)).size!==1||!failed.diagnostic.includes('ambiguous'))throw Error('Not the single reviewed ambiguity failure');
 const input=structuredClone(failed.input) as {evidence_selectors:Array<{exact:string;target_path:string;occurrence?:number}>};
 const selector=input.evidence_selectors[3]!;if(selector.target_path!=='/observedKnowledge/operations/0/attributionId')throw Error('Wrong selector');
 const source=await WorkspaceStore.openReadOnly(root).getSource(state.sourceId);if(!source)throw Error('Source missing');const bytes=await new SourceMaterialStore().read(source);if(!bytes)throw Error('Immutable source missing');
 const assertions=await new EvidenceAssertionStore(root).listForArtifact('canonical-event',event.id);
 const anchors=assertions.filter(a=>a.target.jsonPointer===selector.target_path).flatMap(a=>a.anchors).filter(a=>bytes.subarray(a.startByte,a.endByte).toString('utf8')===selector.exact);if(anchors.length!==1)throw Error('Original anchor not unique');
 const anchor=anchors[0]!,token=Buffer.from(selector.exact),positions:number[]=[];
 for(let pos=bytes.indexOf(token,54279);pos>=0&&pos+token.length<=103369;pos=bytes.indexOf(token,pos+1))positions.push(pos);
 const occurrence=positions.indexOf(anchor.startByte)+1;if(positions.length!==2||occurrence<1)throw Error('Original source occurrence changed');selector.occurrence=occurrence;
 const correctionRef='run-records/2026-09-11-codex-compile-loop/host-review-breakfast-selector-correction.json';
 await fs.writeFile(new URL('host-review-breakfast-selector-correction.json',dir),JSON.stringify({reviewedAt:new Date().toISOString(),history,anchor,positions,occurrence,input,reason:'Rebuilding the existing selector from exact text omitted its prior byte position. The quotation occurs twice. Bind the single corrected call to the occurrence at the existing verified anchor, keeping the same tool, proposal ID, payload, segment and every other selector. The original failed obligation remains until normal validation succeeds; a failed correction stops.'},null,2),{flag:'wx'});
 const predecessor=new CompilerFinishReceipts(root,state.sourceId,review.originalBatch),oldReceipt=await predecessor.read();if(!oldReceipt||oldReceipt.fingerprint!==review.originalReceipt||oldReceipt.state!=='completed')throw Error('Predecessor changed');await predecessor.verify(oldReceipt);
 const toolset=createCompilerProposalToolset(root);await toolset.beginBatch([],batch,state.sourceId);const call=(name:string,value:unknown)=>toolset.tools.find(t=>t.name===name)!.execute(name,value as never,undefined,undefined,{} as never);
 await ledger.withHostSelectorCorrection(tool,input,[failed.inputHash],'Original byte anchor disambiguates the repeated quotation; payload and proposal identity unchanged.',correctionRef,()=>call(tool,input));
 ledger.assertFinishable();
 await call('finish_compiler_batch',{outcome:'complete',reviewed_segments:[],summary:'Source-reviewed pre-greeting hotel-location checkpoints for the professor, uncle and aunt; existing quotation resolved by its original byte occurrence.'});
 const receipts=new CompilerFinishReceipts(root,state.sourceId,batch),receipt=await receipts.read();if(receipt?.state!=='completed')throw Error('Finish incomplete');await receipts.verify(receipt);
 const result=await convergeWorldProposals(root,state.sourceId);if(result.canonical.blocked.length||result.possibilities.blocked.length)throw Error(JSON.stringify(result));
 const current=await canon.listEvents();for(const e of events)if(contentHash(current.find(c=>c.id===e.id))!==contentHash(e.id===event.id?next:e))throw Error('Unexpected event change');
 await predecessor.verify(oldReceipt);
 let gate=false;try{await assertReconciliationDeferralsReviewed(root,state.sourceId);}catch(e){if(String(e).includes('host source review'))gate=true;else throw e;}if(!gate)throw Error('Original review gate lost');
 state.appliedRepairHistory.push(state.appliedRepair);state.appliedRepair={repairId:'breakfast-source-reviewed-location-checkpoints-v1',failureFingerprint:compilerFailureCauseFingerprint({category:'missing-source-backed-hotel-entry',targetIds:['char-gudeli-an','char-shushu','char-shenshen'],dependencyIds:[event.id]}),reviewPath,appliedAt:new Date().toISOString()};
 await fs.writeFile(new URL('host-review-breakfast-entry-checkpoints-result.json',dir),JSON.stringify({receipt:receipt.fingerprint,gateRetained:gate,onlyEntryCheckpointAdded:true}));
 await fs.writeFile(new URL('state.tmp.json',dir),JSON.stringify(state,null,2));await fs.rename(new URL('state.tmp.json',dir),new URL('state.json',dir));console.log(JSON.stringify({ready:true,receipt:receipt.fingerprint,gateRetained:gate}));
});
