import fs from 'node:fs/promises';
import { ProposalStore, CanonicalModelStore } from '../../src/world/canonical-model.js';
import { contentHash } from '../../src/world/canonical.js';
import { WorkspaceStore } from '../../src/storage/workspace-store.js';
import { SourceMaterialStore } from '../../src/storage/source-material-store.js';
import { CompilerProposalObligations } from '../../src/compiler/proposal-obligations.js';
import { CompilerCommitService } from '../../src/compiler/validator.js';
import { CompilerFinishReceipts } from '../../src/compiler/finish-receipts.js';
import { createCompilerProposalToolset } from '../../src/compiler/proposal-tools.js';
import { readKnowledgeRepairPlan } from '../../src/compiler/knowledge-repair.js';
import { validateAttributionProposalTrace } from '../../src/compiler/attribution-trace.js';
import { withWorkspaceOperationLock } from '../../src/util/workspace-lock.js';
const root=process.cwd(),dir=new URL('./',import.meta.url);
await withWorkspaceOperationLock(root,'compiler',async()=>{
 const state=JSON.parse(await fs.readFile(new URL('state.json',dir),'utf8'));
 if(state.attempt!==26||state.status!=='needs-review'||state.failureFingerprint!=='a7c7f0088d27ba49c117896fa5635360b3258cd945a6ca89ab75ccff6bcd708f')throw Error('Incident changed');
 if([state.appliedRepair,...state.appliedRepairHistory].some(r=>r.failureFingerprint===state.failureFingerprint))throw Error('Targeted repair already applied; stop');
 const sid=state.sourceId,batch=state.knowledgeRepair.batchId,store=new ProposalStore(root),canon=new CanonicalModelStore(root),validator=new CompilerCommitService(root),journal=new CompilerProposalObligations(root,sid,batch);
 const plan=await readKnowledgeRepairPlan(root,sid,batch);if(!plan||plan.events.length!==1||plan.events[0]?.id!=='event-email-open-001')throw Error('Scope changed');
 const pending=await Promise.all((await store.list('pending',sid)).map(p=>store.readEnvelope('pending',p.id)));
 if(pending.length!==4||pending.some(p=>(p.generatedBy as {compilerBatchId:string}).compilerBatchId!==batch))throw Error('Draft inventory changed');
 const obligations=journal.unresolved();if(obligations.length!==2)throw Error('Obligation inventory changed');
 const event=pending.find(p=>p.kind==='canonical-event')!,attr=pending.find(p=>p.kind==='attribution')!;
 const history=journal.history('propose_canonical_event',String(event.id)),success=history.findLast(h=>h.status==='succeeded')!;
 const last=history.at(-1)!;
 if(last.inputHash!=='60a349c496a76a63f1fc6ed56546f6177ac5992a6da861a382c1072081b524f1'||!last.diagnostic.includes('already exists with different content'))throw Error('Lifecycle incident changed');
 const original=success.input as Record<string,any>,attempt=last.input as Record<string,any>;
 if(contentHash(original.payload)!==contentHash(attempt.payload)||contentHash(original.evidence_selectors)===contentHash(attempt.evidence_selectors))throw Error('Not an evidence-only immutable draft collision');
 const {evidence:_e,...payload}=event.payload as Record<string,any>;
 if(contentHash(payload)!==contentHash(original.payload))throw Error('Original successful event altered');
 const preview=await validator.validatePendingStructure(sid);
 if(preview.length!==1||preview[0]!.errors.length!==1||preview[0]!.errors[0]!.code!=='READ_SOURCE_ATTRIBUTION_MISMATCH')throw Error(JSON.stringify(preview));
 const doc=await WorkspaceStore.openReadOnly(root).getSource(sid);if(!doc)throw Error('Missing source');
 const bytes=await new SourceMaterialStore().read(doc);if(!bytes)throw Error('Missing immutable source');
 const lines=bytes.toString('utf8').split('\n');
 if(!lines[2380]?.includes('路明非打开那封新邮件，愣住了。')||lines[2384]?.trim()!=='诺诺'||!lines[2382]?.includes('时间是18：00'))throw Error('Source changed');
 const entityId='artifact-nono-invitation-email-00013',entities=await canon.listEntities();
 if(entities.some(e=>e.id===entityId||/邮件|电子信/.test(e.canonicalName)))throw Error('Document identity requires re-review');
 const reason='Host source review confirms a written invitation, opened by Lumingfei, signed Nono. The original scoped review missed the required canonical document holder for read acquisition. Add only this source-grounded document via a separate normal host proposal; the original knowledge plan remains immutable. Repair the failed document attribution with its same proposal ID and same logical attribution ID, then withdraw its successful character-holder predecessor through normal tools. The event retry only changed evidence selectors on an immutable successful draft and reintroduced forbidden sourceActorId before correction: adjudicate these invalid lifecycle calls, retain the successful event unchanged. No evidence supports attendance or acceptance; no world outcome, checkpoint, namespace, or original deferred report is changed.';
 const reviewPath='run-records/2026-09-11-codex-compile-loop/host-review-email-document.json';
 await fs.writeFile(new URL('host-review-email-document.json',dir),JSON.stringify({reviewedAt:new Date().toISOString(),reason,stateFailure:state.error,fingerprint:state.failureFingerprint,priorAppliedRepair:state.appliedRepair,plan,pending,preview,sourceLines:lines.slice(2380,2387),entityInventory:entities,history,obligations:obligations.map(o=>({identity:o,history:journal.history(o.tool,o.proposalId)})),validation:'Focused knowledge, attribution, obligation and finish tests; reviewer TypeScript check.'},null,2),{flag:'wx'});
 const segment='a28585b1cf867f3e3a16-00013-2df5b1eb46fa';
 const tools=createCompilerProposalToolset(root),call=(name:string,input:unknown)=>tools.tools.find(t=>t.name===name)!.execute(name,input as never,undefined,undefined,{} as never);
 const hostBatch=`host-email-document-${sid}-v1`,entityProposal='entity-nono-invitation-email-host-v1';
 await tools.beginBatch([],hostBatch,sid);
 await call('propose_entity',{proposal_id:entityProposal,payload:{id:entityId,kind:'artifact',canonicalName:'诺诺的晚宴邀请邮件',aliases:[]},evidence_segment_ids:[segment],evidence_selectors:[{segment_id:segment,exact:lines.slice(2380,2385).join('\n').trim(),target_path:'/canonicalName',relation:'supports',strength:'strong-inference',interpretation:'Descriptive identity for the new email explicitly opened here, containing the dinner invitation and Nono signature.'},{segment_id:segment,exact:'路明非打开那封新邮件，愣住了。',target_path:'/kind',relation:'supports',strength:'explicit'}]});
 await call('finish_compiler_batch',{outcome:'complete',reviewed_segments:[],summary:'Host source review adds the original written email as a document artifact; existing knowledge drafts and plan are preserved.'});
 const hostReceipts=new CompilerFinishReceipts(root,sid,hostBatch),hostReceipt=await hostReceipts.read();if(hostReceipt?.state!=='completed')throw Error('Document batch incomplete');await hostReceipts.verify(hostReceipt);
 const accepted=await validator.accept('entity',entityProposal);if(!accepted.accepted)throw Error(JSON.stringify(accepted));
 await tools.beginBatch([],batch,sid);
 const failedAttr=obligations.find(o=>o.tool==='propose_attribution')!;
 if(journal.history(failedAttr.tool,failedAttr.proposalId).filter(h=>h.status==='failed').length!==1)throw Error('Document attribution retry exhausted');
 const input=structuredClone(failedAttr.input) as Record<string,any>;
 input.payload.holderEntityId=entityId;
 input.evidence_selectors.push({segment_id:segment,exact:'路明非打开那封新邮件，愣住了。',target_path:'/holderEntityId',relation:'supports',strength:'explicit'});
 await call('propose_attribution',input);
 await call('withdraw_compiler_proposal',{proposal_id:attr.id,reason:`Source-reviewed document-holder correction under ${failedAttr.proposalId}; preserve original in withdrawal history. Audit ${reviewPath}`});
 for(const p of pending.filter(p=>p.id!==attr.id))if(contentHash(await store.readEnvelope('pending',String(p.id)))!==contentHash(p))throw Error('Unrelated draft changed');
 const active=(await store.list('pending',sid)).map(p=>p.id);
 const diagnostics=await validator.validatePendingStructure(sid),trace=await validateAttributionProposalTrace(root,sid,active,[],[]);
 if(diagnostics.length||trace.length)throw Error(JSON.stringify({diagnostics,trace}));
 journal.reviewUnsupported('propose_canonical_event',String(event.id),reason,reviewPath);
 journal.assertFinishable();
 await call('finish_compiler_batch',{outcome:'complete',reviewed_segments:[],summary:'Host review supplies the missing document identity and repairs only the attribution holder; original event draft, knowledge mode and semantic content retained.',target_reviews:[{target:'event:event-email-open-001',disposition:'proposed',evidence_segment_ids:[segment],summary:'Lumingfei reads the written invitation from the now source-grounded email document. No attendance, acceptance, future truth, other event field or checkpoint is changed.'}]});
 const receipts=new CompilerFinishReceipts(root,sid,batch),receipt=await receipts.read();if(receipt?.state!=='completed')throw Error('Original batch finish failed');await receipts.verify(receipt);
 if(contentHash(await readKnowledgeRepairPlan(root,sid,batch))!==contentHash(plan)||contentHash(await store.readEnvelope('rejected',String(attr.id)))!==contentHash(attr))throw Error('Original history changed');
 state.appliedRepairHistory.push(state.appliedRepair);state.appliedRepair={repairId:'email-document-holder-and-lifecycle-host-v1',failureFingerprint:state.failureFingerprint,reviewPath,appliedAt:new Date().toISOString()};
 await fs.writeFile(new URL('host-review-email-document-result.json',dir),JSON.stringify({receiptFingerprint:receipt.fingerprint,documentReceipt:hostReceipt.fingerprint,entityId,preservedEventHash:contentHash(event),preservedPlan:true,diagnostics,trace},null,2));
 await fs.writeFile(new URL('state.tmp.json',dir),JSON.stringify(state,null,2));await fs.rename(new URL('state.tmp.json',dir),new URL('state.json',dir));
 console.log(JSON.stringify({ready:true,receipt:receipt.fingerprint,document:entityId}));
});
