import fs from 'node:fs/promises';
import { CanonicalModelStore } from '../../src/world/canonical-model.js';
import { characterEntryCheckpointSchema } from '../../src/world/model.js';
import { worldStorageRoot } from '../../src/world/paths.js';
import { contentHash } from '../../src/world/canonical.js';
import { WorkspaceStore } from '../../src/storage/workspace-store.js';
import { SourceMaterialStore } from '../../src/storage/source-material-store.js';
import { inspectCompilerStatus } from '../../src/compiler/status.js';
import { CompilerFinishReceipts } from '../../src/compiler/finish-receipts.js';
import { EvidenceAssertionStore } from '../../src/compiler/evidence-assertions.js';
import { createCompilerProposalToolset } from '../../src/compiler/proposal-tools.js';
import { convergeWorldProposals } from '../../src/compiler/converge.js';
import { assertReconciliationDeferralsReviewed } from '../../src/compiler/reconciliation-review-ledger.js';
import { compilerFailureCauseFingerprint } from '../../src/runtime/codex-compile-loop.js';
import { withWorkspaceOperationLock } from '../../src/util/workspace-lock.js';
const root=process.cwd(),dir=new URL('./',import.meta.url);
import { generateEntityResolutionCandidates, EntityResolutionStore } from '../../src/compiler/entity-resolution.js';
await withWorkspaceOperationLock(root,'compiler',async()=>{
 const state=JSON.parse(await fs.readFile(new URL('state.json',dir),'utf8'));if(state.attempt!==82||state.status!=='needs-review')throw Error('Incident changed');const status=(await inspectCompilerStatus(root,state.sourceId)).sources[0]!;if(status.sourceIntegrity!=='verified'||status.hasUnresolvedObligations||status.worldProposalInventory.pending)throw Error('Unreviewed obligations');
 const canon=new CanonicalModelStore(root),events=await canon.listEvents(),entities=await canon.listEntities(),resolutions=new EntityResolutionStore(root),before=await resolutions.list(state.sourceId);const priorReview=JSON.parse(await fs.readFile(new URL(state.appliedRepair.reviewPath.split('/').at(-1)!,dir),'utf8'));for(const t of priorReview.targets)if(!before.some(r=>r.mentionId===t.mention.id&&r.entityId===t.entity.id&&r.status==='resolved'))throw Error('Previous targeted failure recurred');
 const batch=`host-fingel-identity-links-${state.sourceId}-v1`,specs=[
 ['em-fingel','char-fingel','The narrator names Fingel as Lumingfei roommate in room 303; same student introduced by full name at the station, with short name used immediately afterward.'],
 ['m-fingel-current','char-fingel','Fingel explains the exam to Lumingfei in the continuing roommate dialogue. Resolve speaker identity without endorsing the described supernatural rules.'],
 ['m-fingel-01-v2','char-fingel','The forum account is explicitly narrated as Fingel, the academy news editor and Lumingfei roommate. Resolve the named author, without treating a forum appearance as physical presence.'],
 ['m-fingel-02','char-fingel','The next forum post names the same Fingel opening the vote; preserve this separate observation and the attributed content.'],
 ['em-fingel-1','char-fingel','The exam scene explicitly recalls Fingel instructions. Same roommate referent, not an additional live utterance or physical exam-room appearance.'],
 ['m-fingel-1','char-fingel','The narrator explicitly names Lumingfei and Fingel dancing together at the academy party; same established student.'],
 ['em-finger','char-fingel','Despite the opaque finger ID, exact bytes name Fingel in Lumingfei report about the roses at the party. Resolve the reported person without adopting the mistaken interpretation.'],
 ['em-fingel-03','char-fingel','The narrator names Fingel alongside Nono among Lumingfei school acquaintances, contrasting them with Old Tang; no new physical presence in the car scene.'],
 ['em-fingel-b19','char-fingel','Fingel is named among the three swimmers and Lumingfei immediately introduces him to Old Tang as his senior student.'],
 ['mention-fingel-00023','char-fingel','The narrator names Fingel composing the campus news headline in the same room 303 with Lumingfei. Same roommate and news editor, preserving the headline as reported text.'],
 ] as const;
 const source=await WorkspaceStore.openReadOnly(root).getSource(state.sourceId);if(!source)throw Error('Source missing');const bytes=await new SourceMaterialStore().read(source);if(!bytes)throw Error('Source missing');const lines=bytes.toString('utf8').split('\n');
 const targets=[];for(const [mentionId,entityId,rationale] of specs){if(before.some(r=>r.mentionId===mentionId))throw Error('Resolution already exists');const discovery=await generateEntityResolutionCandidates(root,state.sourceId,mentionId,batch),mention=discovery.mention,entity=entities.find(e=>e.id===entityId);if(!entity||!mention.kindCandidates.includes(entity.kind)||bytes.subarray(mention.anchor.startByte,mention.anchor.endByte).toString('utf8')!==mention.surface)throw Error('Source/identity mismatch');const context=lines.slice(Math.max(0,mention.anchor.startLine-18),mention.anchor.endLine+7);targets.push({mention,entity,discovery,context,rationale});}
 const expectedLines=[1193,1274,1570,1571,1650,2418,2735,3639,3815,5054];if(targets.some((t,i)=>t.mention.anchor.startLine!==expectedLines[i]))throw Error('Reviewed context moved');
 const legacyOrigins:string[]=[],receipts=[];for(const batchId of new Set(targets.map(t=>t.mention.derivation.compilerBatchId))){if(!batchId)throw Error('Observation origin missing');const store=new CompilerFinishReceipts(root,state.sourceId,batchId),receipt=await store.read();if(!receipt){if(!status.completedBatchIds.includes(batchId))throw Error('Origin neither receipted nor legacy checkpointed');legacyOrigins.push(batchId);continue;}if(receipt.state!=='completed')throw Error('Incomplete observation receipt');await store.verify(receipt);receipts.push({store,receipt});}
 const ledgerDir=worldStorageRoot(root)+'/compiler/reconciliation-reviews/'+state.sourceId,ledgers=[];for(const file of await fs.readdir(ledgerDir)){const l=JSON.parse(await fs.readFile(ledgerDir+'/'+file,'utf8'));const results=l.results?.filter((r:{target:string})=>specs.some(([m,e])=>r.target.includes(m)||r.target==='character:'+e));if(results?.length)ledgers.push({file,results});}
 const reviewPath='run-records/2026-09-11-codex-compile-loop/host-review-fingel-identity-links.json';await fs.writeFile(new URL('host-review-fingel-identity-links.json',dir),JSON.stringify({reviewedAt:new Date().toISOString(),priorState:state,targets,identityIntroduction:{startLine:815,endLine:821,context:lines.slice(814,821)},ledgers,legacyOrigins,legacyPolicy:'Existing completed observation checkpoints without modern receipts are readable under docs/agent-tool-recovery.md; do not synthesize, replace or certify their missing receipts. All new resolution proposals require a verified completed finish. Initial preflight stopped before any proposal mutation.',originalReceipts:receipts.map(r=>r.receipt),reason:'Ten individually reviewed Fingel references supported by full-name introduction followed by short name at lines 815-821 and the continuing roommate, school, news editor and dialogue contexts. Preserve distinct observations, forum attribution, recalled speech, mistaken claims and remote references. No new aliases, goals, powers, knowledge or physical participation. No relevant original deferral was found; all unrelated deferrals, canonical artifacts, source-accounting obligations, original observations and receipts remain unchanged.'},null,2),{flag:'wx'});
 const toolset=createCompilerProposalToolset(root);await toolset.beginBatch([],batch,state.sourceId);const call=(name:string,input:unknown)=>toolset.tools.find(t=>t.name===name)!.execute(name,input as never,undefined,undefined,{} as never);
 for(const t of targets){const id='res-'+t.mention.id+'-host-v1';await call('propose_entity_resolution',{proposal_id:id,resolution_id:id,mention_id:t.mention.id,status:'resolved',entity_id:t.entity.id,candidates:[{entity_id:t.entity.id,confidence:1,basis_mention_ids:[t.mention.id],evidence_assertion_ids:[],rationale:t.rationale}],rationale:t.rationale});}
 await call('finish_compiler_batch',{outcome:'complete',reviewed_segments:[],summary:'Host source-reviewed ten separate Fingel name references. No entity, event, evidence or accounting waiver.'});
 const store=new CompilerFinishReceipts(root,state.sourceId,batch),receipt=await store.read();if(receipt?.state!=='completed')throw Error('Finish incomplete');await store.verify(receipt);const result=await convergeWorldProposals(root,state.sourceId);if(result.canonical.blocked.length||result.possibilities.blocked.length)throw Error(JSON.stringify(result));
 const after=await resolutions.list(state.sourceId);if(after.length!==before.length+specs.length)throw Error('Unexpected resolution count');for(const old of before)if(contentHash(after.find(r=>r.id===old.id))!==contentHash(old))throw Error('Prior resolution changed');for(const t of targets)if(!after.some(r=>r.mentionId===t.mention.id&&r.entityId===t.entity.id&&r.status==='resolved'))throw Error('Resolution missing');if(contentHash(await canon.listEvents())!==contentHash(events)||contentHash(await canon.listEntities())!==contentHash(entities))throw Error('World artifacts changed');for(const r of receipts)await r.store.verify(r.receipt);
 let gate=false;try{await assertReconciliationDeferralsReviewed(root,state.sourceId);}catch(e){if(String(e).includes('host source review'))gate=true;else throw e;}if(!gate)throw Error('Review gate lost');state.appliedRepairHistory.push(state.appliedRepair);state.appliedRepair={repairId:'source-reviewed-fingel-identity-links-v1',failureFingerprint:compilerFailureCauseFingerprint({category:'missing-context-supported-entity-resolutions',targetIds:specs.map(s=>s[0]),dependencyIds:[...new Set(specs.map(s=>s[1]))]}),reviewPath,appliedAt:new Date().toISOString()};
 await fs.writeFile(new URL('host-review-fingel-identity-links-result.json',dir),JSON.stringify({receipt:receipt.fingerprint,gateRetained:gate,addedResolutions:specs.length,canonicalArtifactsUnchanged:true}));await fs.writeFile(new URL('state.tmp.json',dir),JSON.stringify(state,null,2));await fs.rename(new URL('state.tmp.json',dir),new URL('state.json',dir));console.log(JSON.stringify({ready:true,receipt:receipt.fingerprint,gateRetained:gate}));
});
