import fs from "node:fs/promises";
import { ProposalStore } from "../../src/world/canonical-model.js";
import { contentHash } from "../../src/world/canonical.js";
import { WorkspaceStore } from "../../src/storage/workspace-store.js";
import { SourceMaterialStore } from "../../src/storage/source-material-store.js";
import { SourceAnnotationStore, quotationSchema } from "../../src/compiler/annotations.js";
import { EvidenceVerifier } from "../../src/compiler/evidence.js";
import { evidenceAssertionSchema } from "../../src/world/model.js";
import { createCompilerProposalToolset } from "../../src/compiler/proposal-tools.js";
import { CompilerFinishReceipts } from "../../src/compiler/finish-receipts.js";
import { CompilerProposalObligations } from "../../src/compiler/proposal-obligations.js";
import { validateAttributionProposalTrace } from "../../src/compiler/attribution-trace.js";
import { readKnowledgeRepairPlan } from "../../src/compiler/knowledge-repair.js";
import { compilerFailureFingerprint } from "../../src/runtime/codex-compile-loop.js";
import { withWorkspaceOperationLock } from "../../src/util/workspace-lock.js";
const root=process.cwd(),dir=new URL("./",import.meta.url);
await withWorkspaceOperationLock(root,"compiler",async()=>{
  const state=JSON.parse(await fs.readFile(new URL("state.json",dir),"utf8"));
  if(state.attempt!==12||state.status!=="needs-review"||!state.knowledgeRepair.pending)throw Error("Incident changed.");
  const sid=state.sourceId,batch=state.knowledgeRepair.batchId,store=new ProposalStore(root);
  new CompilerProposalObligations(root,sid,batch).assertFinishable();
  const receipts=new CompilerFinishReceipts(root,sid,batch);if(await receipts.read())throw Error("A finish receipt already exists; preserve it.");
  const plan=await readKnowledgeRepairPlan(root,sid,batch);if(!plan||plan.events[0]?.id!=="event-dragontext-00007")throw Error("Target scope changed.");
  const pending=await Promise.all((await store.list("pending",sid)).map(p=>store.readEnvelope("pending",p.id)));
  if(pending.length!==4||pending.some(p=>(p.generatedBy as {compilerBatchId?:string}).compilerBatchId!==batch))throw Error("Pending drafts changed.");
  const old=pending.find(p=>p.kind==="proposition")!;if(!old)throw Error("Missing proposition draft.");
  const assertions=(old.evidenceAssertions as unknown[]).map(a=>evidenceAssertionSchema.parse(a));
  const obj=assertions.find(a=>a.target.jsonPointer==="/object/value");if(!obj||obj.anchors.length!==1)throw Error("Unexpected object assertion.");
  const doc=await WorkspaceStore.openReadOnly(root).getSource(sid);if(!doc)throw Error("Missing source.");
  const bytes=await new SourceMaterialStore().read(doc);if(!bytes)throw Error("Missing immutable source bytes.");
  const quote=quotationSchema.parse(await new SourceAnnotationStore(root).read(sid,"q-gude-dragontext-translation-00007"));
  const exact="赞颂我王的苏醒，毁灭即是新生", originalExact=bytes.subarray(obj.anchors[0]!.startByte,obj.anchors[0]!.endByte).toString("utf8");
  if(originalExact!==`“${exact}。”古德里安教授解释`)throw Error("Original failing anchor changed.");
  if((await new EvidenceVerifier(root).inspectAnchor(quote.anchor)).excerpt!==`${exact}。`)throw Error("Original quotation changed.");
  const payload=old.payload as Record<string,any>;
  if(payload.object.value!==exact||payload.id!=="prop-gude-dragontext-meaning-00007")throw Error("Proposition semantics changed.");
  const issues=await validateAttributionProposalTrace(root,sid,pending.map(p=>String(p.id)),[],[]);
  if(issues.length!==1||!issues[0]!.includes("prop-gude-dragontext-meaning-00007 object evidence is outside"))throw Error("Unexpected complete trace diagnostic.");
  const event=pending.find(p=>p.kind==="canonical-event")!.payload as Record<string,any>;
  const ops=event.observedKnowledge.operations;
  if(ops.length!==1||ops[0].actorId!=="char-lumingfei"||ops[0].status!=="heard"||ops[0].acquisitionMode!=="told")throw Error("Knowledge outcome needs additional review.");
  const reviewPath="run-records/2026-09-11-codex-compile-loop/host-review-dragontext-anchor.json";
  await fs.writeFile(new URL("host-review-dragontext-anchor.json",dir),JSON.stringify({reviewedAt:new Date().toISOString(),sourceId:sid,batchId:batch,originalFailure:state.error,issues,plan,quote,originalExact,correctedExact:exact,pending,
    reason:"The original proposition content matches the spoken translation. Its object selector incorrectly includes quotation punctuation and the narrator's speaker cue. The model corrected attribution selectors instead, leaving this proposition assertion unchanged through two failed finishes. Host authorizes only narrowing the proposition object selector to the verbatim content inside the existing quotation. Preserve all semantic payloads, the other two proposition selectors, and three unrelated active drafts. This is a correction of an immutable successful draft, so stage a justified successor and withdraw only its predecessor through normal tools. Do not change the original plan, quotation, checkpoint or obligation history.",validation:"Relevant quotation/knowledge/proposal/finish regression tests and script/repository type checks passed before application."},null,2),{flag:"wx"});
  const tools=createCompilerProposalToolset(root);await tools.beginBatch([],batch,sid);
  const call=(name:string,input:unknown)=>tools.tools.find(t=>t.name===name)!.execute(name,input as never,undefined,undefined,{} as never);
  const {evidence:_evidence,...inputPayload}=payload;
  const successor=`prop-gude-dragontext-meaning-object-anchor-host-v1-${batch}`;
  const segmentId="a28585b1cf867f3e3a16-00007-26df32014434";
  const selectors=assertions.map(a=>{
    if(a.anchors.length!==1)throw Error("Preserve multi-anchor evidence for separate review.");
    return {segment_id:segmentId,target_path:a.target.jsonPointer,exact:a.target.jsonPointer==="/object/value"?exact:bytes.subarray(a.anchors[0]!.startByte,a.anchors[0]!.endByte).toString("utf8"),relation:a.relation,strength:a.strength,...(a.interpretation?{interpretation:a.interpretation}:{})};
  });
  await call("propose_proposition",{proposal_id:successor,payload:inputPayload,evidence_segment_ids:[segmentId],evidence_selectors:selectors});
  const replacement=await store.readEnvelope("pending",successor);
  if(contentHash(replacement.payload)!==contentHash(old.payload))throw Error("Correction changed proposition content.");
  const prospective=pending.filter(p=>p.id!==old.id).map(p=>String(p.id)).concat(successor);
  if((await validateAttributionProposalTrace(root,sid,prospective,[],[])).length)throw Error("Corrected trace still fails; retain drafts for review.");
  await call("withdraw_compiler_proposal",{proposal_id:old.id,reason:`Host-reviewed object anchor correction; successor ${successor} preserves the complete semantic payload and other assertions. Audit ${reviewPath}`});
  for(const p of pending.filter(p=>p.id!==old.id))if(contentHash(await store.readEnvelope("pending",String(p.id)))!==contentHash(p))throw Error("Unrelated active draft changed.");
  await call("finish_compiler_batch",{outcome:"complete",reviewed_segments:[],summary:"Host reviewed the original source translation and corrected only the proposition object anchor; preserve heard translation without inferring fluency.",target_reviews:[{target:"event:event-dragontext-00007",disposition:"proposed",evidence_segment_ids:[segmentId],summary:"Lumingfei hears Gudelian's spoken translation. The source explicitly retains his inability to understand dragon language; no language ability, initial checkpoint, or other event field is changed."}]});
  const receipt=await receipts.read();if(receipt?.state!=="completed")throw Error("Original-scope finish incomplete.");await receipts.verify(receipt);
  state.appliedRepairHistory=[...(state.appliedRepairHistory??[]),state.appliedRepair];
  state.appliedRepair={repairId:"dragontext-proposition-object-selector-v1",failureFingerprint:compilerFailureFingerprint(state.error),reviewPath,appliedAt:new Date().toISOString()};
  await fs.writeFile(new URL("host-review-dragontext-anchor-result.json",dir),JSON.stringify({receiptFingerprint:receipt.fingerprint,successor,originalPreservedInRejectedHistory:contentHash(await store.readEnvelope("rejected",String(old.id)))===contentHash(old),semanticPayloadUnchanged:true},null,2));
  await fs.writeFile(new URL("state.tmp.json",dir),JSON.stringify(state,null,2));await fs.rename(new URL("state.tmp.json",dir),new URL("state.json",dir));
  console.log(JSON.stringify({ready:true,batchId:batch,receiptFingerprint:receipt.fingerprint,unrelatedDraftsPreserved:3}));
});
