import fs from "node:fs/promises";
import { WorkspaceStore } from "../../src/storage/workspace-store.js";
import { SourceMaterialStore } from "../../src/storage/source-material-store.js";
import { CanonicalModelStore } from "../../src/world/canonical-model.js";
import { SourceAnnotationStore } from "../../src/compiler/annotations.js";
import { EntityResolutionStore } from "../../src/compiler/entity-resolution.js";
import { inspectCompilerStatus } from "../../src/compiler/status.js";
import { CompilerFinishReceipts } from "../../src/compiler/finish-receipts.js";
import { createCompilerProposalToolset } from "../../src/compiler/proposal-tools.js";
import { writeKnowledgeRepairPlan, buildKnowledgeRepairPrompt } from "../../src/compiler/knowledge-repair.js";
import { assertReconciliationDeferralsReviewed } from "../../src/compiler/reconciliation-review-ledger.js";
import { validateCommittedAttributionTrace } from "../../src/compiler/attribution-trace.js";
import { convergeWorldProposals } from "../../src/compiler/converge.js";
import { EvidenceAssertionStore } from "../../src/compiler/evidence-assertions.js";
import { contentHash } from "../../src/world/canonical.js";
import { compilerFailureFingerprint } from "../../src/runtime/codex-compile-loop.js";
import { withWorkspaceOperationLock } from "../../src/util/workspace-lock.js";
const root=process.cwd(),dir=new URL("./",import.meta.url);
await withWorkspaceOperationLock(root,"compiler",async()=>{
  const state=JSON.parse(await fs.readFile(new URL("state.json",dir),"utf8"));
  if(state.attempt!==24||state.status!=="needs-review"||state.knowledgeRepair.pending)throw Error("Incident changed.");
  const source=(await inspectCompilerStatus(root,state.sourceId)).sources.find(s=>s.sourceId===state.sourceId)!;
  if(source.sourceIntegrity!=="verified"||source.hasUnresolvedObligations||source.worldProposalInventory.pending)throw Error("Unreviewed source or obligations.");
  const canon=new CanonicalModelStore(root), annotations=new SourceAnnotationStore(root);
  for(const a of await canon.listAttributions())if((await validateCommittedAttributionTrace(root,state.sourceId,a)).length)throw Error("Prior trace repair has not passed.");
  const events=await canon.listEvents();let event=events.find(e=>e.id==="event-angier-call-00007")!;
  if(!event||event.observedKnowledge?.operations.length||event.observedOutcome.operations.length)throw Error("Target changed.");
  const oldBatch=`reconcile-${state.sourceId}-bounded-codex-target-review-v1-20260912-2`;
  const oldStore=new CompilerFinishReceipts(root,state.sourceId,oldBatch),old=await oldStore.read();
  if(old?.state!=="completed")throw Error("Original batch unfinished.");await oldStore.verify(old);
  const report=old.identity.input.target_reviews?.find(r=>r.target===`event:${event.id}`);
  if(report?.disposition!=="capability-gap"||report.summary!=="The call decides that the activity continues and discusses repairs, but no supported deterministic catalog field records that decision or an unquantified repair cost.")throw Error("Original report changed.");
  const doc=await WorkspaceStore.openReadOnly(root).getSource(state.sourceId);if(!doc)throw Error("Missing source.");
  const bytes=await new SourceMaterialStore().read(doc);if(!bytes)throw Error("Missing immutable bytes.");
  const lines=bytes.toString("utf8").split("\n");
  const exact=lines[1165]?.match(/“([^”]+)”校长爽朗地笑/u)?.[1];
  if(!exact||!exact.startsWith("算啦，我只是开个玩笑，从校董基金里出这笔钱吧")||!exact.endsWith("我们这些老家伙不会出尔反尔。"))throw Error("Original final funding answer changed");
  if(event.readerSummary!=="曼施坦因教授通过电话向昂热校长报告自由一日损失。昂热校长决定不终止活动，并让恺撒承担草坪维修费用。")throw Error("Original erroneous summary changed");
  const correctedSummary="曼施坦因教授通过免提电话向昂热校长报告自由一日损失。昂热先询问恺撒是否愿意支付草坪修复费用，随后明确说明只是玩笑，改由校董基金出资，并允许学生享受自由一日。";
  const mapping=(await new EntityResolutionStore(root).list(state.sourceId)).filter(r=>["em-angier","em-manshi"].includes(r.mentionId));
  if(!mapping.some(r=>r.mentionId==="em-angier"&&r.entityId==="char-angier")||!mapping.some(r=>r.mentionId==="em-manshi"&&r.entityId==="char-manshtein"))throw Error("Speaker/addressee mapping changed");
  const quoteId="q-angier-final-funding-00007",segmentId="a28585b1cf867f3e3a16-00007-26df32014434";
  const annotationBefore=await annotations.list(state.sourceId);
  if(annotationBefore.some(a=>a.id===quoteId))throw Error("Original correction scope already exists");
  const dependencies={claims:await canon.listClaims(),propositions:await canon.listPropositions(),attributions:await canon.listAttributions()};
  const batchId=`reconcile-${state.sourceId}-knowledge-effects-${state.semanticRunId}-12`,reviewPath="run-records/2026-09-11-codex-compile-loop/host-review-funding-knowledge.json";
  const review={reviewedAt:new Date().toISOString(),sourceId:state.sourceId,batchId,report,originalFinishFingerprint:old.fingerprint,exact,sourceLines:lines.slice(1157,1169),mapping,dependencies,baseline:event,
    finding:"Host read the original deferred report and full telephone exchange. The canonical summary incorrectly treats Angier's joke asking Caesar to pay as the final decision, despite the explicit retraction and board-fund answer. Correct only that erroneous reader summary through normal proposal validation; preserve every other event field. Add the exact final directly spoken answer with established remote speaker and listener. The knowledge supplement may only record Manshtein hearing this answer, not fund movement, a numeric repair charge or an executed rule. Preserve original deferrals and all publication gates.",correctedSummary,
    priorKnowledgeRepair:state.knowledgeRepair,priorAppliedRepair:state.appliedRepair,namespaceUnchanged:state.semanticRunId,validation:"Knowledge scope, quotation trace, normal finish and obligation regression tests and type checks passed before application."};
  await fs.writeFile(new URL("host-review-funding-knowledge.json",dir),JSON.stringify(review,null,2),{flag:"wx"});
  const observationBatch=`host-funding-answer-${state.sourceId}-v1`,tools=createCompilerProposalToolset(root);
  await tools.beginBatch([],observationBatch,state.sourceId);
  const call=(name:string,input:unknown)=>tools.tools.find(t=>t.name===name)!.execute(name,input as never,undefined,undefined,{} as never);
  await call("propose_quotation",{proposal_id:"q-angier-funding-host-v1",annotation_id:quoteId,selector:{segment_id:segmentId,exact},mode:"direct",speaker_mention_id:"em-angier",addressee_mention_ids:["em-manshi"],scene_id:"ds-battle",attribution_confidence:1});
  const oldAssertions=await new EvidenceAssertionStore(root).listForArtifact("canonical-event",event.id);
  const selectors=oldAssertions.flatMap(a=>a.anchors.map(anchor=>({segment_id:segmentId,exact:bytes.subarray(anchor.startByte,anchor.endByte).toString("utf8"),target_path:a.target.jsonPointer,relation:a.relation,strength:a.strength,...(a.interpretation?{interpretation:a.interpretation}:{})})));
  selectors.push({segment_id:segmentId,exact,target_path:"/readerSummary",relation:"supports",strength:"explicit"});
  const {evidence:oldEvidence,...payload}=event;
  await call("propose_canonical_event",{proposal_id:"event-angier-final-funding-host-v1",payload:{...payload,readerSummary:correctedSummary},evidence_segment_ids:[segmentId],evidence_selectors:selectors});
  await call("finish_compiler_batch",{outcome:"complete",reviewed_segments:[],summary:"Host source review corrects the final funding answer, preserving all other event fields and source history."});
  const observationStore=new CompilerFinishReceipts(root,state.sourceId,observationBatch),receipt=await observationStore.read();if(receipt?.state!=="completed")throw Error("Observation finish incomplete.");await observationStore.verify(receipt);
  for(const annotation of annotationBefore)if(contentHash(await annotations.read(state.sourceId,annotation.id))!==contentHash(annotation))throw Error("Existing annotation changed.");
  const convergence=await convergeWorldProposals(root,state.sourceId);if(convergence.canonical.blocked.length||convergence.possibilities.blocked.length)throw Error(JSON.stringify(convergence));
  const current=await canon.listEvents();
  for(const oldEvent of events){const expected=oldEvent.id===event.id?{...oldEvent,readerSummary:correctedSummary}:oldEvent;if(contentHash(current.find(e=>e.id===oldEvent.id))!==contentHash(expected))throw Error("Unreviewed event change");}
  event=current.find(e=>e.id===event.id)!;

  await writeKnowledgeRepairPlan(root,{version:1,sourceId:state.sourceId,batchId,predecessorBatchId:oldBatch,predecessorFingerprint:old.fingerprint,reviewRef:reviewPath,events:[event],quotationIds:[quoteId]});
  const prompt=await buildKnowledgeRepairPrompt(root,state.sourceId,batchId);if(!prompt.includes(quoteId))throw Error("Scoped quotation missing from prompt.");
  let gateRetained=false;try{await assertReconciliationDeferralsReviewed(root,state.sourceId);}catch(e){if(String(e).includes("host source review"))gateRetained=true;else throw e;}if(!gateRetained)throw Error("Original deferral gate disappeared.");
  const diagnostic=`Knowledge acquisition remains unresolved for ${event.id}; predecessor=${old.fingerprint}. Host source review required; do not retry unchanged.`;
  state.knowledgeRepairHistory=[...(state.knowledgeRepairHistory??[]),state.knowledgeRepair];
  state.knowledgeRepair={batchId,pending:true,reviewPath};
  state.appliedRepairHistory=[...(state.appliedRepairHistory??[]),state.appliedRepair];
  state.appliedRepair={repairId:"funding-answer-summary-and-knowledge-v1",failureFingerprint:compilerFailureFingerprint(diagnostic),reviewPath,appliedAt:new Date().toISOString(),fingerprintBasis:"Original deferred event knowledge gap, not aggregate percentages"};
  await fs.writeFile(new URL("state.tmp.json",dir),JSON.stringify(state,null,2));await fs.rename(new URL("state.tmp.json",dir),new URL("state.json",dir));
  console.log(JSON.stringify({ready:true,target:event.id,quotationId:quoteId,observationReceipt:receipt.fingerprint,gateRetained,namespaceUnchanged:true}));
});
