import fs from 'node:fs/promises';
import { ProposalStore } from '../../src/world/canonical-model.js';
import { contentHash } from '../../src/world/canonical.js';
import { WorkspaceStore } from '../../src/storage/workspace-store.js';
import { SourceMaterialStore } from '../../src/storage/source-material-store.js';
import { SourceAnnotationStore, quotationSchema } from '../../src/compiler/annotations.js';
import { evidenceAssertionSchema } from '../../src/world/model.js';
import { CompilerProposalObligations } from '../../src/compiler/proposal-obligations.js';
import { CompilerFinishReceipts } from '../../src/compiler/finish-receipts.js';
import { CompilerCommitService } from '../../src/compiler/validator.js';
import { createCompilerProposalToolset } from '../../src/compiler/proposal-tools.js';
import { readKnowledgeRepairPlan } from '../../src/compiler/knowledge-repair.js';
import { validateAttributionProposalTrace } from '../../src/compiler/attribution-trace.js';
import { withWorkspaceOperationLock } from '../../src/util/workspace-lock.js';
const root=process.cwd(),dir=new URL('./',import.meta.url);
await withWorkspaceOperationLock(root,'compiler',async()=>{
 const state=JSON.parse(await fs.readFile(new URL('state.json',dir),'utf8'));
 if(state.attempt!==28||state.status!=='needs-review'||state.failureFingerprint!=='626922bbf53ef32aef6f793771ac4a0340ff4144d094e0cd92718fc1dca9ff80')throw Error('Incident changed');
 if([state.appliedRepair,...state.appliedRepairHistory].some(r=>r.failureFingerprint===state.failureFingerprint))throw Error('Already repaired fingerprint; stop');
 const sid=state.sourceId,batch=state.knowledgeRepair.batchId,store=new ProposalStore(root),journal=new CompilerProposalObligations(root,sid,batch);
 journal.assertFinishable();
 const plan=await readKnowledgeRepairPlan(root,sid,batch);if(!plan||plan.events[0]?.id!=='event-lumingfei-emergency-signal-00021')throw Error('Scope changed');
 const receipts=new CompilerFinishReceipts(root,sid,batch);if(await receipts.read())throw Error('Existing finish must be preserved');
 const pending=await Promise.all((await store.list('pending',sid)).map(p=>store.readEnvelope('pending',p.id)));
 if(pending.length!==4||pending.some(p=>(p.generatedBy as {compilerBatchId:string}).compilerBatchId!==batch))throw Error('Draft inventory changed');
 const doc=await WorkspaceStore.openReadOnly(root).getSource(sid);if(!doc)throw Error('Missing source');const bytes=await new SourceMaterialStore().read(doc);if(!bytes)throw Error('Missing immutable bytes');
 const quote=quotationSchema.parse(await new SourceAnnotationStore(root).read(sid,'q-lumingfei-emergency-map-00021'));
 const exact=bytes.subarray(quote.anchor.startByte,quote.anchor.endByte).toString('utf8');
 if(exact!=='芬格尔！快把以前那份地图调出来！找出现在的位置！我们迷路了，在龙王家里迷路了！')throw Error('Quotation changed');
 const lines=bytes.toString('utf8').split('\n');if(!lines[4459]?.includes('芬格尔在校园新闻网'))throw Error('Listener response changed');
 const issues=await validateAttributionProposalTrace(root,sid,pending.map(p=>String(p.id)),[],[]);
 if(issues.length!==1||!issues[0]!.includes('prop-lumingfei-emergency-report-00021 object evidence is outside'))throw Error(JSON.stringify(issues));
 const prop=pending.find(p=>p.kind==='proposition')!.payload as Record<string,any>,claim=pending.find(p=>p.kind==='claim')!.payload as Record<string,any>;
 if(prop.object.value!=='给我查那张青铜城的地图！'||claim.object!==prop.object.value||prop.relationId!=='requests-map-lookup'||claim.predicate!==prop.relationId)throw Error('Request semantics changed');
 const reviewPath='run-records/2026-09-11-codex-compile-loop/host-review-emergency-trace.json';
 const reason='Original source has two successive map requests from Lumingfei. Pending semantic content requests map lookup, but all dependency selectors quote the earlier request while the attribution cites the later, host-reviewed quotation. The later exact words 快把以前那份地图调出来！找出现在的位置！ support the same request content as a paraphrase; no assertion that both utterances are verbatim identical. Replace only those evidence anchors with the actual cited quotation, including the event acquisition assertion. Preserve all semantic payloads, all assertion targets and strengths, other anchors, original IDs in withdrawn history, original plan/quotation/checkpoints/namespace. Do not claim localization, rescue or attendance. Normal trace and finish validation must pass.';
 await fs.writeFile(new URL('host-review-emergency-trace.json',dir),JSON.stringify({reviewedAt:new Date().toISOString(),reason,originalFailure:state.error,priorRepair:state.appliedRepair,pending,plan,quote,exact,sourceLines:lines.slice(4446,4461),issues,tests:'23 focused knowledge, attribution, obligations and finish tests; strict reviewer TypeScript check.'},null,2),{flag:'wx'});
 const tools=createCompilerProposalToolset(root);await tools.beginBatch([],batch,sid);
 const call=(name:string,input:unknown)=>tools.tools.find(t=>t.name===name)!.execute(name,input as never,undefined,undefined,{} as never);
 const successors:string[]=[];
 for(const p of pending){
  const assertions=(p.evidenceAssertions as unknown[]).map(a=>evidenceAssertionSchema.parse(a));let changes=0;
  const selectors=assertions.map(a=>{if(a.anchors.length!==1)throw Error('Multi-anchor requires separate review');const anchor=a.anchors[0]!,old=bytes.subarray(anchor.startByte,anchor.endByte).toString('utf8');
   const replace=old==='给我查那张青铜城的地图！'||old==='他妈的你快点儿！我们在水下要死了！给我查那张青铜城的地图！';if(replace)changes++;
   return {segment_id:'a28585b1cf867f3e3a16-00021-0343cf842992',exact:replace?exact:old,target_path:a.target.jsonPointer,relation:a.relation,strength:a.strength,...(a.interpretation?{interpretation:a.interpretation}:{})};});
  if(!changes)throw Error('No reviewed anchor correction');
  const successor=`${(p.payload as {id:string}).id}-quotation-anchor-host-v1-${batch}`;
  const {evidence:_evidence,...payload}=p.payload as Record<string,unknown>;
  await call('propose_'+String(p.kind).replaceAll('-','_'),{proposal_id:successor,payload,evidence_segment_ids:['a28585b1cf867f3e3a16-00021-0343cf842992'],evidence_selectors:selectors});
  if(contentHash((await store.readEnvelope('pending',successor)).payload)!==contentHash(p.payload))throw Error('Semantic payload changed');
  successors.push(successor);
 }
 if((await validateAttributionProposalTrace(root,sid,successors,[],[])).length)throw Error('Corrected trace failed; stop');
 for(const p of pending)await call('withdraw_compiler_proposal',{proposal_id:p.id,reason:`Host-reviewed quotation anchor correction only; same logical identity retained. Audit ${reviewPath}`});
 const preview=await new CompilerCommitService(root).validatePendingStructure(sid);if(preview.length)throw Error(JSON.stringify(preview));
 await call('finish_compiler_batch',{outcome:'complete',reviewed_segments:[],summary:'Host review aligns map-request evidence with its actual cited quotation, preserving semantic payloads and original draft history.',target_reviews:[{target:'event:event-lumingfei-emergency-signal-00021',disposition:'proposed',evidence_segment_ids:['a28585b1cf867f3e3a16-00021-0343cf842992'],summary:'Fingel hears Lumingfei request map lookup through the connected call; no actual localization or rescue result is asserted.'}]});
 const receipt=await receipts.read();if(receipt?.state!=='completed')throw Error('Finish incomplete');await receipts.verify(receipt);
 for(const p of pending)if(contentHash(await store.readEnvelope('rejected',String(p.id)))!==contentHash(p))throw Error('Original draft changed');
 if(contentHash(await readKnowledgeRepairPlan(root,sid,batch))!==contentHash(plan))throw Error('Plan changed');
 state.appliedRepairHistory.push(state.appliedRepair);state.appliedRepair={repairId:'emergency-request-quotation-anchors-v1',failureFingerprint:state.failureFingerprint,reviewPath,appliedAt:new Date().toISOString()};
 await fs.writeFile(new URL('host-review-emergency-trace-result.json',dir),JSON.stringify({receipt:receipt.fingerprint,successors,semanticPayloadsUnchanged:true,originalDraftsPreserved:true}));
 await fs.writeFile(new URL('state.tmp.json',dir),JSON.stringify(state,null,2));await fs.rename(new URL('state.tmp.json',dir),new URL('state.json',dir));
 console.log(JSON.stringify({ready:true,receipt:receipt.fingerprint}));
});
