import fs from "node:fs/promises";
import { WorkspaceStore } from "../../src/storage/workspace-store.js";
import { SourceMaterialStore } from "../../src/storage/source-material-store.js";
import { CanonicalModelStore } from "../../src/world/canonical-model.js";
import { SourceAnnotationStore } from "../../src/compiler/annotations.js";
import { EntityResolutionStore } from "../../src/compiler/entity-resolution.js";
import { inspectCompilerStatus } from "../../src/compiler/status.js";
import { CompilerFinishReceipts } from "../../src/compiler/finish-receipts.js";
import { createCompilerProposalToolset } from "../../src/compiler/proposal-tools.js";
import { writeKnowledgeRepairPlan, buildKnowledgeRepairPrompt } from "../../src/compiler/knowledge-repair.js";
import { assertReconciliationDeferralsReviewed } from "../../src/compiler/reconciliation-review-ledger.js";
import { validateCommittedAttributionTrace } from "../../src/compiler/attribution-trace.js";
import { contentHash } from "../../src/world/canonical.js";
import { compilerFailureFingerprint } from "../../src/runtime/codex-compile-loop.js";
import { withWorkspaceOperationLock } from "../../src/util/workspace-lock.js";
const root=process.cwd(),dir=new URL("./",import.meta.url);
await withWorkspaceOperationLock(root,"compiler",async()=>{
  const state=JSON.parse(await fs.readFile(new URL("state.json",dir),"utf8"));
  if(state.attempt!==15||state.status!=="needs-review"||state.knowledgeRepair.pending)throw Error("Incident changed.");
  const source=(await inspectCompilerStatus(root,state.sourceId)).sources.find(s=>s.sourceId===state.sourceId)!;
  if(source.sourceIntegrity!=="verified"||source.hasUnresolvedObligations||source.worldProposalInventory.pending)throw Error("Unreviewed source or obligations.");
  const canon=new CanonicalModelStore(root), annotations=new SourceAnnotationStore(root);
  for(const a of await canon.listAttributions())if((await validateCommittedAttributionTrace(root,state.sourceId,a)).length)throw Error("Prior trace repair has not passed.");
  const events=await canon.listEvents(),event=events.find(e=>e.id==="event-eva-warns-thirteen-00015")!;
  if(!event||event.observedKnowledge?.operations.length||event.observedOutcome.operations.length)throw Error("Target changed.");
  const oldBatch=`reconcile-${state.sourceId}-bounded-codex-target-review-v1-20260912-3`;
  const oldStore=new CompilerFinishReceipts(root,state.sourceId,oldBatch),old=await oldStore.read();
  if(old?.state!=="completed")throw Error("Original batch unfinished.");await oldStore.verify(old);
  const report=old.identity.input.target_reviews?.find(r=>r.target===`event:${event.id}`);
  if(report?.disposition!=="capability-gap"||report.summary!=="EVA explicitly identifies 13 as an intruder, cannot alarm because of the preconfigured card, and warns him to leave. The warning creates no compatible existing claim/proposition for a knowledge effect and no registered system-warning state.")throw Error("Original report changed.");
  const doc=await WorkspaceStore.openReadOnly(root).getSource(state.sourceId);if(!doc)throw Error("Missing source.");
  const bytes=await new SourceMaterialStore().read(doc);if(!bytes)throw Error("Missing immutable bytes.");
  const lines=bytes.toString("utf8").split("\n");
  const line=lines.find(l=>l.includes("你违规侵入中央主机控制室"));
  const exact=line?.match(/“([^”]+)”女孩说/u)?.[1];
  if(!exact||!exact.includes("我现在应该报警，但我无法报警")||!exact.endsWith("你的权限要求我把你作为己方来看待。"))throw Error("Original EVA disclosure changed.");
  if(!lines.some(l=>l.includes("既然我有特权卡")))throw Error("Listener context changed.");
  const mapping=(await new EntityResolutionStore(root).list(state.sourceId)).filter(r=>["em-evan","em-13"].includes(r.mentionId));
  if(mapping.some(r=>r.mentionId==="em-evan")||!mapping.some(r=>r.mentionId==="em-13"&&r.entityId==="char-thirteen-00015"))throw Error("Expected missing speaker binding or listener mapping changed.");
  const mention=await annotations.read(state.sourceId,"em-evan");
  if(mention.annotationType!=="entity-mention"||mention.surface!=="EVA"||bytes.subarray(mention.anchor.startByte,mention.anchor.endByte).toString("utf8")!=="EVA")throw Error("Original named mention is not source-grounded.");
  const entity=(await canon.listEntities()).find(e=>e.id==="char-eva-00008");if(!entity||![entity.canonicalName,...entity.aliases].includes("EVA"))throw Error("Canonical identity mismatch.");
  const quoteId="q-eva-access-disclosure-00015",segmentId="a28585b1cf867f3e3a16-00015-c98e6792a5ae";
  const annotationBefore=await annotations.list(state.sourceId);
  if(annotationBefore.some(a=>a.id===quoteId))throw Error("Supplementary quotation already exists; review its original scope.");
  const dependencies={claims:await canon.listClaims(),propositions:await canon.listPropositions(),attributions:await canon.listAttributions()};
  const batchId=`reconcile-${state.sourceId}-knowledge-effects-${state.semanticRunId}-5`,reviewPath="run-records/2026-09-11-codex-compile-loop/host-review-eva-disclosure.json";
  const review={reviewedAt:new Date().toISOString(),sourceId:state.sourceId,batchId,report,originalFinishFingerprint:old.fingerprint,exact,sourceLines:lines.slice(2982,2996),mention,entity,mapping,dependencies,baseline:event,
    finding:"Host reviewed the original deferred report and control-room scene. Adams names EVA immediately before the represented girl addresses 13; the original proper-name mention em-evan is anchored to those exact source bytes but lacks a resolution to the already-established EVA identity. Add only that missing typed binding and the exact direct disclosure. 13 can hear her report about the access-card limitation; this is not a permission/state mutation or proof that he complies. Preserve the existing warning quotation, current physical/represented presence, entry checkpoint and unrelated world content. Other audit defects and original publication deferrals remain.",
    priorKnowledgeRepair:state.knowledgeRepair,priorAppliedRepair:state.appliedRepair,namespaceUnchanged:state.semanticRunId,validation:"Knowledge scope, quotation trace, normal finish and obligation regression tests and type checks passed before application."};
  await fs.writeFile(new URL("host-review-eva-disclosure.json",dir),JSON.stringify(review,null,2),{flag:"wx"});
  const observationBatch=`host-eva-disclosure-${state.sourceId}-v1`,tools=createCompilerProposalToolset(root);
  await tools.beginBatch([],observationBatch,state.sourceId);
  const call=(name:string,input:unknown)=>tools.tools.find(t=>t.name===name)!.execute(name,input as never,undefined,undefined,{} as never);
  await call("propose_entity_resolution",{proposal_id:"resolve-evan-host-v1",resolution_id:"res-evan-host-v1",mention_id:"em-evan",status:"resolved",entity_id:"char-eva-00008",candidates:[{entity_id:"char-eva-00008",confidence:1,basis_mention_ids:["em-evan"],evidence_assertion_ids:[],rationale:"Exact source-grounded EVA name matches the established canonical name; adjacent scene identifies the represented speaker."}],rationale:"Host source review: resolve the original unbound proper-name mention to existing EVA; no new identity."});
  await call("propose_quotation",{proposal_id:"q-eva-disclosure-host-v1",annotation_id:quoteId,selector:{segment_id:segmentId,exact},mode:"direct",speaker_mention_id:"em-evan",addressee_mention_ids:["em-13"],scene_id:"ds-library-entry",attribution_confidence:1});
  await call("finish_compiler_batch",{outcome:"complete",reviewed_segments:[],summary:"Host source review: existing EVA identity and exact addressed disclosure; no permission-state or behavior change inferred."});
  const observationStore=new CompilerFinishReceipts(root,state.sourceId,observationBatch),receipt=await observationStore.read();if(receipt?.state!=="completed")throw Error("Observation finish incomplete.");await observationStore.verify(receipt);
  for(const annotation of annotationBefore)if(contentHash(await annotations.read(state.sourceId,annotation.id))!==contentHash(annotation))throw Error("Existing annotation changed.");
  if(contentHash(await canon.listEvents())!==contentHash(events))throw Error("World events changed during observation.");
  await writeKnowledgeRepairPlan(root,{version:1,sourceId:state.sourceId,batchId,predecessorBatchId:oldBatch,predecessorFingerprint:old.fingerprint,reviewRef:reviewPath,events:[event],quotationIds:[quoteId]});
  const prompt=await buildKnowledgeRepairPrompt(root,state.sourceId,batchId);if(!prompt.includes(quoteId))throw Error("Scoped quotation missing from prompt.");
  let gateRetained=false;try{await assertReconciliationDeferralsReviewed(root,state.sourceId);}catch(e){if(String(e).includes("host source review"))gateRetained=true;else throw e;}if(!gateRetained)throw Error("Original deferral gate disappeared.");
  const diagnostic=`Knowledge acquisition remains unresolved for ${event.id}; predecessor=${old.fingerprint}. Host source review required; do not retry unchanged.`;
  state.knowledgeRepairHistory=[...(state.knowledgeRepairHistory??[]),state.knowledgeRepair];
  state.knowledgeRepair={batchId,pending:true,reviewPath};
  state.appliedRepairHistory=[...(state.appliedRepairHistory??[]),state.appliedRepair];
  state.appliedRepair={repairId:"eva-disclosure-source-grounded-dependencies-v1",failureFingerprint:compilerFailureFingerprint(diagnostic),reviewPath,appliedAt:new Date().toISOString(),fingerprintBasis:"Original deferred event knowledge gap, not aggregate percentages"};
  await fs.writeFile(new URL("state.tmp.json",dir),JSON.stringify(state,null,2));await fs.rename(new URL("state.tmp.json",dir),new URL("state.json",dir));
  console.log(JSON.stringify({ready:true,target:event.id,quotationId:quoteId,observationReceipt:receipt.fingerprint,gateRetained,namespaceUnchanged:true}));
});
