import fs from 'node:fs/promises';
import { CanonicalModelStore } from '../../src/world/canonical-model.js';
import { contentHash } from '../../src/world/canonical.js';
import { WorkspaceStore } from '../../src/storage/workspace-store.js';
import { SourceMaterialStore } from '../../src/storage/source-material-store.js';
import { inspectCompilerStatus } from '../../src/compiler/status.js';
import { CompilerFinishReceipts } from '../../src/compiler/finish-receipts.js';
import { EvidenceAssertionStore } from '../../src/compiler/evidence-assertions.js';
import { createCompilerProposalToolset } from '../../src/compiler/proposal-tools.js';
import { convergeWorldProposals } from '../../src/compiler/converge.js';
import { assertReconciliationDeferralsReviewed } from '../../src/compiler/reconciliation-review-ledger.js';
import { compilerFailureCauseFingerprint } from '../../src/runtime/codex-compile-loop.js';
import { compareStoryTime } from '../../src/world/time.js';
import { withWorkspaceOperationLock } from '../../src/util/workspace-lock.js';
const root=process.cwd(),dir=new URL('./',import.meta.url);
await withWorkspaceOperationLock(root,'compiler',async()=>{
 const state=JSON.parse(await fs.readFile(new URL('state.json',dir),'utf8'));
 if(state.attempt!==44||state.status!=='needs-review'||state.knowledgeRepair.pending)throw Error('Incident changed');
 const status=(await inspectCompilerStatus(root,state.sourceId)).sources[0]!;if(status.sourceIntegrity!=='verified'||status.hasUnresolvedObligations||status.worldProposalInventory.pending)throw Error('Unreviewed obligations');
 const canon=new CanonicalModelStore(root),events=await canon.listEvents();
 const before=events.find(e=>e.id==='event-lumingze-visit-001')!,after=events.find(e=>e.id==='event-rescue-briefing-001')!;
 if(before?.storyTime.kind!=='ordinal'||before.storyTime.orderHint!==30||after?.storyTime.kind!=='ordinal'||after.storyTime.orderHint!==31)throw Error('Reference anchors changed');
 if(events.some(e=>e.storyTime.kind==='ordinal'&&e.storyTime.orderHint!==undefined&&e.storyTime.orderHint>30&&e.storyTime.orderHint<31))throw Error('Intermediate index occupied; review before ordering');
 const ids=['event-academy-emergency-alarm-001','event-library-gathering-001'];
 const originals=ids.map(id=>events.find(e=>e.id===id)!);
 if(originals.some(e=>!e||e.storyTime.kind!=='ordinal'||e.storyTime.orderHint!==undefined))throw Error('Targets changed');
 const source=await WorkspaceStore.openReadOnly(root).getSource(state.sourceId);if(!source)throw Error('Source missing');const bytes=await new SourceMaterialStore().read(source);if(!bytes)throw Error('Source bytes missing');const lines=bytes.toString('utf8').split('\n');
 const departure=lines[1978]!.trim(),gather=lines[1993]!.trim(),count=lines[1996]!.trim(),start=lines[1997]!.trim();
 if(!departure.includes('男孩像是来串门的同学那样')||!departure.includes('门外传来了刺耳的蜂鸣声')||gather!=='一群人冲进图书馆，进入总控制室。'||!count.includes('人都到了')||!start.startsWith('“立刻开始。”施耐德教授'))throw Error('Source continuity changed');
 const reports=[];
 for(const n of [2,3]){const batch=`reconcile-${state.sourceId}-bounded-codex-target-review-v1-20260912-${n}`,store=new CompilerFinishReceipts(root,state.sourceId,batch),receipt=await store.read();if(receipt?.state!=='completed')throw Error('Original report missing');await store.verify(receipt);reports.push({batch,receipt,targets:receipt.identity.input.target_reviews?.filter(r=>ids.some(id=>r.target===`event:${id}`))});}
 const next=originals.map((event,i)=>({...event,storyTime:{...event.storyTime,orderHint:30+(i+1)/3}}));
 if(compareStoryTime(before.storyTime,next[0]!.storyTime)!==-1||compareStoryTime(next[0]!.storyTime,next[1]!.storyTime)!==-1||compareStoryTime(next[1]!.storyTime,after.storyTime)!==-1)throw Error('Invalid bracket');
 const batch=`host-alarm-gather-time-${state.sourceId}-v1`,reviewPath='run-records/2026-09-11-codex-compile-loop/host-review-alarm-gather-time.json';
 await fs.writeFile(new URL('host-review-alarm-gather-time.json',dir),JSON.stringify({reviewedAt:new Date().toISOString(),priorState:state,reports,before,after,originals,next,sourceLines:lines.slice(1973,2000),reason:'Exact continuous source chronology is visitor departure then alarm, Nono takes Lumingfei to the library, assembly completed, then Schneider starts the briefing. Existing comparable anchors 30 and 31 bound this entire sequence. Insert two ordinal positions within that existing interval, not a date, duration or claim that mere discourse order always means world time. Preserve labels, all other event fields, original reports, receipts, checkpoints, obligations and unrelated ordering. Host reviewed the earlier no-global-date report: no date is inferred here. Adams necessary-fragment repair has persisted and is not a repeated failure.',validation:'Story-time, relation, compiler finish, obligation and loop regressions plus strict reviewer type check.'},null,2),{flag:'wx'});
 const tools=createCompilerProposalToolset(root);await tools.beginBatch([],batch,state.sourceId);const call=(name:string,input:unknown)=>tools.tools.find(t=>t.name===name)!.execute(name,input as never,undefined,undefined,{} as never);
 const segment='a28585b1cf867f3e3a16-00011-80174f0bd7d3';
 for(const event of next){
  const assertions=await new EvidenceAssertionStore(root).listForArtifact('canonical-event',event.id);
  const selectors=assertions.flatMap(a=>a.anchors.map(anchor=>({segment_id:segment,exact:bytes.subarray(anchor.startByte,anchor.endByte).toString('utf8'),target_path:a.target.jsonPointer,relation:a.relation,strength:a.strength,...(a.interpretation?{interpretation:a.interpretation}:{})})));
  for(const exact of [departure,gather,count,start])selectors.push({segment_id:segment,exact,target_path:'/storyTime',relation:'supports',strength:'explicit'});
  const {evidence,...payload}=event;await call('propose_canonical_event',{proposal_id:`${event.id}-host-time-bracket-v1`,payload,evidence_segment_ids:[segment],evidence_selectors:selectors});
 }
 await call('finish_compiler_batch',{outcome:'complete',reviewed_segments:[],summary:'Host source review positions alarm and assembly within their existing visitor-to-briefing ordinal interval, without changing dates, other event fields or original obligations.'});
 const receipts=new CompilerFinishReceipts(root,state.sourceId,batch),receipt=await receipts.read();if(receipt?.state!=='completed')throw Error('Finish incomplete');await receipts.verify(receipt);
 const result=await convergeWorldProposals(root,state.sourceId);if(result.canonical.blocked.length||result.possibilities.blocked.length)throw Error(JSON.stringify(result));
 const current=await canon.listEvents();for(const event of events)if(contentHash(current.find(e=>e.id===event.id))!==contentHash(next.find(e=>e.id===event.id)??event))throw Error('Unexpected event change');
 for(const record of reports)await new CompilerFinishReceipts(root,state.sourceId,record.batch).verify(record.receipt);
 let gate=false;try{await assertReconciliationDeferralsReviewed(root,state.sourceId);}catch(e){if(String(e).includes('host source review'))gate=true;else throw e;}if(!gate)throw Error('Review gate lost');
 state.appliedRepairHistory.push(state.appliedRepair);state.appliedRepair={repairId:'alarm-gather-source-bounded-order-v1',failureFingerprint:compilerFailureCauseFingerprint({category:'missing-source-bounded-time-order',targetIds:ids,dependencyIds:[before.id,after.id]}),reviewPath,appliedAt:new Date().toISOString()};
 await fs.writeFile(new URL('host-review-alarm-gather-time-result.json',dir),JSON.stringify({receipt:receipt.fingerprint,gateRetained:gate,onlyStoryTimeChanged:true}));
 await fs.writeFile(new URL('state.tmp.json',dir),JSON.stringify(state,null,2));await fs.rename(new URL('state.tmp.json',dir),new URL('state.json',dir));console.log(JSON.stringify({ready:true,gateRetained:gate,receipt:receipt.fingerprint}));
});
