import fs from 'node:fs/promises';
import { CanonicalModelStore } from '../../src/world/canonical-model.js';
import { contentHash } from '../../src/world/canonical.js';
import { WorkspaceStore } from '../../src/storage/workspace-store.js';
import { SourceMaterialStore } from '../../src/storage/source-material-store.js';
import { inspectCompilerStatus } from '../../src/compiler/status.js';
import { CompilerFinishReceipts } from '../../src/compiler/finish-receipts.js';
import { EvidenceAssertionStore } from '../../src/compiler/evidence-assertions.js';
import { createCompilerProposalToolset } from '../../src/compiler/proposal-tools.js';
import { convergeWorldProposals } from '../../src/compiler/converge.js';
import { assertReconciliationDeferralsReviewed } from '../../src/compiler/reconciliation-review-ledger.js';
import { compilerFailureCauseFingerprint } from '../../src/runtime/codex-compile-loop.js';
import { compareStoryTime } from '../../src/world/time.js';
import { withWorkspaceOperationLock } from '../../src/util/workspace-lock.js';
const root=process.cwd(),dir=new URL('./',import.meta.url);
await withWorkspaceOperationLock(root,'compiler',async()=>{
 const state=JSON.parse(await fs.readFile(new URL('state.json',dir),'utf8'));
 if(state.attempt!==45||state.status!=='needs-review'||state.knowledgeRepair.pending)throw Error('Incident changed');
 const status=(await inspectCompilerStatus(root,state.sourceId)).sources[0]!;if(status.sourceIntegrity!=='verified'||status.hasUnresolvedObligations||status.worldProposalInventory.pending)throw Error('Unreviewed obligations');
 const canon=new CanonicalModelStore(root),events=await canon.listEvents();
 const before=events.find(e=>e.id==='event-gear-jam-001')!,after=events.find(e=>e.id==='event-nono-pull-001')!;
 if(before?.storyTime.kind!=='ordinal'||before.storyTime.orderHint!==41||after?.storyTime.kind!=='ordinal'||after.storyTime.orderHint!==49)throw Error('Reference anchors changed');
 if(events.some(e=>e.storyTime.kind==='ordinal'&&e.storyTime.orderHint!==undefined&&e.storyTime.orderHint>41&&e.storyTime.orderHint<49))throw Error('Intermediate index occupied; review before ordering');
 const ids=['event-email-open-001','event-nono-appears-001'];
 const originals=ids.map(id=>events.find(e=>e.id===id)!);
 if(originals.some(e=>!e||e.storyTime.kind!=='ordinal'||e.storyTime.orderHint!==undefined))throw Error('Targets changed');
 const source=await WorkspaceStore.openReadOnly(root).getSource(state.sourceId);if(!source)throw Error('Source missing');const bytes=await new SourceMaterialStore().read(source);if(!bytes)throw Error('Source bytes missing');const lines=bytes.toString('utf8').split('\n');
 const departure=lines[2380]!.trim(),gather=lines[2382]!.trim(),count=lines[2405]!.trim(),start=lines[2407]!.trim();
 if(!departure.includes('路明非打开那封新邮件')||!gather.startsWith('明晚在安珀馆举行晚宴')||count!=='诺诺不知什么时候站到了他们身后。'||!start.includes('扯着他们直奔安珀馆的门口而去'))throw Error('Source continuity changed');
 const reports=[];
 for(const n of [3]){const batch=`reconcile-${state.sourceId}-bounded-codex-target-review-v1-20260912-${n}`,store=new CompilerFinishReceipts(root,state.sourceId,batch),receipt=await store.read();if(receipt?.state!=='completed')throw Error('Original report missing');await store.verify(receipt);reports.push({batch,receipt,targets:receipt.identity.input.target_reviews?.filter(r=>ids.some(id=>r.target===`event:${id}`))});}
 const next=originals.map((event,i)=>({...event,storyTime:{...event.storyTime,orderHint:48+i/2}}));
 if(compareStoryTime(before.storyTime,next[0]!.storyTime)!==-1||compareStoryTime(next[0]!.storyTime,next[1]!.storyTime)!==-1||compareStoryTime(next[1]!.storyTime,after.storyTime)!==-1)throw Error('Invalid bracket');
 const batch=`host-amber-arrival-time-${state.sourceId}-v1`,reviewPath='run-records/2026-09-11-codex-compile-loop/host-review-amber-arrival-time.json';
 await fs.writeFile(new URL('host-review-amber-arrival-time.json',dir),JSON.stringify({reviewedAt:new Date().toISOString(),priorState:state,reports,before,after,originals,next,sourceLines:lines.slice(2372,2409),reason:'Host independently reviewed immutable source: the dorm conversation explicitly discusses the already completed map decoding rescue, then a new email invites Lumingfei for tomorrow evening. The next scene is that Amber Hall evening: Nono appears behind the two students, then immediately takes them to the entrance (existing order 49). Positions 48 and 48.5 encode this source-supported relative order after the earlier rescue and before 49; they are neither dates nor durations. The earlier deferred reports concern missing knowledge/presence fields, not proof that relative chronology is absent. Preserve all existing labels, fields, source-wide deferred reports, plans, namespaces and publication gates. The alarm/gathering fix from attempt 44 is verified separately before application; attempt 45 is remaining audit work rather than that repair recurring.',validation:'Story-time, relation, compiler finish, obligation and loop regressions plus strict reviewer type check.'},null,2),{flag:'wx'});
 const tools=createCompilerProposalToolset(root);await tools.beginBatch([],batch,state.sourceId);const call=(name:string,input:unknown)=>tools.tools.find(t=>t.name===name)!.execute(name,input as never,undefined,undefined,{} as never);
 const segment='a28585b1cf867f3e3a16-00013-2df5b1eb46fa';
 for(const event of next){
  const assertions=await new EvidenceAssertionStore(root).listForArtifact('canonical-event',event.id);
  const selectors=assertions.flatMap(a=>a.anchors.map(anchor=>({segment_id:segment,exact:bytes.subarray(anchor.startByte,anchor.endByte).toString('utf8'),target_path:a.target.jsonPointer,relation:a.relation,strength:a.strength,...(a.interpretation?{interpretation:a.interpretation}:{})})));
  for(const exact of [departure,gather,count,start])selectors.push({segment_id:segment,exact,target_path:'/storyTime',relation:'supports',strength:'explicit'});
  const {evidence,...payload}=event;await call('propose_canonical_event',{proposal_id:`${event.id}-host-amber-time-bracket-v1`,payload,evidence_segment_ids:[segment],evidence_selectors:selectors});
 }
 await call('finish_compiler_batch',{outcome:'complete',reviewed_segments:[],summary:'Host source review orders the invitation email on the prior evening and Nono appearing immediately before the existing Amber Hall entrance event; preserve all other fields and original obligations.'});
 const receipts=new CompilerFinishReceipts(root,state.sourceId,batch),receipt=await receipts.read();if(receipt?.state!=='completed')throw Error('Finish incomplete');await receipts.verify(receipt);
 const result=await convergeWorldProposals(root,state.sourceId);if(result.canonical.blocked.length||result.possibilities.blocked.length)throw Error(JSON.stringify(result));
 const current=await canon.listEvents();for(const event of events)if(contentHash(current.find(e=>e.id===event.id))!==contentHash(next.find(e=>e.id===event.id)??event))throw Error('Unexpected event change');
 for(const record of reports)await new CompilerFinishReceipts(root,state.sourceId,record.batch).verify(record.receipt);
 let gate=false;try{await assertReconciliationDeferralsReviewed(root,state.sourceId);}catch(e){if(String(e).includes('host source review'))gate=true;else throw e;}if(!gate)throw Error('Review gate lost');
 state.appliedRepairHistory.push(state.appliedRepair);state.appliedRepair={repairId:'amber-arrival-source-bounded-order-v1',failureFingerprint:compilerFailureCauseFingerprint({category:'missing-source-bounded-time-order',targetIds:ids,dependencyIds:[before.id,after.id]}),reviewPath,appliedAt:new Date().toISOString()};
 await fs.writeFile(new URL('host-review-amber-arrival-time-result.json',dir),JSON.stringify({receipt:receipt.fingerprint,gateRetained:gate,onlyStoryTimeChanged:true}));
 await fs.writeFile(new URL('state.tmp.json',dir),JSON.stringify(state,null,2));await fs.rename(new URL('state.tmp.json',dir),new URL('state.json',dir));console.log(JSON.stringify({ready:true,gateRetained:gate,receipt:receipt.fingerprint}));
});
