import fs from "node:fs/promises";
import { WorkspaceStore } from "../../src/storage/workspace-store.js";
import { SourceMaterialStore } from "../../src/storage/source-material-store.js";
import { CanonicalModelStore } from "../../src/world/canonical-model.js";
import { SourceAnnotationStore } from "../../src/compiler/annotations.js";
import { EntityResolutionStore } from "../../src/compiler/entity-resolution.js";
import { inspectCompilerStatus } from "../../src/compiler/status.js";
import { CompilerFinishReceipts } from "../../src/compiler/finish-receipts.js";
import { createCompilerProposalToolset } from "../../src/compiler/proposal-tools.js";
import { writeKnowledgeRepairPlan, buildKnowledgeRepairPrompt } from "../../src/compiler/knowledge-repair.js";
import { assertReconciliationDeferralsReviewed } from "../../src/compiler/reconciliation-review-ledger.js";
import { validateCommittedAttributionTrace } from "../../src/compiler/attribution-trace.js";
import { contentHash } from "../../src/world/canonical.js";
import { compilerFailureFingerprint } from "../../src/runtime/codex-compile-loop.js";
import { withWorkspaceOperationLock } from "../../src/util/workspace-lock.js";
const root=process.cwd(),dir=new URL("./",import.meta.url);
await withWorkspaceOperationLock(root,"compiler",async()=>{
  const state=JSON.parse(await fs.readFile(new URL("state.json",dir),"utf8"));
  if(state.attempt!==19||state.status!=="needs-review"||state.knowledgeRepair.pending)throw Error("Incident changed.");
  const source=(await inspectCompilerStatus(root,state.sourceId)).sources.find(s=>s.sourceId===state.sourceId)!;
  if(source.sourceIntegrity!=="verified"||source.hasUnresolvedObligations||source.worldProposalInventory.pending)throw Error("Unreviewed source or obligations.");
  const canon=new CanonicalModelStore(root), annotations=new SourceAnnotationStore(root);
  for(const a of await canon.listAttributions())if((await validateCommittedAttributionTrace(root,state.sourceId,a)).length)throw Error("Prior trace repair has not passed.");
  const events=await canon.listEvents(),event=events.find(e=>e.id==="event-zhao-confession-00004")!;
  if(!event||event.observedKnowledge?.operations.length||event.observedOutcome.operations.length)throw Error("Target changed.");
  const oldBatch=`reconcile-${state.sourceId}-bounded-codex-target-review-v1-20260912-1`;
  const oldStore=new CompilerFinishReceipts(root,state.sourceId,oldBatch),old=await oldStore.read();
  if(old?.state!=="completed")throw Error("Original batch unfinished.");await oldStore.verify(old);
  const report=old.identity.input.target_reviews?.find(r=>r.target===`event:${event.id}`);
  if(report?.disposition!=="unsupported"||report.summary!=="The public confession is explicit, but the available state contract has no supported field for the social utterance; requested entry checkpoints would require unsupported prior state or knowledge.")throw Error("Original report changed.");
  const doc=await WorkspaceStore.openReadOnly(root).getSource(state.sourceId);if(!doc)throw Error("Missing source.");
  const bytes=await new SourceMaterialStore().read(doc);if(!bytes)throw Error("Missing immutable bytes.");
  const lines=bytes.toString("utf8").split("\n");
  const line=lines[679]!;
  const exact=line.match(/赵孟华大声说，“([^”]+)”/u)?.[1];
  if(!exact||!exact.startsWith("我们马上要分开了，我不想后悔，我想跟陈雯雯说")||!exact.endsWith("那不衰到家了么？"))throw Error("Original confession changed.");
  const mapping=(await new EntityResolutionStore(root).list(state.sourceId)).filter(r=>["mention-zhaomenghua","mention-chenwenwen"].includes(r.mentionId));
  if(!mapping.some(r=>r.mentionId==="mention-zhaomenghua"&&r.entityId==="char-zhaomenghua")||!mapping.some(r=>r.mentionId==="mention-chenwenwen"&&r.entityId==="char-chendouwen"))throw Error("Speaker/addressee mapping changed.");
  const quoteId="quotation-zhao-confess",segmentId="a28585b1cf867f3e3a16-00004-f50b153c1580";
  const annotationBefore=await annotations.list(state.sourceId),original=await annotations.read(state.sourceId,quoteId);
  if(original.annotationType!=="quotation"||bytes.subarray(original.anchor.startByte,original.anchor.endByte).toString("utf8")!=="我们马上要分开了，我不想后悔，我想跟陈雯雯说")throw Error("Original truncated quotation changed.");
  const dependencies={claims:await canon.listClaims(),propositions:await canon.listPropositions(),attributions:await canon.listAttributions()};
  const batchId=`reconcile-${state.sourceId}-knowledge-effects-${state.semanticRunId}-8`,reviewPath="run-records/2026-09-11-codex-compile-loop/host-review-confession-knowledge.json";
  const review={reviewedAt:new Date().toISOString(),sourceId:state.sourceId,batchId,report,originalFinishFingerprint:old.fingerprint,exact,sourceLines:lines.slice(672,686),mapping,dependencies,baseline:event,
    finding:"Host reviewed the original unsupported report and cinema scene. The existing quotation is truncated before the actual disclosure. Correct the same logical quotation to the full uninterrupted speech, preserving its speaker, addressee and original history. Chen hears Zhao publicly express liking her for three years; no numeric relationship, accepted relationship, reciprocal affection or later response follows automatically. Limit the supplementary knowledge to hearing this addressed report; every entry checkpoint and original publication deferral remains.",original,
    priorKnowledgeRepair:state.knowledgeRepair,priorAppliedRepair:state.appliedRepair,namespaceUnchanged:state.semanticRunId,validation:"Knowledge scope, quotation trace, normal finish and obligation regression tests and type checks passed before application."};
  await fs.writeFile(new URL("host-review-confession-knowledge.json",dir),JSON.stringify(review,null,2),{flag:"wx"});
  const observationBatch=`host-confession-quotation-${state.sourceId}-v1`,tools=createCompilerProposalToolset(root);
  await tools.beginBatch([],observationBatch,state.sourceId);
  const call=(name:string,input:unknown)=>tools.tools.find(t=>t.name===name)!.execute(name,input as never,undefined,undefined,{} as never);
  await call("propose_quotation",{proposal_id:"q-zhao-complete-host-v1",annotation_id:quoteId,selector:{segment_id:segmentId,exact},mode:"direct",speaker_mention_id:"mention-zhaomenghua",addressee_mention_ids:["mention-chenwenwen"],scene_id:"ds-cinema-event",attribution_confidence:1});
  await call("finish_compiler_batch",{outcome:"complete",reviewed_segments:[],summary:"Host source review restores the full interrupted-by-truncation direct speech under the same quotation ID; retain speaker and listener."});
  const observationStore=new CompilerFinishReceipts(root,state.sourceId,observationBatch),receipt=await observationStore.read();if(receipt?.state!=="completed")throw Error("Observation finish incomplete.");await observationStore.verify(receipt);
  for(const annotation of annotationBefore.filter(a=>a.id!==quoteId))if(contentHash(await annotations.read(state.sourceId,annotation.id))!==contentHash(annotation))throw Error("Existing annotation changed.");
  const corrected=await annotations.read(state.sourceId,quoteId);
  if(corrected.annotationType!=="quotation"||corrected.speakerMentionId!==original.speakerMentionId||contentHash(corrected.addresseeMentionIds)!==contentHash(original.addresseeMentionIds)||corrected.sceneId!==original.sceneId||bytes.subarray(corrected.anchor.startByte,corrected.anchor.endByte).toString("utf8")!==exact)throw Error("Corrected quotation identity or source differs.");
  for(const attribution of await canon.listAttributions())if((await validateCommittedAttributionTrace(root,state.sourceId,attribution)).length)throw Error("Quotation revision broke committed trace.");
  if(contentHash(await canon.listEvents())!==contentHash(events))throw Error("World events changed during observation.");
  await writeKnowledgeRepairPlan(root,{version:1,sourceId:state.sourceId,batchId,predecessorBatchId:oldBatch,predecessorFingerprint:old.fingerprint,reviewRef:reviewPath,events:[event],quotationIds:[quoteId]});
  const prompt=await buildKnowledgeRepairPrompt(root,state.sourceId,batchId);if(!prompt.includes(quoteId))throw Error("Scoped quotation missing from prompt.");
  let gateRetained=false;try{await assertReconciliationDeferralsReviewed(root,state.sourceId);}catch(e){if(String(e).includes("host source review"))gateRetained=true;else throw e;}if(!gateRetained)throw Error("Original deferral gate disappeared.");
  const diagnostic=`Knowledge acquisition remains unresolved for ${event.id}; predecessor=${old.fingerprint}. Host source review required; do not retry unchanged.`;
  state.knowledgeRepairHistory=[...(state.knowledgeRepairHistory??[]),state.knowledgeRepair];
  state.knowledgeRepair={batchId,pending:true,reviewPath};
  state.appliedRepairHistory=[...(state.appliedRepairHistory??[]),state.appliedRepair];
  state.appliedRepair={repairId:"confession-quotation-and-knowledge-dependencies-v1",failureFingerprint:compilerFailureFingerprint(diagnostic),reviewPath,appliedAt:new Date().toISOString(),fingerprintBasis:"Original deferred event knowledge gap, not aggregate percentages"};
  await fs.writeFile(new URL("state.tmp.json",dir),JSON.stringify(state,null,2));await fs.rename(new URL("state.tmp.json",dir),new URL("state.json",dir));
  console.log(JSON.stringify({ready:true,target:event.id,quotationId:quoteId,observationReceipt:receipt.fingerprint,gateRetained,namespaceUnchanged:true}));
});
