import fs from 'node:fs/promises';
import { CanonicalModelStore } from '../../src/world/canonical-model.js';
import { characterEntryCheckpointSchema } from '../../src/world/model.js';
import { worldStorageRoot } from '../../src/world/paths.js';
import { contentHash } from '../../src/world/canonical.js';
import { WorkspaceStore } from '../../src/storage/workspace-store.js';
import { SourceMaterialStore } from '../../src/storage/source-material-store.js';
import { inspectCompilerStatus } from '../../src/compiler/status.js';
import { CompilerFinishReceipts } from '../../src/compiler/finish-receipts.js';
import { EvidenceAssertionStore } from '../../src/compiler/evidence-assertions.js';
import { createCompilerProposalToolset } from '../../src/compiler/proposal-tools.js';
import { convergeWorldProposals } from '../../src/compiler/converge.js';
import { assertReconciliationDeferralsReviewed } from '../../src/compiler/reconciliation-review-ledger.js';
import { compilerFailureCauseFingerprint } from '../../src/runtime/codex-compile-loop.js';
import { withWorkspaceOperationLock } from '../../src/util/workspace-lock.js';
const root=process.cwd(),dir=new URL('./',import.meta.url);
await withWorkspaceOperationLock(root,'compiler',async()=>{
 const state=JSON.parse(await fs.readFile(new URL('state.json',dir),'utf8'));
 if(state.attempt!==55||state.status!=='needs-review'||state.knowledgeRepair.pending)throw Error('Incident changed');
 const status=(await inspectCompilerStatus(root,state.sourceId)).sources[0]!;
 if(status.sourceIntegrity!=='verified'||status.hasUnresolvedObligations||status.worldProposalInventory.pending)throw Error('Unreviewed obligations');
 const canon=new CanonicalModelStore(root),events=await canon.listEvents();
 const event=events.find(e=>e.id==='event-cc1000-arrival-00006');if(!event||event.characterEntryCheckpoints?.length)throw Error('Entry target changed');
 const priorRepair=events.find(e=>e.id==='event-laotang-coaching-00003');if(!priorRepair?.characterEntryCheckpoints?.some(c=>c.actorId==='char-lumingfei'))throw Error('Prior targeted failure recurred; stop');
 const sorted=events.slice().sort((a,b)=>Math.min(...a.evidence.map(r=>r.span.startLine))-Math.min(...b.evidence.map(r=>r.span.startLine))||(a.narrativeContext?.discourseOrder??0)-(b.narrativeContext?.discourseOrder??0)||a.id.localeCompare(b.id));
 for(const actor of ['char-fingel'])if(sorted.find(e=>(!e.narrativeContext||e.narrativeContext.mode==='scene')&&e.participantPresence?.some(p=>p.entityId===actor&&p.mode==='physical'))?.id!==event.id)throw Error('First-entry target changed');
 const originalBatch=`reconcile-${state.sourceId}-bounded-codex-target-review-v1-20260912-1`,predecessor=new CompilerFinishReceipts(root,state.sourceId,originalBatch),old=await predecessor.read();if(old?.state!=='completed')throw Error('Original finish missing');await predecessor.verify(old);
 const reports=old.identity.input.target_reviews?.filter(r=>['event:event-cc1000-arrival-00006'].includes(r.target));if(reports?.length!==1||reports.some(r=>r.disposition!=='unsupported'))throw Error('Original reports changed');
 const ledgerDir=worldStorageRoot(root)+'/compiler/reconciliation-reviews/'+state.sourceId;
 const ledgers=[];for(const file of await fs.readdir(ledgerDir)){const ledger=JSON.parse(await fs.readFile(ledgerDir+'/'+file,'utf8'));const results=ledger.results?.filter((r:{target:string})=>r.target==='event:event-cc1000-arrival-00006');if(results?.length)ledgers.push({file,finishFingerprint:ledger.finishFingerprint,results});}if(!ledgers.length)throw Error('Original target ledger missing');
 const source=await WorkspaceStore.openReadOnly(root).getSource(state.sourceId);if(!source)throw Error('Source missing');const bytes=await new SourceMaterialStore().read(source);if(!bytes)throw Error('Immutable source missing');const lines=bytes.toString('utf8').split('\n');
 const exact=(needle:string)=>{const matches=lines.slice(835,869).filter(l=>l.includes(needle));if(matches.length!==1)throw Error('Anchor not unique');return matches[0]!.trim();};
 const waiting=exact('他和芬格尔在芝加哥火车站度过两个晚上了'),returning=exact('他说对他而言每次返校都是这样的'),hall=exact('候车大厅里只剩下他们俩了');
 const checkpoints=[characterEntryCheckpointSchema.parse({actorId:'char-fingel',readerSetup:'凌晨列车进站之前，芬格尔和路明非仍在芝加哥火车站候车，等候前往卡塞尔学院的CC1000次快车。',actorObservation:'你和路明非已经在车站等了两个晚上，仍等着乘车返校。',participantPresence:[{entityId:'char-fingel',mode:'physical'},{entityId:'char-lumingfei',mode:'physical'}],delta:{version:1,operations:[{op:'set',entityId:'char-fingel',field:'character.plan',value:'等候CC1000次快车，乘车返回卡塞尔学院'}]}})];
 const next={...event,characterEntryCheckpoints:checkpoints};
 const batch=`host-fingel-train-pre-entry-${state.sourceId}-v1`,reviewPath='run-records/2026-09-11-codex-compile-loop/host-review-fingel-train-entry-checkpoint.json';
 await fs.writeFile(new URL('host-review-fingel-train-entry-checkpoint.json',dir),JSON.stringify({reviewedAt:new Date().toISOString(),priorState:state,originalBatch,originalReceipt:old.fingerprint,reports,ledgers,original:event,next,sourceQuotes:{waiting,returning,hall},reason:'Host reviewed the original unsupported arrival report and all target ledgers, including the later accepted observation proposal, against immutable source lines 836-869. Absence of an existing Chicago location entity prevents a location delta but does not negate the explicit prior return-to-school waiting plan. Add only Fingel own waiting/return plan before the train arrives. Preserve the existing arrival observation knowledge as a post-event effect; do not leak arrival, ticket ranks, scanner results or later dialogue into pre-entry knowledge. The conductor appears after arrival and is outside this bounded checkpoint repair. Preserve all existing event fields, accepted knowledge, original reports, receipts and publication gates.',validation:'Character entry, entry-context, compiler finish/obligation and loop regressions plus strict type check and normal schema/evidence/commit verification.'},null,2),{flag:'wx'});
 const toolset=createCompilerProposalToolset(root);await toolset.beginBatch([],batch,state.sourceId);const call=(name:string,input:unknown)=>toolset.tools.find(t=>t.name===name)!.execute(name,input as never,undefined,undefined,{} as never);
 const segment='a28585b1cf867f3e3a16-00006-dfcdc0eeafc7';
 const assertions=await new EvidenceAssertionStore(root).listForArtifact('canonical-event',event.id);
 const selectors=assertions.flatMap(a=>a.anchors.map(anchor=>{
  const exact=bytes.subarray(anchor.startByte,anchor.endByte).toString('utf8'),needle=Buffer.from(exact),hits:number[]=[];
  for(let offset=117806;offset<166800;){const at=bytes.indexOf(needle,offset);if(at<0||at+needle.length>166800)break;hits.push(at);offset=at+1;}
  const occurrence=hits.indexOf(anchor.startByte)+1;if(!occurrence)throw Error('Original evidence outside reviewed segment');
  return {segment_id:segment,exact,...(hits.length>1?{occurrence}:{}),target_path:a.target.jsonPointer,relation:a.relation,strength:a.strength,...(a.interpretation?{interpretation:a.interpretation}:{})};
 }));
 for(let index=0;index<checkpoints.length;index++)for(const field of ['readerSetup','actorObservation','participantPresence','delta'])for(const quote of [waiting,returning,hall])selectors.push({segment_id:segment,exact:quote,target_path:`/characterEntryCheckpoints/${index}/${field}`,relation:'supports',strength:'strong-inference',interpretation:'Pre-arrival return-to-school waiting plan explicitly supported by the two nights in the waiting hall. No later train or ticket knowledge.'});
 const {evidence,...payload}=next;await call('propose_canonical_event',{proposal_id:'event-fingel-train-host-checkpoint-v1',payload,evidence_segment_ids:[segment],evidence_selectors:selectors});
 await call('finish_compiler_batch',{outcome:'complete',reviewed_segments:[],summary:'Source-reviewed pre-arrival waiting plan for Fingel; existing arrival knowledge and all other fields retained.'});
 const receipts=new CompilerFinishReceipts(root,state.sourceId,batch),receipt=await receipts.read();if(receipt?.state!=='completed')throw Error('Finish incomplete');await receipts.verify(receipt);
 const result=await convergeWorldProposals(root,state.sourceId);if(result.canonical.blocked.length||result.possibilities.blocked.length)throw Error(JSON.stringify(result));
 const current=await canon.listEvents();for(const e of events)if(contentHash(current.find(c=>c.id===e.id))!==contentHash(e.id===event.id?next:e))throw Error('Unexpected event change');
 await predecessor.verify(old);
 let gate=false;try{await assertReconciliationDeferralsReviewed(root,state.sourceId);}catch(e){if(String(e).includes('host source review'))gate=true;else throw e;}if(!gate)throw Error('Original review gate lost');
 state.appliedRepairHistory.push(state.appliedRepair);state.appliedRepair={repairId:'fingel-source-reviewed-pre-arrival-checkpoint-v1',failureFingerprint:compilerFailureCauseFingerprint({category:'missing-source-backed-fingel-train-entry',targetIds:['char-fingel'],dependencyIds:[event.id]}),reviewPath,appliedAt:new Date().toISOString()};
 await fs.writeFile(new URL('host-review-fingel-train-entry-checkpoint-result.json',dir),JSON.stringify({receipt:receipt.fingerprint,gateRetained:gate,onlyEntryCheckpointAdded:true}));
 await fs.writeFile(new URL('state.tmp.json',dir),JSON.stringify(state,null,2));await fs.rename(new URL('state.tmp.json',dir),new URL('state.json',dir));console.log(JSON.stringify({ready:true,receipt:receipt.fingerprint,gateRetained:gate}));
});
