import fs from "node:fs/promises";
import { WorkspaceStore } from "../../src/storage/workspace-store.js";
import { SourceMaterialStore } from "../../src/storage/source-material-store.js";
import { CanonicalModelStore } from "../../src/world/canonical-model.js";
import { SourceAnnotationStore } from "../../src/compiler/annotations.js";
import { EntityResolutionStore } from "../../src/compiler/entity-resolution.js";
import { inspectCompilerStatus } from "../../src/compiler/status.js";
import { CompilerFinishReceipts } from "../../src/compiler/finish-receipts.js";
import { createCompilerProposalToolset } from "../../src/compiler/proposal-tools.js";
import { writeKnowledgeRepairPlan, buildKnowledgeRepairPrompt } from "../../src/compiler/knowledge-repair.js";
import { assertReconciliationDeferralsReviewed } from "../../src/compiler/reconciliation-review-ledger.js";
import { validateCommittedAttributionTrace } from "../../src/compiler/attribution-trace.js";
import { contentHash } from "../../src/world/canonical.js";
import { compilerFailureFingerprint } from "../../src/runtime/codex-compile-loop.js";
import { withWorkspaceOperationLock } from "../../src/util/workspace-lock.js";
const root=process.cwd(),dir=new URL("./",import.meta.url);
await withWorkspaceOperationLock(root,"compiler",async()=>{
  const state=JSON.parse(await fs.readFile(new URL("state.json",dir),"utf8"));
  if(state.attempt!==13||state.status!=="needs-review"||state.knowledgeRepair.pending)throw Error("Incident changed.");
  const source=(await inspectCompilerStatus(root,state.sourceId)).sources.find(s=>s.sourceId===state.sourceId)!;
  if(source.sourceIntegrity!=="verified"||source.hasUnresolvedObligations||source.worldProposalInventory.pending)throw Error("Unreviewed source or obligations.");
  const canon=new CanonicalModelStore(root), annotations=new SourceAnnotationStore(root);
  for(const a of await canon.listAttributions())if((await validateCommittedAttributionTrace(root,state.sourceId,a)).length)throw Error("Prior trace repair has not passed.");
  const events=await canon.listEvents(),event=events.find(e=>e.id==="event-medical-reveal-00007")!;
  if(!event||event.observedKnowledge?.operations.length||event.observedOutcome.operations.length)throw Error("Target changed.");
  const oldBatch=`reconcile-${state.sourceId}-bounded-codex-target-review-v1-20260912-2`;
  const oldStore=new CompilerFinishReceipts(root,state.sourceId,oldBatch),old=await oldStore.read();
  if(old?.state!=="completed")throw Error("Original batch unfinished.");await oldStore.verify(old);
  const report=old.identity.input.target_reviews?.find(r=>r.target===`event:${event.id}`);
  if(report?.disposition!=="capability-gap"||report.summary!=="Source explicitly establishes that Frigga bullets do not injure and anesthetize targets, but the catalog has no nonnumeric injury/anesthesia field and no compatible pre-existing claim ID for a knowledge delta. The requested Manshtein entry checkpoint also requires an unavailable complete checkpoint projection seed.")throw Error("Original report changed.");
  const doc=await WorkspaceStore.openReadOnly(root).getSource(state.sourceId);if(!doc)throw Error("Missing source.");
  const bytes=await new SourceMaterialStore().read(doc);if(!bytes)throw Error("Missing immutable bytes.");
  const lines=bytes.toString("utf8").split("\n");
  const line=lines.find(l=>l.includes("这种炼金弹头击中目标时"));
  const exact=line?.match(/“([^”]+)”古德里安教授/u)?.[1];
  if(!exact||!exact.includes("不会伤到人")||!exact.includes("微量的麻醉剂"))throw Error("Original medical explanation changed.");
  if(!lines.some(l=>l.includes("古德里安教授在路明非身边坐下")))throw Error("Listener context changed.");
  const mapping=(await new EntityResolutionStore(root).list(state.sourceId)).filter(r=>["em-gude","em-lumingfei"].includes(r.mentionId));
  if(!mapping.some(r=>r.mentionId==="em-gude"&&r.entityId==="char-gudeli-an")||!mapping.some(r=>r.mentionId==="em-lumingfei"&&r.entityId==="char-lumingfei"))throw Error("Speaker/addressee mapping changed.");
  const quoteId="q-gude-frigga-explanation-00007",segmentId="a28585b1cf867f3e3a16-00007-26df32014434";
  const annotationBefore=await annotations.list(state.sourceId);
  if(annotationBefore.some(a=>a.id===quoteId))throw Error("Supplementary quotation already exists; review its original scope.");
  const dependencies={claims:await canon.listClaims(),propositions:await canon.listPropositions(),attributions:await canon.listAttributions()};
  const batchId=`reconcile-${state.sourceId}-knowledge-effects-${state.semanticRunId}-3`,reviewPath="run-records/2026-09-11-codex-compile-loop/host-review-medical-knowledge.json";
  const review={reviewedAt:new Date().toISOString(),sourceId:state.sourceId,batchId,report,originalFinishFingerprint:old.fingerprint,exact,sourceLines:lines.slice(1135,1148),mapping,dependencies,baseline:event,
    finding:"Host read the original report and source medical explanation with Gudelian sitting beside Lumingfei. The nonnumeric injury/anesthesia state-field gap does not preclude recording what Lumingfei hears. A compatible semantic dependency and quotation are missing. Add the exact existing speech as a typed observation, preserving speaker and addressed listener. Authorize only heard explanation content through the fixed dependency scope; do not invent numeric health, anesthesia state, bullet entities, or assign knowledge to others. The separate Manshtein entry-checkpoint issue remains unresolved and is not certified by this supplement.",
    priorKnowledgeRepair:state.knowledgeRepair,priorAppliedRepair:state.appliedRepair,namespaceUnchanged:state.semanticRunId,validation:"Knowledge scope, quotation trace, normal finish and obligation regression tests and type checks passed before application."};
  await fs.writeFile(new URL("host-review-medical-knowledge.json",dir),JSON.stringify(review,null,2),{flag:"wx"});
  const observationBatch=`host-medical-quotation-${state.sourceId}-v1`,tools=createCompilerProposalToolset(root);
  await tools.beginBatch([],observationBatch,state.sourceId);
  const call=(name:string,input:unknown)=>tools.tools.find(t=>t.name===name)!.execute(name,input as never,undefined,undefined,{} as never);
  await call("propose_quotation",{proposal_id:"q-gude-frigga-host-v1",annotation_id:quoteId,selector:{segment_id:segmentId,exact},mode:"direct",speaker_mention_id:"em-gude",addressee_mention_ids:["em-lumingfei"],scene_id:"ds-battle",attribution_confidence:1});
  await call("finish_compiler_batch",{outcome:"complete",reviewed_segments:[],summary:"Host source review: exact medical explanation and addressed listener; no health score, state change, or initial checkpoint inferred."});
  const observationStore=new CompilerFinishReceipts(root,state.sourceId,observationBatch),receipt=await observationStore.read();if(receipt?.state!=="completed")throw Error("Observation finish incomplete.");await observationStore.verify(receipt);
  for(const annotation of annotationBefore)if(contentHash(await annotations.read(state.sourceId,annotation.id))!==contentHash(annotation))throw Error("Existing annotation changed.");
  if(contentHash(await canon.listEvents())!==contentHash(events))throw Error("World events changed during observation.");
  await writeKnowledgeRepairPlan(root,{version:1,sourceId:state.sourceId,batchId,predecessorBatchId:oldBatch,predecessorFingerprint:old.fingerprint,reviewRef:reviewPath,events:[event],quotationIds:[quoteId]});
  const prompt=await buildKnowledgeRepairPrompt(root,state.sourceId,batchId);if(!prompt.includes(quoteId))throw Error("Scoped quotation missing from prompt.");
  let gateRetained=false;try{await assertReconciliationDeferralsReviewed(root,state.sourceId);}catch(e){if(String(e).includes("host source review"))gateRetained=true;else throw e;}if(!gateRetained)throw Error("Original deferral gate disappeared.");
  const diagnostic=`Knowledge acquisition remains unresolved for ${event.id}; predecessor=${old.fingerprint}. Host source review required; do not retry unchanged.`;
  state.knowledgeRepairHistory=[...(state.knowledgeRepairHistory??[]),state.knowledgeRepair];
  state.knowledgeRepair={batchId,pending:true,reviewPath};
  state.appliedRepairHistory=[...(state.appliedRepairHistory??[]),state.appliedRepair];
  state.appliedRepair={repairId:"medical-source-grounded-knowledge-dependencies-v1",failureFingerprint:compilerFailureFingerprint(diagnostic),reviewPath,appliedAt:new Date().toISOString(),fingerprintBasis:"Original deferred event knowledge gap, not aggregate percentages"};
  await fs.writeFile(new URL("state.tmp.json",dir),JSON.stringify(state,null,2));await fs.rename(new URL("state.tmp.json",dir),new URL("state.json",dir));
  console.log(JSON.stringify({ready:true,target:event.id,quotationId:quoteId,observationReceipt:receipt.fingerprint,gateRetained,namespaceUnchanged:true}));
});
