import fs from 'node:fs/promises';
import { CanonicalModelStore } from '../../src/world/canonical-model.js';
import { characterEntryCheckpointSchema } from '../../src/world/model.js';
import { worldStorageRoot } from '../../src/world/paths.js';
import { contentHash } from '../../src/world/canonical.js';
import { WorkspaceStore } from '../../src/storage/workspace-store.js';
import { SourceMaterialStore } from '../../src/storage/source-material-store.js';
import { inspectCompilerStatus } from '../../src/compiler/status.js';
import { CompilerFinishReceipts } from '../../src/compiler/finish-receipts.js';
import { EvidenceAssertionStore } from '../../src/compiler/evidence-assertions.js';
import { createCompilerProposalToolset } from '../../src/compiler/proposal-tools.js';
import { convergeWorldProposals } from '../../src/compiler/converge.js';
import { assertReconciliationDeferralsReviewed } from '../../src/compiler/reconciliation-review-ledger.js';
import { compilerFailureCauseFingerprint } from '../../src/runtime/codex-compile-loop.js';
import { withWorkspaceOperationLock } from '../../src/util/workspace-lock.js';
const root=process.cwd(),dir=new URL('./',import.meta.url);
import { generateEntityResolutionCandidates, EntityResolutionStore } from '../../src/compiler/entity-resolution.js';
await withWorkspaceOperationLock(root,'compiler',async()=>{
 const state=JSON.parse(await fs.readFile(new URL('state.json',dir),'utf8'));if(state.attempt!==181||state.status!=='needs-review')throw Error('Incident changed');const status=(await inspectCompilerStatus(root,state.sourceId)).sources[0]!;if(status.sourceIntegrity!=='verified'||status.hasUnresolvedObligations||status.worldProposalInventory.pending)throw Error('Unreviewed obligations');
 const canon=new CanonicalModelStore(root),events=await canon.listEvents(),entities=await canon.listEntities(),resolutions=new EntityResolutionStore(root),before=await resolutions.list(state.sourceId);const priorReview=JSON.parse(await fs.readFile(new URL(state.appliedRepair.reviewPath.split('/').at(-1)!,dir),'utf8'));for(const t of priorReview.targets)if(!before.some(r=>r.mentionId===t.mention.id&&r.entityId===t.entity.id&&['resolved','new-entity'].includes(r.status)))throw Error('Previous targeted failure recurred');
 const batch=`host-burning-dragon-constantin-identity-link-${state.sourceId}-v1`,specs=[
 ['em-burning-03','char-constantin','At 3660-3662 the burning figure on the car calls for his brother. The continuous campus attack is filmed and explicitly identified as Constantin at 3707-3709; 3735-3736 confirms the same figure thrown from the car. Link only identity, without committing powers or events.'],
 ['em-dragon-03','char-constantin','At 3691 Mannstein describes the dragon attacking campus in the same continuous incident. The following video identification at 3709 names Constantin; later face recognition and Lao Tang recollection corroborate the identity. Resolve only the contextual referent, not the speakers tentative species, power or capability claims.'],
 ] as const;
 const source=await WorkspaceStore.openReadOnly(root).getSource(state.sourceId);if(!source)throw Error('Source missing');const bytes=await new SourceMaterialStore().read(source);if(!bytes)throw Error('Source missing');const lines=bytes.toString('utf8').split('\n');
 const targets=[];for(const [mentionId,entityId,rationale] of specs){if(before.some(r=>r.mentionId===mentionId))throw Error('Resolution already exists');const discovery=await generateEntityResolutionCandidates(root,state.sourceId,mentionId,batch),mention=discovery.mention,entity=entities.find(e=>e.id===entityId);if(!entity||!mention.kindCandidates.includes(entity.kind)||bytes.subarray(mention.anchor.startByte,mention.anchor.endByte).toString('utf8')!==mention.surface)throw Error('Source/identity mismatch');const context=lines.slice(Math.max(0,mention.anchor.startLine-60),mention.anchor.endLine+18);targets.push({mention,entity,discovery,context,rationale});}
 const expectedLines=[3660,3691];if(targets.some((t,i)=>t.mention.anchor.startLine!==expectedLines[i]))throw Error('Reviewed context moved');
 const legacyOrigins:string[]=[],receipts=[];for(const batchId of new Set(targets.map(t=>t.mention.derivation.compilerBatchId))){if(!batchId)throw Error('Observation origin missing');const store=new CompilerFinishReceipts(root,state.sourceId,batchId),receipt=await store.read();if(!receipt){if(!status.completedBatchIds.includes(batchId))throw Error('Origin neither receipted nor legacy checkpointed');legacyOrigins.push(batchId);continue;}if(receipt.state!=='completed')throw Error('Incomplete observation receipt');await store.verify(receipt);receipts.push({store,receipt});}
 const ledgerDir=worldStorageRoot(root)+'/compiler/reconciliation-reviews/'+state.sourceId,ledgers=[];for(const file of await fs.readdir(ledgerDir)){const l=JSON.parse(await fs.readFile(ledgerDir+'/'+file,'utf8'));const results=l.results?.filter((r:{target:string})=>specs.some(([m,e])=>r.target.includes(m)||r.target==='character:'+e));if(results?.length)ledgers.push({file,results});}
 const reviewPath='run-records/2026-09-11-codex-compile-loop/host-review-burning-dragon-constantin-identity-link.json';await fs.writeFile(new URL('host-review-burning-dragon-constantin-identity-link.json',dir),JSON.stringify({reviewedAt:new Date().toISOString(),priorState:state,targets,supportingContexts:[[3651,3710],[3731,3736],[3847,3855],[3893,3895],[3908,3925]].map(([a,b])=>({startLine:a,endLine:b,lines:lines.slice(a-1,b)})),reviewScope:"Two burning campus dragon references linked to Constantin",ledgers,legacyOrigins,legacyPolicy:'Existing completed observation checkpoints without modern receipts are readable under docs/agent-tool-recovery.md; do not synthesize, replace or certify their missing receipts. All new resolution proposals require a verified completed finish.',originalReceipts:receipts.map(r=>r.receipt),reason:'Reviewed the continuous campus attack and pursuit: the burning figure on the car is the subject of the control-room alarm, phone video and explicit Constantin identification. The escape recollection at 3735-3736 ties that same figure to the car; later pool face recognition and Lao Tang memory corroborate identity. No target-specific reconciliation report was found. Resolve these two references only; do not turn tentative dialogue about rank, metal, fire or instability into active rules, and do not mutate events or character knowledge. All observations, receipts, canonical artifacts, prior resolutions, accounting obligations and checkpoints remain unchanged.'},null,2),{flag:'wx'});
 const toolset=createCompilerProposalToolset(root);await toolset.beginBatch([],batch,state.sourceId);const call=(name:string,input:unknown)=>toolset.tools.find(t=>t.name===name)!.execute(name,input as never,undefined,undefined,{} as never);
 for(const t of targets){const id='res-'+t.mention.id+'-host-v1';await call('propose_entity_resolution',{proposal_id:id,resolution_id:id,mention_id:t.mention.id,status:'resolved',entity_id:t.entity.id,candidates:[{entity_id:t.entity.id,confidence:1,basis_mention_ids:[t.mention.id],evidence_assertion_ids:[],rationale:t.rationale}],rationale:t.rationale});}
 await call('finish_compiler_batch',{outcome:'complete',reviewed_segments:[],summary:'Host source-reviewed two burning campus dragon references to Constantin; identity only, without relationship, knowledge, ability or event mutations. No entity, event, evidence or accounting waiver.'});
 const store=new CompilerFinishReceipts(root,state.sourceId,batch),receipt=await store.read();if(receipt?.state!=='completed')throw Error('Finish incomplete');await store.verify(receipt);const result=await convergeWorldProposals(root,state.sourceId);if(result.canonical.blocked.length||result.possibilities.blocked.length)throw Error(JSON.stringify(result));
 const after=await resolutions.list(state.sourceId);if(after.length!==before.length+specs.length)throw Error('Unexpected resolution count');for(const old of before)if(contentHash(after.find(r=>r.id===old.id))!==contentHash(old))throw Error('Prior resolution changed');for(const t of targets)if(!after.some(r=>r.mentionId===t.mention.id&&r.entityId===t.entity.id&&r.status==='resolved'))throw Error('Resolution missing');if(contentHash(await canon.listEvents())!==contentHash(events)||contentHash(await canon.listEntities())!==contentHash(entities))throw Error('World artifacts changed');for(const r of receipts)await r.store.verify(r.receipt);
 let gate=false;try{await assertReconciliationDeferralsReviewed(root,state.sourceId);}catch(e){if(String(e).includes('host source review'))gate=true;else throw e;}if(!gate)throw Error('Review gate lost');state.appliedRepairHistory.push(state.appliedRepair);state.appliedRepair={repairId:'source-reviewed-burning-dragon-constantin-identity-link-v1',failureFingerprint:compilerFailureCauseFingerprint({category:'missing-context-supported-entity-resolutions',targetIds:specs.map(s=>s[0]),dependencyIds:[...new Set(specs.map(s=>s[1]))]}),reviewPath,appliedAt:new Date().toISOString()};
 await fs.writeFile(new URL('host-review-burning-dragon-constantin-identity-link-result.json',dir),JSON.stringify({receipt:receipt.fingerprint,gateRetained:gate,addedResolutions:specs.length,canonicalArtifactsUnchanged:true}));await fs.writeFile(new URL('state.tmp.json',dir),JSON.stringify(state,null,2));await fs.rename(new URL('state.tmp.json',dir),new URL('state.json',dir));console.log(JSON.stringify({ready:true,receipt:receipt.fingerprint,gateRetained:gate}));
});
