import fs from "node:fs/promises";
import path from "node:path";
import { contentHash } from "../../src/world/canonical.js";
import { worldStorageRoot } from "../../src/world/paths.js";
import { InitialWorldStore } from "../../src/world/initial.js";
import { WorkspaceStore } from "../../src/storage/workspace-store.js";
import { SourceMaterialStore } from "../../src/storage/source-material-store.js";
import { inspectCompilerStatus } from "../../src/compiler/status.js";
import { auditCompiler } from "../../src/compiler/audit.js";
import { CompilerFinishReceipts } from "../../src/compiler/finish-receipts.js";
import { buildWorldReconciliationPrompt } from "../../src/compiler/reconcile-world.js";
import { compilerFailureFingerprint } from "../../src/runtime/codex-compile-loop.js";
import { withWorkspaceOperationLock } from "../../src/util/workspace-lock.js";
const root=process.cwd(), dir=new URL("./",import.meta.url);
await withWorkspaceOperationLock(root,"compiler",async()=>{
  const file=new URL("state.json",dir), state=JSON.parse(await fs.readFile(file,"utf8"));
  if(state.attempt!==8 || state.status!=="needs-review" || state.semanticRunId!=="codex-target-review-v1-20260912")throw Error("Incident changed.");
  const status=await inspectCompilerStatus(root,state.sourceId), source=status.sources.find(s=>s.sourceId===state.sourceId)!;
  if(source.sourceIntegrity!=="verified" || source.hasUnresolvedObligations || source.worldProposalInventory.pending)throw Error("Source or obligations require review first.");
  const initial=await new InitialWorldStore(root).get();
  if(initial?.readerContext?.focalActorId!=="char-opening-man" || !initial.participantPresence?.some(p=>p.entityId==="char-opening-man" && p.mode==="physical"))throw Error("Opening actor changed.");
  const sourceDoc=await WorkspaceStore.openReadOnly(root).getSource(state.sourceId);
  if(!sourceDoc)throw Error("Missing source.");
  const bytes=await new SourceMaterialStore().read(sourceDoc);if(!bytes)throw Error("Missing immutable source bytes.");
  const excerpt="他猛地坐起，在下午的阳光中睁开眼睛，呼吸急促，全身都是冷汗，外面是高架轻轨经过的噪音。";
  if(!bytes.toString("utf8").includes(excerpt))throw Error("Opening evidence changed.");
  const planPath=path.join(worldStorageRoot(root),"compiler","reconciliation",`${state.sourceId}.${contentHash(state.semanticRunId).slice(0,24)}.json`);
  const oldPlanText=await fs.readFile(planPath,"utf8"), oldPlan=JSON.parse(oldPlanText);
  if(oldPlan.actorIds[0]!=="char-lumingfei" || oldPlan.driverActorId)throw Error("Predecessor driver assignment changed.");
  const predecessor=[];let deferred=0;
  for(let i=1;i<=4;i++){
    const batchId=`reconcile-${state.sourceId}-bounded-${state.semanticRunId}-${i}`;
    const store=new CompilerFinishReceipts(root,state.sourceId,batchId), receipt=await store.read();
    if(receipt?.state!=="completed")throw Error("Predecessor is unfinished.");await store.verify(receipt);
    const reports=receipt.identity.input.target_reviews??[];
    deferred+=reports.filter(r=>r.disposition!=="proposed").length;
    predecessor.push({batchId,fingerprint:receipt.fingerprint,reports});
  }
  const driverReport=predecessor[0]!.reports.find(r=>r.target==="character:char-lumingfei");
  if(driverReport?.disposition!=="unsupported")throw Error("Prior driver report changed.");
  const audit=await auditCompiler(root,{sourceId:state.sourceId});
  if(!audit.semanticRepairTargets.characterIds.includes("char-opening-man"))throw Error("Fixed audit still omits opening actor.");
  const nextNamespace="codex-opening-driver-v1-20260912";
  const prompt=await buildWorldReconciliationPrompt(root,state.sourceId,audit,1,{proposalIdSuffixTail:nextNamespace,focus:"opening-driver"});
  const context=JSON.parse(prompt.match(/<reconciliation-context>\n([\s\S]+)\n<\/reconciliation-context>/u)![1]!);
  if(JSON.stringify(context.repairPlan.reviewTargets)!==JSON.stringify(["character:char-opening-man"]) || context.initialWorld || !context.openingDriverContext?.readOnly)throw Error("Supplement is not scoped to the actual opening driver.");
  if(await fs.readFile(planPath,"utf8")!==oldPlanText)throw Error("Predecessor plan was modified.");
  const review={reviewedAt:new Date().toISOString(),sourceId:state.sourceId,reason:"Host verified the deferred opening-driver report against immutable prologue and initial-world physical/focal identity. The prior planner assigned a later protagonist; the corrected audit/planner selects the physical opening focal actor. This authorizes only an evidence-constrained supplementary driver proposal pass, not an invented action or a changed opening checkpoint. All predecessor reports, unresolved semantic findings and durable deferral publication gates remain. No source-wide deferrals were cleared.",excerpt,initialWorldHash:contentHash(initial),predecessorPlanHash:contentHash(oldPlan),predecessor,retainedDeferrals:deferred,successorNamespace:nextNamespace,focus:"opening-driver",expectedTargets:context.repairPlan.reviewTargets,validation:"100 relevant tests and repository/script type checks passed."};
  await fs.writeFile(new URL("host-review-opening-target.json",dir),JSON.stringify(review,null,2));
  await fs.writeFile(new URL("audit-before-opening-target.json",dir),JSON.stringify(audit,null,2));
  state.appliedRepair={repairId:"opening-physical-actor-selection-v1",failureFingerprint:compilerFailureFingerprint(state.error),reviewPath:"run-records/2026-09-11-codex-compile-loop/host-review-opening-target.json",appliedAt:review.reviewedAt};
  state.semanticRunHistory=[...(state.semanticRunHistory??[]),{namespace:state.semanticRunId,reviewPath:state.appliedRepair.reviewPath}];
  state.semanticRunId=nextNamespace;state.reconciliationFocus="opening-driver";
  await fs.writeFile(new URL("state.tmp.json",dir),JSON.stringify(state,null,2));await fs.rename(new URL("state.tmp.json",dir),file);
  console.log(JSON.stringify({ready:true,targets:context.repairPlan.reviewTargets,retainedDeferrals:deferred,originalOpeningUnchanged:true,sourceIntegrity:source.sourceIntegrity}));
});
