import fs from 'node:fs/promises';
import {ProposalStore} from '../../src/world/canonical-model.js';
import {contentHash} from '../../src/world/canonical.js';
import {CompilerProposalObligations} from '../../src/compiler/proposal-obligations.js';
import {CompilerCommitService} from '../../src/compiler/validator.js';
import {CompilerFinishReceipts} from '../../src/compiler/finish-receipts.js';
import {createCompilerProposalToolset} from '../../src/compiler/proposal-tools.js';
import {readKnowledgeRepairPlan} from '../../src/compiler/knowledge-repair.js';
import {SourceAnnotationStore,quotationSchema} from '../../src/compiler/annotations.js';
import {WorkspaceStore} from '../../src/storage/workspace-store.js';
import {SourceMaterialStore} from '../../src/storage/source-material-store.js';
import {evidenceAssertionSchema} from '../../src/world/model.js';
import {validateAttributionProposalTrace} from '../../src/compiler/attribution-trace.js';
import {withWorkspaceOperationLock} from '../../src/util/workspace-lock.js';
const root=process.cwd(),dir=new URL('./',import.meta.url);
await withWorkspaceOperationLock(root,'compiler',async()=>{
 const state=JSON.parse(await fs.readFile(new URL('state.json',dir),'utf8'));
 if(state.attempt!==30||state.status!=='needs-review'||state.failureFingerprint!=='91387cb2707fac261925e5485d1f051fbbee51251a14ed7ce5d3b6d6174934f0')throw Error('Incident changed');
 if([state.appliedRepair,...state.appliedRepairHistory].some(r=>r.failureFingerprint===state.failureFingerprint))throw Error('Targeted repair repeated; stop');
 const sid=state.sourceId,batch=state.knowledgeRepair.batchId,store=new ProposalStore(root),journal=new CompilerProposalObligations(root,sid,batch),validator=new CompilerCommitService(root);
 const plan=await readKnowledgeRepairPlan(root,sid,batch);if(!plan||plan.events[0]?.id!=='event-bronze-city-discovered-00010')throw Error('Scope changed');
 const receipts=new CompilerFinishReceipts(root,sid,batch);if(await receipts.read())throw Error('Existing receipt');
 const pending=await Promise.all((await store.list('pending',sid)).map(p=>store.readEnvelope('pending',p.id)));
 if(pending.length!==4||pending.some(p=>(p.generatedBy as {compilerBatchId:string}).compilerBatchId!==batch))throw Error('Pending scope changed');
 const id=`proposal-prop-mans-exploration-window-00010-${batch}`,obligations=journal.unresolved();
 if(obligations.length!==1||obligations[0]?.proposalId!==id||obligations[0]?.inputHash!=='9a70a75fb2072ddcd2290c87ff6483da8c21b2e286cf16fb50bca8f7144d5f0d')throw Error('Failure changed');
 const original=await store.readEnvelope('rejected',id),rejection=await store.readRejection(id),active=pending.find(p=>p.kind==='proposition')!;
 if(!rejection?.errors.some(e=>e.code==='WITHDRAWN_COMPILER_PROPOSAL')||(active.payload as {id:string}).id!==(original.payload as {id:string}).id)throw Error('Lifecycle history changed');
 const preview=await validator.validatePendingStructure(sid);if(preview.length!==1||preview[0]!.errors.length!==1||preview[0]!.errors[0]!.code!=='KNOWLEDGE_PROJECTION_MISMATCH')throw Error(JSON.stringify(preview));
 const doc=await WorkspaceStore.openReadOnly(root).getSource(sid);if(!doc)throw Error('Missing source');const bytes=await new SourceMaterialStore().read(doc);if(!bytes)throw Error('Missing source bytes');
 const quote=quotationSchema.parse(await new SourceAnnotationStore(root).read(sid,'q-mans-exploration-window-00010'));
 const exact=bytes.subarray(quote.anchor.startByte,quote.anchor.endByte).toString('utf8');
 if(exact!=='好的，我明白了。我会为你们更换新的设备，但是记住，你们的时间只有两个小时，无论是氧气还是电力都只能撑两小时，两小时后长江航道海事局的直升机大概也到了，那时候水下作业将被迫停止。')throw Error('Quotation changed');
 const originalPayload=original.payload as Record<string,any>,claim=pending.find(p=>p.kind==='claim')!.payload as Record<string,any>;
 if(originalPayload.object.value!==claim.object||claim.object!=='叶胜和酒德亚纪的探索时间只有两个小时；氧气和电力只能支撑两小时，之后水下作业将被迫停止。')throw Error('Original projection changed');
 const reason='Host reviewed original source, complete quotation, original withdrawn proposition, its narrowed successor, failed resurrection and current claim. Full original content (two-hour exploration, oxygen/electricity limit and stopping underwater work) is inside the cited speech; quotation punctuation was outside the content anchor. The model unnecessarily shortened the proposition, creating the reproduced claim/proposition object mismatch, then tried reviving a withdrawn ID. That attempted lifecycle operation is invalid and is adjudicated without accepting its new sets-exploration-time-limit semantics. Restore original source-supported proposition payload under a justified successor, correcting only its object anchor to inner quotation content. Preserve original claim, event and attribution, all plan fields and failure history. This records Ye Sheng knowing Mans reported the constraint, not a numeric resource mutation or guaranteed future event.';
 const reviewPath='run-records/2026-09-11-codex-compile-loop/host-review-exploration-projection.json';
 await fs.writeFile(new URL('host-review-exploration-projection.json',dir),JSON.stringify({reviewedAt:new Date().toISOString(),reason,originalFailure:state.error,priorRepair:state.appliedRepair,plan,pending,original,rejection,history:journal.history('propose_proposition',id),preview,quote,exact,sourceLines:bytes.toString('utf8').split('\n').slice(1830,1836),tests:'23 knowledge, attribution, obligations and finish tests; strict reviewer type check.'},null,2),{flag:'wx'});
 const tools=createCompilerProposalToolset(root);await tools.beginBatch([],batch,sid);const call=(name:string,input:unknown)=>tools.tools.find(t=>t.name===name)!.execute(name,input as never,undefined,undefined,{} as never);
 const assertions=(original.evidenceAssertions as unknown[]).map(a=>evidenceAssertionSchema.parse(a));
 const selectors=assertions.map(a=>{if(a.anchors.length!==1)throw Error('Unexpected anchor count');const x=a.anchors[0]!;const old=bytes.subarray(x.startByte,x.endByte).toString('utf8');if(old!==`“${exact}”`)throw Error('Original anchor changed');return {segment_id:'a28585b1cf867f3e3a16-00010-4539f49e0b67',exact:a.target.jsonPointer==='/object/value'?exact:old,target_path:a.target.jsonPointer,relation:a.relation,strength:a.strength};});
 const {evidence:_evidence,...payload}=originalPayload,successor=`prop-mans-window-full-content-host-v1-${batch}`;
 await call('propose_proposition',{proposal_id:successor,payload,evidence_segment_ids:['a28585b1cf867f3e3a16-00010-4539f49e0b67'],evidence_selectors:selectors});
 if(contentHash((await store.readEnvelope('pending',successor)).payload)!==contentHash(original.payload))throw Error('Original semantics changed');
 const prospective=pending.filter(p=>p.id!==active.id).map(p=>String(p.id)).concat(successor);if((await validateAttributionProposalTrace(root,sid,prospective,[],[])).length)throw Error('Trace still fails');
 await call('withdraw_compiler_proposal',{proposal_id:active.id,reason:`Host full-source review restores complete content already supported by the original quotation, with corrected object anchor; ${reviewPath}`});
 if((await validator.validatePendingStructure(sid)).length)throw Error('Projection still fails');
 journal.reviewUnsupported('propose_proposition',id,reason,reviewPath);journal.assertFinishable();
 await call('finish_compiler_batch',{outcome:'complete',reviewed_segments:[],summary:'Host restores full source-supported exploration constraint and repairs its object quotation boundary; original lifecycle history retained.',target_reviews:[{target:'event:event-bronze-city-discovered-00010',disposition:'proposed',evidence_segment_ids:['a28585b1cf867f3e3a16-00010-4539f49e0b67'],summary:'Ye Sheng receives and acknowledges Mans reported two-hour exploration constraint. No resource quantity or future event is committed.'}]});
 const receipt=await receipts.read();if(receipt?.state!=='completed')throw Error('Finish failed');await receipts.verify(receipt);
 for(const p of pending)if(contentHash(await store.readEnvelope(p.id===active.id?'rejected':'pending',String(p.id)))!==contentHash(p))throw Error('Prior draft altered');
 if(contentHash(await readKnowledgeRepairPlan(root,sid,batch))!==contentHash(plan)||contentHash(await store.readEnvelope('rejected',id))!==contentHash(original))throw Error('Original history changed');
 state.appliedRepairHistory.push(state.appliedRepair);state.appliedRepair={repairId:'exploration-full-projection-and-lifecycle-v1',failureFingerprint:state.failureFingerprint,reviewPath,appliedAt:new Date().toISOString()};
 await fs.writeFile(new URL('host-review-exploration-projection-result.json',dir),JSON.stringify({receipt:receipt.fingerprint,successor,originalSemanticsRestored:true}));
 await fs.writeFile(new URL('state.tmp.json',dir),JSON.stringify(state,null,2));await fs.rename(new URL('state.tmp.json',dir),new URL('state.json',dir));console.log(JSON.stringify({ready:true,receipt:receipt.fingerprint}));
});
