import fs from 'node:fs/promises';
import { CanonicalModelStore } from '../../src/world/canonical-model.js';
import { characterEntryCheckpointSchema } from '../../src/world/model.js';
import { worldStorageRoot } from '../../src/world/paths.js';
import { contentHash } from '../../src/world/canonical.js';
import { WorkspaceStore } from '../../src/storage/workspace-store.js';
import { SourceMaterialStore } from '../../src/storage/source-material-store.js';
import { inspectCompilerStatus } from '../../src/compiler/status.js';
import { CompilerFinishReceipts } from '../../src/compiler/finish-receipts.js';
import { EvidenceAssertionStore } from '../../src/compiler/evidence-assertions.js';
import { createCompilerProposalToolset } from '../../src/compiler/proposal-tools.js';
import { convergeWorldProposals } from '../../src/compiler/converge.js';
import { assertReconciliationDeferralsReviewed } from '../../src/compiler/reconciliation-review-ledger.js';
import { compilerFailureCauseFingerprint } from '../../src/runtime/codex-compile-loop.js';
import { withWorkspaceOperationLock } from '../../src/util/workspace-lock.js';
const root=process.cwd(),dir=new URL('./',import.meta.url);
await withWorkspaceOperationLock(root,'compiler',async()=>{
 const state=JSON.parse(await fs.readFile(new URL('state.json',dir),'utf8'));
 if(state.attempt!==58||state.status!=='needs-review'||state.knowledgeRepair.pending)throw Error('Incident changed');
 const status=(await inspectCompilerStatus(root,state.sourceId)).sources[0]!;
 if(status.sourceIntegrity!=='verified'||status.hasUnresolvedObligations||status.worldProposalInventory.pending)throw Error('Unreviewed obligations');
 const canon=new CanonicalModelStore(root),events=await canon.listEvents();
 const event=events.find(e=>e.id==='event-underwater-earthquake-00010');if(!event||event.characterEntryCheckpoints?.length)throw Error('Entry target changed');
 const priorRepair=events.find(e=>e.id==='event-man-asks-coins-00009');if(!priorRepair?.characterEntryCheckpoints?.some(c=>c.actorId==='char-unnamed-man-00009'))throw Error('Prior targeted failure recurred; stop');
 const sorted=events.slice().sort((a,b)=>Math.min(...a.evidence.map(r=>r.span.startLine))-Math.min(...b.evidence.map(r=>r.span.startLine))||(a.narrativeContext?.discourseOrder??0)-(b.narrativeContext?.discourseOrder??0)||a.id.localeCompare(b.id));
 for(const actor of ['char-mans'])if(sorted.find(e=>(!e.narrativeContext||e.narrativeContext.mode==='scene')&&e.participantPresence?.some(p=>p.entityId===actor&&p.mode==='physical'))?.id!==event.id)throw Error('First-entry target changed');
 const originalBatch=`reconcile-${state.sourceId}-bounded-codex-target-review-v1-20260912-2`,predecessor=new CompilerFinishReceipts(root,state.sourceId,originalBatch),old=await predecessor.read();if(old?.state!=='completed')throw Error('Original finish missing');await predecessor.verify(old);
 const reports=old.identity.input.target_reviews?.filter(r=>['event:event-underwater-earthquake-00010'].includes(r.target));if(reports?.length!==1||reports.some(r=>r.disposition!=='capability-gap'))throw Error('Original reports changed');
 const ledgerDir=worldStorageRoot(root)+'/compiler/reconciliation-reviews/'+state.sourceId;
 const ledgers=[];for(const file of await fs.readdir(ledgerDir)){const ledger=JSON.parse(await fs.readFile(ledgerDir+'/'+file,'utf8'));const results=ledger.results?.filter((r:{target:string})=>r.target==='event:event-underwater-earthquake-00010');if(results?.length)ledgers.push({file,finishFingerprint:ledger.finishFingerprint,results});}if(!ledgers.length)throw Error('Original target ledger missing');
 const source=await WorkspaceStore.openReadOnly(root).getSource(state.sourceId);if(!source)throw Error('Source missing');const bytes=await new SourceMaterialStore().read(source);if(!bytes)throw Error('Immutable source missing');const lines=bytes.toString('utf8').split('\n');
 const exact=(needle:string)=>{const matches=lines.slice(1800,1808).filter(l=>l.includes(needle));if(matches.length!==1)throw Error('Anchor not unique');return matches[0]!.trim();};
 const warning=exact('长江航道海事局通知我们可能会有强度五级的水下地震'),monitor=exact('曼斯走进前舱，凑到塞尔玛身边'),recall=exact('叶胜、亚纪，准备上浮。');
 const checkpoints=[characterEntryCheckpointSchema.parse({actorId:'char-mans',readerSetup:'水下地震尚未开始。曼斯在摩尼亚赫号前舱收到地震预警，已通过耳机通知叶胜、亚纪准备上浮。',actorObservation:'你在前舱查看潜水员的监测信号，收到地震预警，正准备让叶胜和亚纪撤回水面。',participantPresence:[{entityId:'char-mans',mode:'physical'}],delta:{version:1,operations:[{op:'set',entityId:'char-mans',field:'character.plan',value:'让叶胜和酒德亚纪准备上浮，撤回水面'}]}})];
 const next={...event,characterEntryCheckpoints:checkpoints};
 const batch=`host-mans-earthquake-pre-entry-${state.sourceId}-v1`,reviewPath='run-records/2026-09-11-codex-compile-loop/host-review-mans-earthquake-entry-checkpoint.json';
 await fs.writeFile(new URL('host-review-mans-earthquake-entry-checkpoint.json',dir),JSON.stringify({reviewedAt:new Date().toISOString(),priorState:state,originalBatch,originalReceipt:old.fingerprint,reports,ledgers,original:event,next,sourceQuotes:{warning,monitor,recall},reason:'Host reviewed the original capability-gap report and subsequent accepted knowledge proposal ledger against immutable source lines 1801-1808. The original location.condition numerical gap is not solved by inventing a number. For the separate entry gap, source expressly places Mans in the forward cabin monitoring the divers and ordering ascent before the earthquake. Current validated inline checkpoint schema permits a grounded character.plan without a full projection seed. Add only his existing pre-earthquake recall plan and physical setup. Keep divers observation knowledge after the event; do not seed actual earthquake, broken tether, collapse, rescue success or numerical environmental state. All original fields, identities, reports, receipts and publication gates are retained.',validation:'Character entry, entry-context, compiler finish/obligation and loop regressions plus strict type check and normal schema/evidence/commit verification.'},null,2),{flag:'wx'});
 const toolset=createCompilerProposalToolset(root);await toolset.beginBatch([],batch,state.sourceId);const call=(name:string,input:unknown)=>toolset.tools.find(t=>t.name===name)!.execute(name,input as never,undefined,undefined,{} as never);
 const segment='a28585b1cf867f3e3a16-00010-4539f49e0b67';
 const assertions=await new EvidenceAssertionStore(root).listForArtifact('canonical-event',event.id);
 const selectors=assertions.flatMap(a=>a.anchors.map(anchor=>{
  const exact=bytes.subarray(anchor.startByte,anchor.endByte).toString('utf8'),needle=Buffer.from(exact),hits:number[]=[];
  for(let offset=256734;offset<305615;){const at=bytes.indexOf(needle,offset);if(at<0||at+needle.length>305615)break;hits.push(at);offset=at+1;}
  const occurrence=hits.indexOf(anchor.startByte)+1;if(!occurrence)throw Error('Original evidence outside reviewed segment');
  return {segment_id:segment,exact,...(hits.length>1?{occurrence}:{}),target_path:a.target.jsonPointer,relation:a.relation,strength:a.strength,...(a.interpretation?{interpretation:a.interpretation}:{})};
 }));
 for(let index=0;index<checkpoints.length;index++)for(const field of ['readerSetup','actorObservation','participantPresence','delta'])for(const quote of [warning,monitor,recall])selectors.push({segment_id:segment,exact:quote,target_path:`/characterEntryCheckpoints/${index}/${field}`,relation:'supports',strength:'strong-inference',interpretation:'Explicit pre-earthquake warning, monitoring and ascent instruction establish Mans own recall plan. No earthquake outcome or diver knowledge seeded.'});
 const {evidence,...payload}=next;await call('propose_canonical_event',{proposal_id:'event-mans-earthquake-host-checkpoint-v1',payload,evidence_segment_ids:[segment],evidence_selectors:selectors});
 await call('finish_compiler_batch',{outcome:'complete',reviewed_segments:[],summary:'Source-reviewed pre-earthquake recall-plan checkpoint for Mans; original post-event observation knowledge retained.'});
 const receipts=new CompilerFinishReceipts(root,state.sourceId,batch),receipt=await receipts.read();if(receipt?.state!=='completed')throw Error('Finish incomplete');await receipts.verify(receipt);
 const result=await convergeWorldProposals(root,state.sourceId);if(result.canonical.blocked.length||result.possibilities.blocked.length)throw Error(JSON.stringify(result));
 const current=await canon.listEvents();for(const e of events)if(contentHash(current.find(c=>c.id===e.id))!==contentHash(e.id===event.id?next:e))throw Error('Unexpected event change');
 await predecessor.verify(old);
 let gate=false;try{await assertReconciliationDeferralsReviewed(root,state.sourceId);}catch(e){if(String(e).includes('host source review'))gate=true;else throw e;}if(!gate)throw Error('Original review gate lost');
 state.appliedRepairHistory.push(state.appliedRepair);state.appliedRepair={repairId:'mans-source-reviewed-pre-earthquake-checkpoint-v1',failureFingerprint:compilerFailureCauseFingerprint({category:'missing-source-backed-mans-earthquake-entry',targetIds:['char-mans'],dependencyIds:[event.id]}),reviewPath,appliedAt:new Date().toISOString()};
 await fs.writeFile(new URL('host-review-mans-earthquake-entry-checkpoint-result.json',dir),JSON.stringify({receipt:receipt.fingerprint,gateRetained:gate,onlyEntryCheckpointAdded:true}));
 await fs.writeFile(new URL('state.tmp.json',dir),JSON.stringify(state,null,2));await fs.rename(new URL('state.tmp.json',dir),new URL('state.json',dir));console.log(JSON.stringify({ready:true,receipt:receipt.fingerprint,gateRetained:gate}));
});
