import fs from 'node:fs/promises';
import {ProposalStore,CanonicalModelStore} from '../../src/world/canonical-model.js';
import {CompilerProposalObligations} from '../../src/compiler/proposal-obligations.js';
import {createCompilerProposalToolset} from '../../src/compiler/proposal-tools.js';
import {CompilerFinishReceipts} from '../../src/compiler/finish-receipts.js';
import {readKnowledgeRepairPlan} from '../../src/compiler/knowledge-repair.js';
import {SourceAnnotationStore,quotationSchema} from '../../src/compiler/annotations.js';
import {WorkspaceStore} from '../../src/storage/workspace-store.js';
import {SourceMaterialStore} from '../../src/storage/source-material-store.js';
import {validateAttributionProposalTrace} from '../../src/compiler/attribution-trace.js';
import {evidenceAssertionSchema} from '../../src/world/model.js';
import {contentHash} from '../../src/world/canonical.js';
import {compilerFailureFingerprint} from '../../src/runtime/codex-compile-loop.js';
import {withWorkspaceOperationLock} from '../../src/util/workspace-lock.js';
const root=process.cwd(),dir=new URL('./',import.meta.url);
await withWorkspaceOperationLock(root,'compiler',async()=>{
 const state=JSON.parse(await fs.readFile(new URL('state.json',dir),'utf8'));
 if(state.attempt!==17||state.status!=='needs-review'||!state.knowledgeRepair.pending)throw Error('Incident changed');
 const sid=state.sourceId,batch=state.knowledgeRepair.batchId,proposalId='event-lumingze-visit-001-'+batch;
 const journal=new CompilerProposalObligations(root,sid,batch),history=journal.history('propose_canonical_event',proposalId),failed=history.filter(a=>a.status==='failed');
 if(failed.length!==2||failed.some(a=>a.hostReview)||journal.unresolved().length!==1||!failed[1]!.diagnostic.includes('3 occurrences match'))throw Error('Obligation changed');
 if([state.appliedRepair,...state.appliedRepairHistory].some(r=>r.failureFingerprint===state.failureFingerprint))throw Error('Reviewed failure repeated; stop');
 const store=new ProposalStore(root),pending=await Promise.all((await store.list('pending',sid)).map(p=>store.readEnvelope('pending',p.id)));
 if(pending.length!==3||pending.some(p=>(p.generatedBy as any).compilerBatchId!==batch))throw Error('Draft scope changed');
 const receipts=new CompilerFinishReceipts(root,sid,batch);if(await receipts.read())throw Error('Original finish already exists');
 const plan=await readKnowledgeRepairPlan(root,sid,batch);if(!plan||plan.events[0]?.id!=='event-lumingze-visit-001')throw Error('Plan changed');
 const original=failed[1]!.input as any,input=structuredClone(original);
 const current=(await new CanonicalModelStore(root).listEvents()).find(e=>e.id===plan.events[0]!.id)!;
 if(contentHash(current)!==contentHash(plan.events[0]))throw Error('Reviewed baseline changed');
 const {evidence, ...baseline}=current,{observedKnowledge,...eventRest}=input.payload;
 if(contentHash(eventRest)!==contentHash(baseline)||observedKnowledge.operations.length!==1||observedKnowledge.operations[0].status!=='heard'||observedKnowledge.operations[0].sourceActorId!=='char-lumingze-boy')throw Error('Event requires additional semantic review');
 const doc=await WorkspaceStore.openReadOnly(root).getSource(sid);if(!doc)throw Error('Missing source');const bytes=await new SourceMaterialStore().read(doc);if(!bytes)throw Error('Missing original bytes');
 const lines=bytes.toString('utf8').split('\n'),quote=quotationSchema.parse(await new SourceAnnotationStore(root).read(sid,'q-lzcheat-001'));
 const exact=bytes.subarray(quote.anchor.startByte,quote.anchor.endByte).toString('utf8');
 if(exact!=='我教给你的第一个秘籍就是black sheep wall，现在这个秘籍解封。使用它，你会获得一份周围环境的详细地图。但是记得不要滥用，用多了会被发现的。')throw Error('Original quote changed');
 if(original.evidence_selectors[1].target_path!=='/observedKnowledge/operations/0/actorId'||original.evidence_selectors[1].exact!=='路明非愣了一下，')throw Error('Actor selector changed');
 input.evidence_selectors[1].exact=lines[1975]!.trim();
 if(!input.evidence_selectors[1].exact.startsWith('路明非愣了一下，“神神鬼鬼的'))throw Error('Source listener reply changed');
 const segmentId='a28585b1cf867f3e3a16-00011-80174f0bd7d3',slice=bytes.subarray(305615,330964).toString('utf8');
 for(const s of input.evidence_selectors)if(s.segment_id!==segmentId||slice.split(s.exact).length!==2)throw Error('Selector not unique in original scope');
 const prop=pending.find(p=>p.kind==='proposition')!,assertions=(prop.evidenceAssertions as unknown[]).map(a=>evidenceAssertionSchema.parse(a));
 const obj=assertions.find(a=>a.target.jsonPointer==='/object/value')!;
 if(obj.anchors.length!==1||bytes.subarray(obj.anchors[0]!.startByte,obj.anchors[0]!.endByte).toString('utf8')!==`“${exact}”`)throw Error('Proposition anchor requires separate review');
 const issues=await validateAttributionProposalTrace(root,sid,pending.map(p=>String(p.id)),[],[]);
 if(issues.length!==1||!issues[0]!.includes('prop-lzcheat-disclosure-001 object evidence is outside'))throw Error('Unexpected trace diagnostics '+issues.join(';'));
 const reviewPath='run-records/2026-09-11-codex-compile-loop/host-review-boy-selectors.json';
 const reason='Host read original lines 1962-1978. Preserve the original failed event ID and semantic payload; replace only its ambiguous listener selector with the unique full immediate reply. The existing proposition object anchor wrongly includes quotation marks outside the retained quotation; narrow only that exact selector through a justified same-content successor. Keep every other draft, assertion, plan, namespace, checkpoint and historical failed input. The host grant permits one exact reviewed input through normal validation and leaves failures unresolved until verified success.';
 await fs.writeFile(new URL('host-review-boy-selectors.json',dir),JSON.stringify({reviewedAt:new Date().toISOString(),reason,sourceId:sid,batchId:batch,failed,original,input,issues,quote,plan,pending,sourceLines:lines.slice(1961,1979),priorRepair:state.appliedRepair,validation:'10 focused tests including successful and failed host correction through real tools; repository type checks passed.'},null,2),{flag:'wx'});
 const tools=createCompilerProposalToolset(root);await tools.beginBatch([],batch,sid);const call=(name:string,args:unknown)=>tools.tools.find(t=>t.name===name)!.execute(name,args as never,undefined,undefined,{}as never);
 await journal.withHostSelectorCorrection('propose_canonical_event',input,failed.map(a=>a.inputHash),reason,reviewPath,()=>call('propose_canonical_event',input));
 journal.assertFinishable();
 const {evidence:oldEvidence,...payload}=prop.payload as any,successor='prop-lzcheat-disclosure-object-anchor-host-v1-'+batch;
 const selectors=assertions.map(a=>{if(a.anchors.length!==1)throw Error('Unexpected multi-anchor assertion');return {segment_id:segmentId,target_path:a.target.jsonPointer,exact:a.target.jsonPointer==='/object/value'?exact:bytes.subarray(a.anchors[0]!.startByte,a.anchors[0]!.endByte).toString('utf8'),relation:a.relation,strength:a.strength,...(a.interpretation?{interpretation:a.interpretation}:{})};});
 await call('propose_proposition',{proposal_id:successor,payload,evidence_segment_ids:[segmentId],evidence_selectors:selectors});
 if(contentHash((await store.readEnvelope('pending',successor)).payload)!==contentHash(prop.payload))throw Error('Proposition semantics changed');
 const prospective=pending.filter(p=>p.id!==prop.id).map(p=>String(p.id)).concat(successor,proposalId);
 if((await validateAttributionProposalTrace(root,sid,prospective,[],[])).length)throw Error('Corrected content trace still fails; stop');
 await call('withdraw_compiler_proposal',{proposal_id:prop.id,reason:`Host-reviewed exact object anchor correction; semantic payload unchanged in ${successor}. Audit ${reviewPath}`});
 for(const p of pending.filter(p=>p.id!==prop.id))if(contentHash(await store.readEnvelope('pending',String(p.id)))!==contentHash(p))throw Error('Unrelated draft changed');
 await call('finish_compiler_batch',{outcome:'complete',reviewed_segments:[],summary:'Host corrected listener disambiguation and proposition quotation boundary, preserving all semantic payloads and identity split.',target_reviews:[{target:'event:event-lumingze-visit-001',disposition:'proposed',evidence_segment_ids:[segmentId],summary:'Lumingfei hears the boy describe black sheep wall. This is a received report, not proof of an operational ability or knowledge belonging to the cousin.'}]});
 const receipt=await receipts.read();if(receipt?.state!=='completed')throw Error('Original finish incomplete');await receipts.verify(receipt);
 state.appliedRepairHistory=[...state.appliedRepairHistory,state.appliedRepair];state.appliedRepair={repairId:'boy-listener-and-content-selectors-v1',failureFingerprint:compilerFailureFingerprint(state.error),reviewPath,appliedAt:new Date().toISOString()};
 await fs.writeFile(new URL('state.tmp.json',dir),JSON.stringify(state,null,2));await fs.rename(new URL('state.tmp.json',dir),new URL('state.json',dir));
 console.log(JSON.stringify({ready:true,originalProposalId:proposalId,receiptFingerprint:receipt.fingerprint,failedAttemptsPreserved:failed.length,unrelatedDraftsPreserved:2}));
});
