import fs from "node:fs/promises";
import { WorkspaceStore } from "../../src/storage/workspace-store.js";
import { SourceMaterialStore } from "../../src/storage/source-material-store.js";
import { CanonicalModelStore } from "../../src/world/canonical-model.js";
import { SourceAnnotationStore } from "../../src/compiler/annotations.js";
import { EntityResolutionStore } from "../../src/compiler/entity-resolution.js";
import { inspectCompilerStatus } from "../../src/compiler/status.js";
import { CompilerFinishReceipts } from "../../src/compiler/finish-receipts.js";
import { createCompilerProposalToolset } from "../../src/compiler/proposal-tools.js";
import { writeKnowledgeRepairPlan, buildKnowledgeRepairPrompt } from "../../src/compiler/knowledge-repair.js";
import { assertReconciliationDeferralsReviewed } from "../../src/compiler/reconciliation-review-ledger.js";
import { validateCommittedAttributionTrace } from "../../src/compiler/attribution-trace.js";
import { contentHash } from "../../src/world/canonical.js";
import { compilerFailureFingerprint } from "../../src/runtime/codex-compile-loop.js";
import { withWorkspaceOperationLock } from "../../src/util/workspace-lock.js";
const root=process.cwd(),dir=new URL("./",import.meta.url);
await withWorkspaceOperationLock(root,"compiler",async()=>{
  const state=JSON.parse(await fs.readFile(new URL("state.json",dir),"utf8"));
  if(state.attempt!==16||state.status!=="needs-review"||state.knowledgeRepair.pending)throw Error("Incident changed.");
  const source=(await inspectCompilerStatus(root,state.sourceId)).sources.find(s=>s.sourceId===state.sourceId)!;
  if(source.sourceIntegrity!=="verified"||source.hasUnresolvedObligations||source.worldProposalInventory.pending)throw Error("Unreviewed source or obligations.");
  const canon=new CanonicalModelStore(root), annotations=new SourceAnnotationStore(root);
  for(const a of await canon.listAttributions())if((await validateCommittedAttributionTrace(root,state.sourceId,a)).length)throw Error("Prior trace repair has not passed.");
  const events=await canon.listEvents(),event=events.find(e=>e.id==="event-lumingze-visit-001")!;
  if(!event||event.observedKnowledge?.operations.length||event.observedOutcome.operations.length)throw Error("Target changed.");
  const oldBatch=`reconcile-${state.sourceId}-bounded-codex-target-review-v1-20260912-3`;
  const oldStore=new CompilerFinishReceipts(root,state.sourceId,oldBatch),old=await oldStore.read();
  if(old?.state!=="completed")throw Error("Original batch unfinished.");await oldStore.verify(old);
  const report=old.identity.input.target_reviews?.find(r=>r.target===`event:${event.id}`);
  if(report?.disposition!=="capability-gap"||report.summary!=="The visit and warning are explicit, including the newly available Black Sheep Wall phrase, but there is no claim/proposition record compatible with a KnowledgeDelta and no registered field represents the newly available capability. No supported typed effect can be added.")throw Error("Original report changed.");
  const doc=await WorkspaceStore.openReadOnly(root).getSource(state.sourceId);if(!doc)throw Error("Missing source.");
  const bytes=await new SourceMaterialStore().read(doc);if(!bytes)throw Error("Missing immutable bytes.");
  const lines=bytes.toString("utf8").split("\n");
  const exact="我教给你的第一个秘籍就是black sheep wall，现在这个秘籍解封。使用它，你会获得一份周围环境的详细地图。但是记得不要滥用，用多了会被发现的。";
  const quoteId="q-lzcheat-001";
  const quotation=await annotations.read(state.sourceId,quoteId);
  if(quotation.annotationType!=="quotation"||quotation.speakerMentionId!=="em-lumingze-003"||!quotation.addresseeMentionIds?.includes("em-lumingfei-003")||bytes.subarray(quotation.anchor.startByte,quotation.anchor.endByte).toString("utf8")!==exact)throw Error("Exact source quotation changed.");
  const mapping=(await new EntityResolutionStore(root).list(state.sourceId)).filter(r=>["em-lumingze-003","em-lumingfei-003"].includes(r.mentionId));
  if(!mapping.some(r=>r.mentionId==="em-lumingze-003"&&r.entityId==="char-lumingze-boy")||!mapping.some(r=>r.mentionId==="em-lumingfei-003"&&r.entityId==="char-lumingfei")||!event.participants.includes("char-lumingze-boy")||event.participants.includes("char-lumingze"))throw Error("Identity split failed again; preserve and stop.");
  if(!state.identityRepair)throw Error("Identity host review absent.");
  const identityStore=new CompilerFinishReceipts(root,state.sourceId,state.identityRepair.batchId),identityReceipt=await identityStore.read();if(identityReceipt?.state!=="completed"||identityReceipt.fingerprint!==state.identityRepair.receiptFingerprint)throw Error("Identity receipt changed");await identityStore.verify(identityReceipt);
  const dependencies={claims:await canon.listClaims(),propositions:await canon.listPropositions(),attributions:await canon.listAttributions()};
  const batchId=`reconcile-${state.sourceId}-knowledge-effects-${state.semanticRunId}-6`,reviewPath="run-records/2026-09-11-codex-compile-loop/host-review-boy-knowledge.json";
  const review={reviewedAt:new Date().toISOString(),sourceId:state.sourceId,batchId,report,originalFinishFingerprint:old.fingerprint,exact,sourceLines:lines.slice(1956,1979),mapping,dependencies,baseline:event,
    finding:"Host reviewed the original deferred report and exact full quotation. The missing dependency is a claim/proposition for the boy's addressed explanation, not a new arbitrary state field. After the separately verified identity split, Lumingfei may acquire only a told/heard report that the boy says the phrase supplies a detailed map and warns against overuse. This does not establish an operational power, verified world rule, actual map, truth of the report, cousin knowledge, or consent. Preserve every existing event field including presence, outcome and checkpoint; source-wide deferrals and all other audit gaps remain.",
    identityRepair:state.identityRepair,quotation,
    priorKnowledgeRepair:state.knowledgeRepair,priorAppliedRepair:state.appliedRepair,namespaceUnchanged:state.semanticRunId,validation:"Knowledge scope, quotation trace, normal finish and obligation regression tests and type checks passed before application."};
  await fs.writeFile(new URL("host-review-boy-knowledge.json",dir),JSON.stringify(review,null,2),{flag:"wx"});
  await writeKnowledgeRepairPlan(root,{version:1,sourceId:state.sourceId,batchId,predecessorBatchId:oldBatch,predecessorFingerprint:old.fingerprint,reviewRef:reviewPath,events:[event],quotationIds:[quoteId]});
  const prompt=await buildKnowledgeRepairPrompt(root,state.sourceId,batchId);if(!prompt.includes(quoteId))throw Error("Scoped quotation missing from prompt.");
  let gateRetained=false;try{await assertReconciliationDeferralsReviewed(root,state.sourceId);}catch(e){if(String(e).includes("host source review"))gateRetained=true;else throw e;}if(!gateRetained)throw Error("Original deferral gate disappeared.");
  const diagnostic=`Knowledge acquisition remains unresolved for ${event.id}; predecessor=${old.fingerprint}. Host source review required; do not retry unchanged.`;
  state.knowledgeRepairHistory=[...(state.knowledgeRepairHistory??[]),state.knowledgeRepair];
  state.knowledgeRepair={batchId,pending:true,reviewPath};
  state.appliedRepairHistory=[...(state.appliedRepairHistory??[]),state.appliedRepair];
  state.appliedRepair={repairId:"boy-identity-reviewed-knowledge-dependencies-v1",failureFingerprint:compilerFailureFingerprint(diagnostic),reviewPath,appliedAt:new Date().toISOString(),fingerprintBasis:"Original deferred event knowledge gap, not aggregate percentages"};
  await fs.writeFile(new URL("state.tmp.json",dir),JSON.stringify(state,null,2));await fs.rename(new URL("state.tmp.json",dir),new URL("state.json",dir));
  console.log(JSON.stringify({ready:true,target:event.id,quotationId:quoteId,identityReceipt:identityReceipt.fingerprint,gateRetained,namespaceUnchanged:true}));
});
