import fs from "node:fs/promises";
import { WorkspaceStore } from "../../src/storage/workspace-store.js";
import { SourceMaterialStore } from "../../src/storage/source-material-store.js";
import { CanonicalModelStore } from "../../src/world/canonical-model.js";
import { SourceAnnotationStore } from "../../src/compiler/annotations.js";
import { EntityResolutionStore } from "../../src/compiler/entity-resolution.js";
import { inspectCompilerStatus } from "../../src/compiler/status.js";
import { CompilerFinishReceipts } from "../../src/compiler/finish-receipts.js";
import { createCompilerProposalToolset } from "../../src/compiler/proposal-tools.js";
import { writeKnowledgeRepairPlan, buildKnowledgeRepairPrompt } from "../../src/compiler/knowledge-repair.js";
import { assertReconciliationDeferralsReviewed } from "../../src/compiler/reconciliation-review-ledger.js";
import { validateCommittedAttributionTrace } from "../../src/compiler/attribution-trace.js";
import { contentHash } from "../../src/world/canonical.js";
import { compilerFailureFingerprint } from "../../src/runtime/codex-compile-loop.js";
import { withWorkspaceOperationLock } from "../../src/util/workspace-lock.js";
const root=process.cwd(),dir=new URL("./",import.meta.url);
await withWorkspaceOperationLock(root,"compiler",async()=>{
  const state=JSON.parse(await fs.readFile(new URL("state.json",dir),"utf8"));
  if(state.attempt!==29||state.status!=="needs-review"||state.knowledgeRepair.pending)throw Error("Incident changed.");
  const source=(await inspectCompilerStatus(root,state.sourceId)).sources.find(s=>s.sourceId===state.sourceId)!;
  if(source.sourceIntegrity!=="verified"||source.hasUnresolvedObligations||source.worldProposalInventory.pending)throw Error("Unreviewed source or obligations.");
  const canon=new CanonicalModelStore(root), annotations=new SourceAnnotationStore(root);
  for(const a of await canon.listAttributions())if((await validateCommittedAttributionTrace(root,state.sourceId,a)).length)throw Error("Prior trace repair has not passed.");
  const events=await canon.listEvents(),event=events.find(e=>e.id==="event-bronze-city-discovered-00010")!;
  if(!event||event.observedKnowledge?.operations.length||event.observedOutcome.operations.length)throw Error("Target changed.");
  const oldBatch=`reconcile-${state.sourceId}-bounded-codex-target-review-v1-20260912-2`;
  const oldStore=new CompilerFinishReceipts(root,state.sourceId,oldBatch),old=await oldStore.read();
  if(old?.state!=="completed")throw Error("Original batch unfinished.");await oldStore.verify(old);
  const report=old.identity.input.target_reviews?.find(r=>r.target===`event:${event.id}`);
  if(report?.disposition!=="capability-gap"||report.summary!=="Source confirms the city discovery and Mans's authorization, but establishes no representable deterministic state field. Its relative wording does not supply a numeric comparable ordering anchor.")throw Error("Original report changed.");
  const doc=await WorkspaceStore.openReadOnly(root).getSource(state.sourceId);if(!doc)throw Error("Missing source.");
  const bytes=await new SourceMaterialStore().read(doc);if(!bytes)throw Error("Missing immutable bytes.");
  const lines=bytes.toString("utf8").split("\n");
  const exact="好的，我明白了。我会为你们更换新的设备，但是记住，你们的时间只有两个小时，无论是氧气还是电力都只能撑两小时，两小时后长江航道海事局的直升机大概也到了，那时候水下作业将被迫停止。";
  if(!lines[1833]?.includes(`“${exact}”`)||!lines[1834]?.includes('“明白，”叶胜说'))throw Error("Original instruction and response changed");
  const speaker="em-mans-1",listener="em-yesheng-1",quoteId="q-mans-exploration-window-00010",segmentId="a28585b1cf867f3e3a16-00010-4539f49e0b67";
  const mappings=await new EntityResolutionStore(root).list(state.sourceId);
  if(!mappings.some(r=>r.mentionId===speaker&&r.entityId==="char-mans")||!mappings.some(r=>r.mentionId===listener&&r.entityId==="char-yesheng"))throw Error("Identity trace changed");
  const annotationBefore=await annotations.list(state.sourceId);
  for(const id of [speaker,listener]){const a=annotationBefore.find(a=>a.id===id);if(!a||a.annotationType!=="entity-mention"||a.anchor.startLine<1614||a.anchor.startLine>1887)throw Error("Source mention outside exploration segment");}
  if(annotationBefore.some(a=>a.id===quoteId))throw Error("Quotation already reviewed");
  const dependencies={claims:await canon.listClaims(),propositions:await canon.listPropositions(),attributions:await canon.listAttributions()};
  const batchId=`reconcile-${state.sourceId}-knowledge-effects-${state.semanticRunId}-15`,reviewPath="run-records/2026-09-11-codex-compile-loop/host-review-exploration-window.json";
  const review={reviewedAt:new Date().toISOString(),sourceId:state.sourceId,batchId,report,originalFinishFingerprint:old.fingerprint,exact,sourceLines:lines.slice(1824,1836),mappings:mappings.filter(r=>[speaker,listener].includes(r.mentionId)),dependencies,baseline:event,
    finding:"Host reviewed original model capability-gap report and the exploration exchange. Mans directly explains the two-hour equipment window after Ye Sheng argues for continuing; Ye Sheng explicitly replies 明白. Add the exact spoken quotation with established speaker/listener identities. Permit only Ye Sheng hearing Mans's reported operational time constraint through told acquisition and necessary claim/proposition/attribution dependencies. No actual oxygen/electricity quantity, equipment transfer, helicopter arrival, successful exploration or global story-time number follows from this report. Preserve every baseline event field, prior proposal/receipt/deferral, and publication gate.",
    priorKnowledgeRepair:state.knowledgeRepair,priorAppliedRepair:state.appliedRepair,namespaceUnchanged:state.semanticRunId,validation:"Knowledge scope, quotation trace, normal finish and obligation regression tests and type checks passed before application."};
  await fs.writeFile(new URL("host-review-exploration-window.json",dir),JSON.stringify(review,null,2),{flag:"wx"});
  const observationBatch=`host-exploration-window-${state.sourceId}-v1`,tools=createCompilerProposalToolset(root);
  await tools.beginBatch([],observationBatch,state.sourceId);
  const call=(name:string,input:unknown)=>tools.tools.find(t=>t.name===name)!.execute(name,input as never,undefined,undefined,{} as never);
  await call("propose_quotation",{proposal_id:"q-mans-exploration-window-host-v1",annotation_id:quoteId,selector:{segment_id:segmentId,exact},mode:"direct",speaker_mention_id:speaker,addressee_mention_ids:[listener],attribution_confidence:1});
  await call("finish_compiler_batch",{outcome:"complete",reviewed_segments:[],summary:"Host original-source review adds the exact exploration time-window report with resolved speaker/listener; all baseline event data is preserved."});
  const observationStore=new CompilerFinishReceipts(root,state.sourceId,observationBatch),receipt=await observationStore.read();if(receipt?.state!=="completed")throw Error("Observation finish incomplete");await observationStore.verify(receipt);
  for(const a of annotationBefore)if(contentHash(await annotations.read(state.sourceId,a.id))!==contentHash(a))throw Error("Existing annotation changed");
  await writeKnowledgeRepairPlan(root,{version:1,sourceId:state.sourceId,batchId,predecessorBatchId:oldBatch,predecessorFingerprint:old.fingerprint,reviewRef:reviewPath,events:[event],quotationIds:[quoteId]});
  const prompt=await buildKnowledgeRepairPrompt(root,state.sourceId,batchId);if(!prompt.includes(quoteId))throw Error("Scoped quotation missing from prompt.");
  let gateRetained=false;try{await assertReconciliationDeferralsReviewed(root,state.sourceId);}catch(e){if(String(e).includes("host source review"))gateRetained=true;else throw e;}if(!gateRetained)throw Error("Original deferral gate disappeared.");
  const diagnostic=`Knowledge acquisition remains unresolved for ${event.id}; predecessor=${old.fingerprint}. Host source review required; do not retry unchanged.`;
  state.knowledgeRepairHistory=[...(state.knowledgeRepairHistory??[]),state.knowledgeRepair];
  state.knowledgeRepair={batchId,pending:true,reviewPath};
  state.appliedRepairHistory=[...(state.appliedRepairHistory??[]),state.appliedRepair];
  state.appliedRepair={repairId:"exploration-window-source-reviewed-knowledge-v1",failureFingerprint:compilerFailureFingerprint(diagnostic),reviewPath,appliedAt:new Date().toISOString(),fingerprintBasis:"Original deferred event knowledge gap, not aggregate percentages"};
  await fs.writeFile(new URL("state.tmp.json",dir),JSON.stringify(state,null,2));await fs.rename(new URL("state.tmp.json",dir),new URL("state.json",dir));
  console.log(JSON.stringify({ready:true,target:event.id,gateRetained,namespaceUnchanged:true}));
});
