import fs from 'node:fs/promises';
import { CanonicalModelStore } from '../../src/world/canonical-model.js';
import { ActorModelStore } from '../../src/world/actors.js';
import { contentHash } from '../../src/world/canonical.js';
import { WorkspaceStore } from '../../src/storage/workspace-store.js';
import { SourceMaterialStore } from '../../src/storage/source-material-store.js';
import { inspectCompilerStatus } from '../../src/compiler/status.js';
import { CompilerFinishReceipts } from '../../src/compiler/finish-receipts.js';
import { EvidenceAssertionStore } from '../../src/compiler/evidence-assertions.js';
import { createCompilerProposalToolset } from '../../src/compiler/proposal-tools.js';
import { convergeWorldProposals } from '../../src/compiler/converge.js';
import { assertReconciliationDeferralsReviewed } from '../../src/compiler/reconciliation-review-ledger.js';
import { validateEventRelationCatalog } from '../../src/world/event-relations.js';
import { compilerFailureCauseFingerprint } from '../../src/runtime/codex-compile-loop.js';
import { withWorkspaceOperationLock } from '../../src/util/workspace-lock.js';
const root=process.cwd(),dir=new URL('./',import.meta.url);
await withWorkspaceOperationLock(root,'compiler',async()=>{
 const state=JSON.parse(await fs.readFile(new URL('state.json',dir),'utf8'));
 if(state.attempt!==47||state.status!=='needs-review'||state.knowledgeRepair.pending)throw Error('Incident changed');
 const status=(await inspectCompilerStatus(root,state.sourceId)).sources[0]!;
 if(status.sourceIntegrity!=='verified'||status.hasUnresolvedObligations||status.worldProposalInventory.pending)throw Error('Unreviewed obligations');
 const canon=new CanonicalModelStore(root),events=await canon.listEvents(),relations=await canon.listEventRelations();
 const prior=relations.find(r=>r.id==='rel-car-accept-00005'),event=events.find(e=>e.id==='event-accept-00005');
 if(!prior||prior.type!=='motivates'||prior.operationality!=='motivational'||!event||contentHash(event.causalParents)!==contentHash(['event-car-stop-00005']))throw Error('Targets changed');
 const goals=await new ActorModelStore(root).listGoals();if(!goals.some(g=>g.id==='goal-chu-recruit-lumingfei-00013'&&g.activation?.afterCanonicalEventIds.includes('event-chu-invite-001')))throw Error('Prior recruitment repair missing');
 const originalBatch=`reconcile-${state.sourceId}-bounded-codex-target-review-v1-20260912-1`,predecessor=new CompilerFinishReceipts(root,state.sourceId,originalBatch),old=await predecessor.read();
 if(old?.state!=='completed')throw Error('Original finish missing');await predecessor.verify(old);
 const report=old.identity.input.target_reviews?.find(r=>r.target==='event:event-accept-00005');
 if(report?.disposition!=='unsupported'||!report.summary.includes('entry checkpoint'))throw Error('Original report changed');
 const source=await WorkspaceStore.openReadOnly(root).getSource(state.sourceId);if(!source)throw Error('Source missing');const bytes=await new SourceMaterialStore().read(source);if(!bytes)throw Error('Immutable source missing');const lines=bytes.toString('utf8').split('\n');
 const exact=(needle:string)=>{const found=lines.slice(727,788).filter(l=>l.includes(needle));if(found.length!==1)throw Error('Ambiguous/missing reviewed source');return found[0]!.trim();};
 const stopped=exact('发动机熄火了，车停在一家24小时药店的门前'),waiting=exact('下车等等吧，等他们再派车来接我们'),reason=exact('好吧，我答应，不答应怎么办呢？'),offer=exact('你还可以选一次，最后一次'),accept=exact('想好了，我接受。');
 const {motivatedActorIds,...rest}=prior;
 const nextRelation={...rest,type:'before' as const,operationality:'non-operational' as const,mechanism:'The car stops before the roadside enrollment conversation. The passage establishes this temporal order, not that fuel exhaustion causes or is required for Lumingfei to accept enrollment. His stated reasons concern school prospects and returning to classmates after the public departure.'};
 const nextEvent={...event,causalParents:[]};
 const issues=validateEventRelationCatalog({events:new Map(events.map(e=>[e.id,e.id===event.id?nextEvent:e])),relations:relations.map(r=>r.id===prior.id?nextRelation:r)});if(issues.length)throw Error(JSON.stringify(issues));
 const batch=`host-roadside-temporal-correction-${state.sourceId}-v1`,reviewPath='run-records/2026-09-11-codex-compile-loop/host-review-roadside-relation.json';
 await fs.writeFile(new URL('host-review-roadside-relation.json',dir),JSON.stringify({reviewedAt:new Date().toISOString(),priorState:state,originalBatch,originalReceipt:old.fingerprint,report,priorRelation:prior,nextRelation,priorEvent:event,nextEvent,sourceLines:lines.slice(727,772),reason:'Original relation mechanism itself calls the roadside stop a setting, but labels it as motivation and leaves a legacy hard causal parent. Full source explicitly gives the decision reasons and last-choice conversation; no fuel-dependent acceptance mechanism is stated. Correct the relation to temporal before and remove only its unsupported legacy hard-parent projection through normal versioned proposal validation. Do not invent a necessary enabling relation to meet the 100% legacy metric. Preserve original event, relation and proposal revisions in history, the existing acceptance plan effect, physical presence, all checkpoints, original deferred entry-checkpoint report and every publication gate. This is a semantic correction of an unsupported edge, not deletion or settlement of an obligation. Recruitment goal remains present; aggregate remaining gaps do not imply its failure.',validation:'Event relation, time/development, compiler finish, obligations and loop tests; normal typed proposal/finish/convergence and exact field comparison.'},null,2),{flag:'wx'});
 const tools=createCompilerProposalToolset(root);await tools.beginBatch([],batch,state.sourceId);const call=(name:string,input:unknown)=>tools.tools.find(t=>t.name===name)!.execute(name,input as never,undefined,undefined,{} as never);
 const segment='a28585b1cf867f3e3a16-00005-12c9137e67cf';
 const {evidence:relationEvidence,...relationPayload}=nextRelation;
 await call('propose_event_relation',{proposal_id:'rel-car-accept-host-temporal-v1',payload:relationPayload,evidence_segment_ids:[segment],evidence_selectors:['/type','/operationality','/mechanism'].flatMap(target_path=>[stopped,waiting,offer,reason,accept].map(exact=>({segment_id:segment,exact,target_path,relation:'supports',strength:'explicit'})))});
 const assertions=await new EvidenceAssertionStore(root).listForArtifact('canonical-event',event.id);
 const selectors=assertions.filter(a=>!a.target.jsonPointer.startsWith('/causalParents')).flatMap(a=>a.anchors.map(anchor=>({segment_id:segment,exact:bytes.subarray(anchor.startByte,anchor.endByte).toString('utf8'),target_path:a.target.jsonPointer,relation:a.relation,strength:a.strength,...(a.interpretation?{interpretation:a.interpretation}:{})})));
 for(const exact of [stopped,waiting,offer,reason,accept])selectors.push({segment_id:segment,exact,target_path:'/causalParents',relation:'supports',strength:'explicit'});
 const {evidence,...payload}=nextEvent;await call('propose_canonical_event',{proposal_id:'event-accept-host-temporal-correction-v1',payload,evidence_segment_ids:[segment],evidence_selectors:selectors});
 await call('finish_compiler_batch',{outcome:'complete',reviewed_segments:[],summary:'Correct roadside relation from unsupported motivation/hard parent to explicit temporal order, preserving acceptance effects and original entry-checkpoint review obligations.'});
 const receipts=new CompilerFinishReceipts(root,state.sourceId,batch),receipt=await receipts.read();if(receipt?.state!=='completed')throw Error('Finish incomplete');await receipts.verify(receipt);
 const result=await convergeWorldProposals(root,state.sourceId);if(result.canonical.blocked.length||result.possibilities.blocked.length)throw Error(JSON.stringify(result));
 const currentEvents=await canon.listEvents(),currentRelations=await canon.listEventRelations();
 for(const e of events)if(contentHash(currentEvents.find(c=>c.id===e.id))!==contentHash(e.id===event.id?nextEvent:e))throw Error('Unexpected event change');
 for(const r of relations)if(contentHash(currentRelations.find(c=>c.id===r.id))!==contentHash(r.id===prior.id?nextRelation:r))throw Error('Unexpected relation change');
 if(contentHash(await new ActorModelStore(root).listGoals())!==contentHash(goals))throw Error('Goals changed');
 await predecessor.verify(old);
 let gate=false;try{await assertReconciliationDeferralsReviewed(root,state.sourceId);}catch(e){if(String(e).includes('host source review'))gate=true;else throw e;}if(!gate)throw Error('Original review gate lost');
 state.appliedRepairHistory.push(state.appliedRepair);state.appliedRepair={repairId:'roadside-setting-temporal-not-causal-v1',failureFingerprint:compilerFailureCauseFingerprint({category:'unsupported-setting-as-hard-cause',targetIds:[event.id],dependencyIds:[prior.id]}),reviewPath,appliedAt:new Date().toISOString()};
 await fs.writeFile(new URL('host-review-roadside-relation-result.json',dir),JSON.stringify({receipt:receipt.fingerprint,gateRetained:gate,onlyReviewedEdgeFieldsChanged:true}));
 await fs.writeFile(new URL('state.tmp.json',dir),JSON.stringify(state,null,2));await fs.rename(new URL('state.tmp.json',dir),new URL('state.json',dir));console.log(JSON.stringify({ready:true,receipt:receipt.fingerprint,gateRetained:gate}));
});
