import fs from "node:fs/promises";
import { WorkspaceStore } from "../../src/storage/workspace-store.js";
import { SourceMaterialStore } from "../../src/storage/source-material-store.js";
import { CanonicalModelStore } from "../../src/world/canonical-model.js";
import { inspectCompilerStatus } from "../../src/compiler/status.js";
import { CompilerFinishReceipts } from "../../src/compiler/finish-receipts.js";
import { writeKnowledgeRepairPlan, buildKnowledgeRepairPrompt } from "../../src/compiler/knowledge-repair.js";
import { assertReconciliationDeferralsReviewed } from "../../src/compiler/reconciliation-review-ledger.js";
import { validateCommittedAttributionTrace } from "../../src/compiler/attribution-trace.js";
import { compilerFailureCauseFingerprint } from "../../src/runtime/codex-compile-loop.js";
import { withWorkspaceOperationLock } from "../../src/util/workspace-lock.js";
const root=process.cwd(),dir=new URL("./",import.meta.url);
await withWorkspaceOperationLock(root,"compiler",async()=>{
  const state=JSON.parse(await fs.readFile(new URL("state.json",dir),"utf8"));
  if(state.attempt!==35||state.status!=="needs-review"||state.knowledgeRepair.pending)throw Error("Incident changed.");
  const source=(await inspectCompilerStatus(root,state.sourceId)).sources.find(s=>s.sourceId===state.sourceId)!;
  if(source.sourceIntegrity!=="verified"||source.hasUnresolvedObligations||source.worldProposalInventory.pending)throw Error("Unreviewed source or obligations.");
  const canon=new CanonicalModelStore(root);
  for(const a of await canon.listAttributions())if((await validateCommittedAttributionTrace(root,state.sourceId,a)).length)throw Error("Prior trace repair has not passed.");
  const events=await canon.listEvents(),event=events.find(e=>e.id==="event-academy-emergency-alarm-001")!;
  if(!event||event.observedKnowledge?.operations.length||event.observedOutcome.operations.length)throw Error("Target changed.");
  const oldBatch=`reconcile-${state.sourceId}-bounded-codex-target-review-v1-20260912-2`;
  const oldStore=new CompilerFinishReceipts(root,state.sourceId,oldBatch),old=await oldStore.read();
  if(old?.state!=="completed")throw Error("Original batch unfinished.");await oldStore.verify(old);
  const report=old.identity.input.target_reviews?.find(r=>r.target===`event:${event.id}`);
  if(report?.disposition!=="capability-gap"||report.summary!=="The alarm summons high-ranked students, but summons are not a catalog state field. The source says the time is one-thirty after noon without a date or established global ordinal order.")throw Error("Original report changed.");
  const doc=await WorkspaceStore.openReadOnly(root).getSource(state.sourceId);if(!doc)throw Error("Missing source.");
  const bytes=await new SourceMaterialStore().read(doc);if(!bytes)throw Error("Missing immutable bytes.");
  const lines=bytes.toString("utf8").split("\n");
  const exact="路明非站在宿舍过道中。天花板上的红灯闪烁，刺耳的蜂鸣声来自隐藏在墙壁中的扩音器。学生们正从各个楼梯出口向着电梯汇集，有男有女，都穿着校服，神色严肃。卡塞尔学院规模有限，1区宿舍男女混住。";
  if(lines[1983]?.trim()!==exact||!lines[1978]?.includes("门外传来了刺耳的蜂鸣声"))throw Error("Original alarm observation changed");
  if(!event.participants.includes("char-lumingfei")||event.participantPresence?.find(p=>p.entityId==="char-lumingfei")?.mode!=="physical")throw Error("Observer changed");
  const dependencies={claims:await canon.listClaims(),propositions:await canon.listPropositions(),attributions:await canon.listAttributions()};
  const batchId=`reconcile-${state.sourceId}-knowledge-effects-${state.semanticRunId}-20`,reviewPath="run-records/2026-09-11-codex-compile-loop/host-review-alarm-observation.json";
  const review={reviewedAt:new Date().toISOString(),sourceId:state.sourceId,batchId,report,originalFinishFingerprint:old.fingerprint,exact,sourceLines:lines.slice(1978,1989),dependencies,baseline:event,
    finding:"Host compared the verbatim original capability-gap report with immutable source lines 1979-1989. A summons state field and global numeric date remain unsupported; do not fabricate either. But source explicitly places Lumingfei in the dormitory corridor hearing the alarm and seeing red lights and students assembling. Existing observed knowledge can record that concrete sensory information using a source-grounded proposition and compatible claim, without inventing entities or world-state fields. Do not equate hearing the buzzer with knowing the alarm's purpose: Fingel's later explanation would require a verified speaker attribution, and this event has only Lumingfei as participant. Limit this supplement to his direct perception. Preserve time ambiguity, every baseline field, original report, proposals, obligations and all publication gates. Prior map supplement committed three physically present observers reading the displayed attribution; exact source says all interfaces showed the map and names Lumingfei's interpretation, supporting those observers. Its remaining audit gaps are not a recurrence of missing knowledge.",
    priorKnowledgeRepair:state.knowledgeRepair,priorAppliedRepair:state.appliedRepair,namespaceUnchanged:state.semanticRunId,validation:"Knowledge scope, quotation trace, normal finish and obligation regression tests and type checks passed before application."};
  await fs.writeFile(new URL("host-review-alarm-observation.json",dir),JSON.stringify(review,null,2),{flag:"wx"});
  await writeKnowledgeRepairPlan(root,{version:1,sourceId:state.sourceId,batchId,predecessorBatchId:oldBatch,predecessorFingerprint:old.fingerprint,reviewRef:reviewPath,events:[event]});
  const prompt=await buildKnowledgeRepairPrompt(root,state.sourceId,batchId);if(!prompt.includes(event.id))throw Error("Scoped quotation missing from prompt.");
  let gateRetained=false;try{await assertReconciliationDeferralsReviewed(root,state.sourceId);}catch(e){if(String(e).includes("host source review"))gateRetained=true;else throw e;}if(!gateRetained)throw Error("Original deferral gate disappeared.");
  state.knowledgeRepairHistory=[...(state.knowledgeRepairHistory??[]),state.knowledgeRepair];
  state.knowledgeRepair={batchId,pending:true,reviewPath};
  state.appliedRepairHistory=[...(state.appliedRepairHistory??[]),state.appliedRepair];
  state.appliedRepair={repairId:"alarm-perception-source-reviewed-knowledge-v1",failureFingerprint:compilerFailureCauseFingerprint({category:"knowledge-not-produced-with-verified-evidence",targetIds:[event.id],dependencyIds:[]}),reviewPath,appliedAt:new Date().toISOString(),fingerprintBasis:"Original deferred event knowledge gap, not aggregate percentages"};
  await fs.writeFile(new URL("state.tmp.json",dir),JSON.stringify(state,null,2));await fs.rename(new URL("state.tmp.json",dir),new URL("state.json",dir));
  console.log(JSON.stringify({ready:true,target:event.id,gateRetained,namespaceUnchanged:true}));
});
