import { EvidenceAssertionStore } from "../../src/compiler/evidence-assertions.js";
import { contentHash } from "../../src/world/canonical.js";
import { createCompilerProposalToolset } from "../../src/compiler/proposal-tools.js";
import { convergeWorldProposals } from "../../src/compiler/converge.js";
import fs from "node:fs/promises";
import { WorkspaceStore } from "../../src/storage/workspace-store.js";
import { SourceMaterialStore } from "../../src/storage/source-material-store.js";
import { CanonicalModelStore } from "../../src/world/canonical-model.js";
import { inspectCompilerStatus } from "../../src/compiler/status.js";
import { CompilerFinishReceipts } from "../../src/compiler/finish-receipts.js";
import { writeKnowledgeRepairPlan, buildKnowledgeRepairPrompt, readKnowledgeRepairPlan } from "../../src/compiler/knowledge-repair.js";
import { assertReconciliationDeferralsReviewed } from "../../src/compiler/reconciliation-review-ledger.js";
import { validateCommittedAttributionTrace } from "../../src/compiler/attribution-trace.js";
import { compilerFailureCauseFingerprint } from "../../src/runtime/codex-compile-loop.js";
import { withWorkspaceOperationLock } from "../../src/util/workspace-lock.js";
const root=process.cwd(),dir=new URL("./",import.meta.url);
await withWorkspaceOperationLock(root,"compiler",async()=>{
  const state=JSON.parse(await fs.readFile(new URL("state.json",dir),"utf8"));
  if(state.attempt!==36||state.status!=="needs-review"||state.knowledgeRepair.pending)throw Error("Incident changed.");
  const source=(await inspectCompilerStatus(root,state.sourceId)).sources.find(s=>s.sourceId===state.sourceId)!;
  if(source.sourceIntegrity!=="verified"||source.hasUnresolvedObligations||source.worldProposalInventory.pending)throw Error("Unreviewed source or obligations.");
  const canon=new CanonicalModelStore(root);
  for(const a of await canon.listAttributions())if((await validateCommittedAttributionTrace(root,state.sourceId,a)).length)throw Error("Prior trace repair has not passed.");
  const events=await canon.listEvents(); let event=events.find(e=>e.id==="event-academy-emergency-alarm-001")!;
  if(event?.observedKnowledge?.operations.length!==1||event.observedKnowledge.operations[0]?.op!=="learn"||event.observedKnowledge.operations[0]?.attributionId!=="attr-schneider-rescue-members-trapped-001")throw Error("Target changed");
  const badEvent=event, priorPlan=await readKnowledgeRepairPlan(root,state.sourceId,state.knowledgeRepair.batchId);
  if(!priorPlan)throw Error("Missing original plan");
  const {observedKnowledge:badKnowledge,...unchanged}=event;
  if(contentHash(unchanged)!==contentHash(priorPlan.events[0]))throw Error("Unexpected event changes");
  const priorReceipts=new CompilerFinishReceipts(root,state.sourceId,state.knowledgeRepair.batchId),priorReceipt=await priorReceipts.read();
  if(priorReceipt?.state!=="completed")throw Error("Missing original finish");await priorReceipts.verify(priorReceipt);

  const oldBatch=`reconcile-${state.sourceId}-bounded-codex-target-review-v1-20260912-2`;
  const oldStore=new CompilerFinishReceipts(root,state.sourceId,oldBatch),old=await oldStore.read();
  if(old?.state!=="completed")throw Error("Original batch unfinished.");await oldStore.verify(old);
  const report=old.identity.input.target_reviews?.find(r=>r.target===`event:${event.id}`);
  if(report?.disposition!=="capability-gap"||report.summary!=="The alarm summons high-ranked students, but summons are not a catalog state field. The source says the time is one-thirty after noon without a date or established global ordinal order.")throw Error("Original report changed.");
  const doc=await WorkspaceStore.openReadOnly(root).getSource(state.sourceId);if(!doc)throw Error("Missing source.");
  const bytes=await new SourceMaterialStore().read(doc);if(!bytes)throw Error("Missing immutable bytes.");
  const lines=bytes.toString("utf8").split("\n");
  const exact="路明非站在宿舍过道中。天花板上的红灯闪烁，刺耳的蜂鸣声来自隐藏在墙壁中的扩音器。学生们正从各个楼梯出口向着电梯汇集，有男有女，都穿着校服，神色严肃。卡塞尔学院规模有限，1区宿舍男女混住。";
  if(lines[1983]?.trim()!==exact||!lines[1978]?.includes("门外传来了刺耳的蜂鸣声"))throw Error("Original alarm observation changed");
  if(!event.participants.includes("char-lumingfei")||event.participantPresence?.find(p=>p.entityId==="char-lumingfei")?.mode!=="physical")throw Error("Observer changed");
  const dependencies={claims:await canon.listClaims(),propositions:await canon.listPropositions(),attributions:await canon.listAttributions()};
  const batchId=`reconcile-${state.sourceId}-knowledge-effects-${state.semanticRunId}-21`,reviewPath="run-records/2026-09-11-codex-compile-loop/host-review-alarm-scope-correction.json";
  const review={reviewedAt:new Date().toISOString(),sourceId:state.sourceId,batchId,badEvent,priorPlan,priorReceipt,report,originalFinishFingerprint:old.fingerprint,exact,sourceLines:lines.slice(1978,2001),dependencies,baseline:event,
    finding:"Attempt 36 attached Schneider’s later control-room report (line 1999) to the earlier dormitory alarm (1979-1986). Restore only this incorrectly timed operation through a validated host successor; the original accepted proposal, receipt, plan, dependencies and genuinely later briefing remain intact. Enforce direct observation in the new immutable supplementary plan. Host compared the verbatim original capability-gap report with immutable source lines 1979-1989. A summons state field and global numeric date remain unsupported; do not fabricate either. But source explicitly places Lumingfei in the dormitory corridor hearing the alarm and seeing red lights and students assembling. Existing observed knowledge can record that concrete sensory information using a source-grounded proposition and compatible claim, without inventing entities or world-state fields. Do not equate hearing the buzzer with knowing the alarm's purpose: Fingel's later explanation would require a verified speaker attribution, and this event has only Lumingfei as participant. Limit this supplement to his direct perception. Preserve time ambiguity, every baseline field, original report, proposals, obligations and all publication gates. Prior map supplement committed three physically present observers reading the displayed attribution; exact source says all interfaces showed the map and names Lumingfei's interpretation, supporting those observers. Its remaining audit gaps are not a recurrence of missing knowledge.",
    priorKnowledgeRepair:state.knowledgeRepair,priorAppliedRepair:state.appliedRepair,namespaceUnchanged:state.semanticRunId,validation:"Knowledge scope, quotation trace, normal finish and obligation regression tests and type checks passed before application."};
  await fs.writeFile(new URL("host-review-alarm-scope-correction.json",dir),JSON.stringify(review,null,2),{flag:"wx"});
  const segmentId="a28585b1cf867f3e3a16-00011-80174f0bd7d3",hostBatch=`host-alarm-temporal-correction-${state.sourceId}-v1`;
  const assertions=await new EvidenceAssertionStore(root).listForArtifact("canonical-event",event.id);
  const incorrect=assertions.find(a=>a.target.jsonPointer==="/observedKnowledge/operations/0");
  if(!incorrect||incorrect.anchors.some(a=>a.startLine!==1999))throw Error("Unreviewed knowledge anchor");
  const selectors=assertions.filter(a=>!a.target.jsonPointer.startsWith("/observedKnowledge")).flatMap(a=>a.anchors.map(anchor=>({segment_id:segmentId,exact:bytes.subarray(anchor.startByte,anchor.endByte).toString("utf8"),target_path:a.target.jsonPointer,relation:a.relation,strength:a.strength,...(a.interpretation?{interpretation:a.interpretation}:{})})));
  const tools=createCompilerProposalToolset(root);await tools.beginBatch([],hostBatch,state.sourceId);
  const call=(name:string,input:unknown)=>tools.tools.find(t=>t.name===name)!.execute(name,input as never,undefined,undefined,{} as never);
  const {evidence,...payload}=priorPlan.events[0]!;
  await call("propose_canonical_event",{proposal_id:"event-alarm-temporal-correction-host-v1",payload,evidence_segment_ids:[segmentId],evidence_selectors:selectors});
  await call("finish_compiler_batch",{outcome:"complete",reviewed_segments:[],summary:"Host restores the alarm event before the incorrectly imported later briefing; preserve original evidence, history and all publication gates."});
  const hostReceipts=new CompilerFinishReceipts(root,state.sourceId,hostBatch),hostReceipt=await hostReceipts.read();if(hostReceipt?.state!=="completed")throw Error("Incomplete correction");await hostReceipts.verify(hostReceipt);
  const convergence=await convergeWorldProposals(root,state.sourceId);if(convergence.canonical.blocked.length||convergence.possibilities.blocked.length)throw Error(JSON.stringify(convergence));
  const current=await canon.listEvents();for(const oldEvent of events){if(contentHash(current.find(e=>e.id===oldEvent.id))!==contentHash(oldEvent.id===event.id?priorPlan.events[0]:oldEvent))throw Error("Unexpected change");}
  event=current.find(e=>e.id===event.id)!;
  if(contentHash(await readKnowledgeRepairPlan(root,state.sourceId,state.knowledgeRepair.batchId))!==contentHash(priorPlan))throw Error("Original plan changed");await priorReceipts.verify(priorReceipt);
  await writeKnowledgeRepairPlan(root,{version:1,sourceId:state.sourceId,batchId,predecessorBatchId:oldBatch,predecessorFingerprint:old.fingerprint,reviewRef:reviewPath,events:[event],requireDirectObservation:true});
  const prompt=await buildKnowledgeRepairPrompt(root,state.sourceId,batchId);if(!prompt.includes(event.id))throw Error("Scoped quotation missing from prompt.");
  let gateRetained=false;try{await assertReconciliationDeferralsReviewed(root,state.sourceId);}catch(e){if(String(e).includes("host source review"))gateRetained=true;else throw e;}if(!gateRetained)throw Error("Original deferral gate disappeared.");
  state.knowledgeRepairHistory=[...(state.knowledgeRepairHistory??[]),state.knowledgeRepair];
  state.knowledgeRepair={batchId,pending:true,reviewPath};
  state.appliedRepairHistory=[...(state.appliedRepairHistory??[]),state.appliedRepair];
  state.appliedRepair={repairId:"alarm-direct-observation-scope-v1",failureFingerprint:compilerFailureCauseFingerprint({category:"later-report-imported-into-alarm",targetIds:[event.id],dependencyIds:["attr-schneider-rescue-members-trapped-001"]}),reviewPath,appliedAt:new Date().toISOString(),fingerprintBasis:"Verified attempt 36 temporal misattribution, not aggregate percentages"};
  await fs.writeFile(new URL("state.tmp.json",dir),JSON.stringify(state,null,2));await fs.rename(new URL("state.tmp.json",dir),new URL("state.json",dir));
  console.log(JSON.stringify({ready:true,target:event.id,gateRetained,namespaceUnchanged:true}));
});
