import fs from 'node:fs/promises';
import { CanonicalModelStore } from '../../src/world/canonical-model.js';
import { contentHash } from '../../src/world/canonical.js';
import { WorkspaceStore } from '../../src/storage/workspace-store.js';
import { SourceMaterialStore } from '../../src/storage/source-material-store.js';
import { inspectCompilerStatus } from '../../src/compiler/status.js';
import { CompilerFinishReceipts } from '../../src/compiler/finish-receipts.js';
import { createCompilerProposalToolset } from '../../src/compiler/proposal-tools.js';
import { convergeWorldProposals } from '../../src/compiler/converge.js';
import { assertReconciliationDeferralsReviewed } from '../../src/compiler/reconciliation-review-ledger.js';
import { eventRelationProjectsLegacyCausalParent, validateEventRelationCatalog } from '../../src/world/event-relations.js';
import { compilerFailureCauseFingerprint } from '../../src/runtime/codex-compile-loop.js';
import { withWorkspaceOperationLock } from '../../src/util/workspace-lock.js';
const root=process.cwd(),dir=new URL('./',import.meta.url);
await withWorkspaceOperationLock(root,'compiler',async()=>{
 const state=JSON.parse(await fs.readFile(new URL('state.json',dir),'utf8'));
 if(state.attempt!==43||state.status!=='needs-review'||state.knowledgeRepair.pending)throw Error('Incident changed');
 const status=(await inspectCompilerStatus(root,state.sourceId)).sources[0]!;
 if(status.sourceIntegrity!=='verified'||status.hasUnresolvedObligations||status.worldProposalInventory.pending)throw Error('Unreviewed obligations');
 const canon=new CanonicalModelStore(root),events=await canon.listEvents(),relations=await canon.listEventRelations();
 const prior=relations.find(r=>r.id==='rel-strike-reforms-00009');if(!prior||prior.operationality!=='contributory'||prior.type!=='causes')throw Error('Relation changed');
 const source=await WorkspaceStore.openReadOnly(root).getSource(state.sourceId);if(!source)throw Error('Source missing');const bytes=await new SourceMaterialStore().read(source);if(!bytes)throw Error('Immutable bytes missing');
 const lines=bytes.toString('utf8').split('\n'),strike=lines[1552]!.trim(),reform=lines[1555]!.trim();
 if(!strike.includes('崩碎为一堆金属短棍和满地乱滚的小球')||!reform.startsWith('短棍和小球滚动着汇聚起来，Adams再次成形'))throw Error('Source changed');
 const originalBatch='batch-a28585b1cf867f3e3a16-00009-semantic-87cd9bc1ceb7';
 // Preserve the original source relation and its evidence; normal host proposal finish validates the successor.
 const latestStore=new CompilerFinishReceipts(root,state.sourceId,state.knowledgeRepair.batchId),latestReceipt=await latestStore.read();if(latestReceipt?.state!=='completed')throw Error('Prior supplement unfinished');await latestStore.verify(latestReceipt);
 const next={...prior,type:'enables' as const,operationality:'necessary' as const,mechanism:'This specific reassembly gathers the metal rods and balls produced when Adams was shattered. That fragmented state must exist before those same pieces can reassemble; the strike is not asserted to supply the autonomous repair mechanism.'};
 const batch=`host-adams-fragment-dependency-${state.sourceId}-v1`,reviewPath='run-records/2026-09-11-codex-compile-loop/host-review-adams-causal.json';
 const issues=validateEventRelationCatalog({events:new Map(events.map(e=>[e.id,e])),relations:relations.map(r=>r.id===prior.id?next:r)});
 if(issues.length)throw Error(JSON.stringify(issues));
 await fs.writeFile(new URL('host-review-adams-causal.json',dir),JSON.stringify({reviewedAt:new Date().toISOString(),originalBatch,prior,next,sourceLines:lines.slice(1549,1558),priorState:state,latestReceipt,reason:'The original contributory cause failed to encode that this reassembly requires the fragments from the preceding shattering. Source links the same rods and balls across both passages. Add a necessary enabling dependency, not an assertion that every strike causes repair. No legacy parent, event outcome, checkpoint, proposal history or obligation is removed. Other unsupported dependencies remain blocked.',validation:'Event relation, compiler finish, obligation and compile-loop tests and strict type check passed.'},null,2),{flag:'wx'});
 const tools=createCompilerProposalToolset(root);await tools.beginBatch([],batch,state.sourceId);
 const call=(name:string,input:unknown)=>tools.tools.find(t=>t.name===name)!.execute(name,input as never,undefined,undefined,{} as never);
 const {evidence,...payload}=next,segment='a28585b1cf867f3e3a16-00009-6677e8830ee3';
 const selectors=['/type','/operationality','/mechanism'].flatMap(target_path=>[strike,reform].map(exact=>({segment_id:segment,exact,target_path,relation:'supports',strength:'explicit'})));
 await call('propose_event_relation',{proposal_id:'rel-strike-reforms-host-dependency-v1',payload,evidence_segment_ids:[segment],evidence_selectors:selectors});
 await call('finish_compiler_batch',{outcome:'complete',reviewed_segments:[],summary:'Host source review adds the necessary prior-fragment dependency for this Adams reassembly while preserving original events and history.'});
 const receipts=new CompilerFinishReceipts(root,state.sourceId,batch),receipt=await receipts.read();if(receipt?.state!=='completed')throw Error('Correction unfinished');await receipts.verify(receipt);
 const result=await convergeWorldProposals(root,state.sourceId);if(result.canonical.blocked.length||result.possibilities.blocked.length)throw Error(JSON.stringify(result));
 if(contentHash(await canon.listEvents())!==contentHash(events))throw Error('Events changed');
 const current=await canon.listEventRelations();for(const r of relations)if(contentHash(current.find(c=>c.id===r.id))!==contentHash(r.id===prior.id?next:r))throw Error('Unexpected relation change');
 if(!eventRelationProjectsLegacyCausalParent(current.find(r=>r.id===prior.id)!))throw Error('Dependency missing');
 let gate=false;try{await assertReconciliationDeferralsReviewed(root,state.sourceId);}catch(e){if(String(e).includes('host source review'))gate=true;else throw e;}if(!gate)throw Error('Original review gate lost');
 await latestStore.verify(latestReceipt);
 state.appliedRepairHistory.push(state.appliedRepair);state.appliedRepair={repairId:'adams-fragment-required-before-reassembly-v1',failureFingerprint:compilerFailureCauseFingerprint({category:'missing-necessary-fragment-dependency',targetIds:[prior.toEventId],dependencyIds:[prior.id]}),reviewPath,appliedAt:new Date().toISOString()};
 await fs.writeFile(new URL('host-review-adams-causal-result.json',dir),JSON.stringify({receipt:receipt.fingerprint,gateRetained:gate,eventsUnchanged:true}));
 await fs.writeFile(new URL('state.tmp.json',dir),JSON.stringify(state,null,2));await fs.rename(new URL('state.tmp.json',dir),new URL('state.json',dir));
 console.log(JSON.stringify({ready:true,receipt:receipt.fingerprint,gateRetained:gate}));
});
