import fs from 'node:fs/promises';
import { CanonicalModelStore } from '../../src/world/canonical-model.js';
import { ActorModelStore, characterGoalSchema, evaluateCharacterGoal } from '../../src/world/actors.js';
import { worldStorageRoot } from '../../src/world/paths.js';
import { contentHash } from '../../src/world/canonical.js';
import { WorkspaceStore } from '../../src/storage/workspace-store.js';
import { SourceMaterialStore } from '../../src/storage/source-material-store.js';
import { inspectCompilerStatus } from '../../src/compiler/status.js';
import { CompilerFinishReceipts } from '../../src/compiler/finish-receipts.js';
import { createCompilerProposalToolset } from '../../src/compiler/proposal-tools.js';
import { convergeWorldProposals } from '../../src/compiler/converge.js';
import { assertReconciliationDeferralsReviewed } from '../../src/compiler/reconciliation-review-ledger.js';
import { compilerFailureCauseFingerprint } from '../../src/runtime/codex-compile-loop.js';
import { withWorkspaceOperationLock } from '../../src/util/workspace-lock.js';
const root=process.cwd(),dir=new URL('./',import.meta.url);
await withWorkspaceOperationLock(root,'compiler',async()=>{
 const state=JSON.parse(await fs.readFile(new URL('state.json',dir),'utf8'));
 if(state.attempt!==65||state.status!=='needs-review'||state.knowledgeRepair.pending)throw Error('Incident changed');
 const status=(await inspectCompilerStatus(root,state.sourceId)).sources[0]!;
 if(status.sourceIntegrity!=='verified'||status.hasUnresolvedObligations||status.worldProposalInventory.pending)throw Error('Unreviewed obligations');
 const canon=new CanonicalModelStore(root),actors=new ActorModelStore(root),events=await canon.listEvents(),goals=await actors.listGoals(),models=await actors.listModels();
 const invitation=events.find(e=>e.id==='event-gear-jam-001');if(!invitation||!invitation.participants.includes('char-yesheng'))throw Error('Invitation changed');
 if(!goals.some(g=>g.id==='goal-yaji-retreat-bronze-city-00011'))throw Error('Prior targeted failure recurred; stop');
 const originalBatch=`reconcile-${state.sourceId}-bounded-codex-target-review-v1-20260912-1`;
 const predecessor=new CompilerFinishReceipts(root,state.sourceId,originalBatch),old=await predecessor.read();if(old?.state!=='completed')throw Error('Original finish missing');await predecessor.verify(old);
 const report=old.identity.input.target_reviews?.find(r=>r.target==='character:char-jiudeyaji');
 if(report?.disposition!=='unsupported'||report.summary!=='The current model is already character-v1. The source establishes her interview role but no bounded psychological development or executable opening driver for this later character.')throw Error('Original report changed');
 const ledgerDir=worldStorageRoot(root)+'/compiler/reconciliation-reviews/'+state.sourceId,ledgers=[];for(const file of await fs.readdir(ledgerDir)){const l=JSON.parse(await fs.readFile(ledgerDir+'/'+file,'utf8'));const results=l.results?.filter((r:{target:string})=>['character:char-jiudeyaji','character:char-yesheng','event:event-gear-jam-001'].includes(r.target));if(results?.length)ledgers.push({file,results});}if(!ledgers.length)throw Error('Target ledger missing');
 const source=await WorkspaceStore.openReadOnly(root).getSource(state.sourceId);if(!source)throw Error('Source missing');const bytes=await new SourceMaterialStore().read(source);if(!bytes)throw Error('Immutable source missing');const lines=bytes.toString('utf8').split('\n');
 const quote=lines[1952]!.trim(),context=lines[1949]!.trim();if(!quote.includes('必须尽快撤离，这是叶胜的直觉')||!context.includes('叶胜和亚纪看向四周'))throw Error('Source changed');
 const goal=characterGoalSchema.parse({id:'goal-yesheng-retreat-bronze-city-00011',actorId:'char-yesheng',description:'在亲见青铜城机关启动后的危机阶段，争取尽快撤离青铜城。撤离意图不等于已经发现安全出口，也不保证撤离成功。',priority:0.5,requiresKnowledge:[],targetIds:['loc-bronze-city-00010'],activation:{preconditions:[],afterCanonicalEventIds:['event-gears-activate-001']},evidence:invitation.evidence});
 if(goals.some(g=>g.id===goal.id))throw Error('Goal already exists; inspect original scope instead of retrying');
 const evaluationState={atCommit:'host-review',logicalTime:{step:0},values:{},activeRuleIds:[]};
 const dormant=evaluateCharacterGoal(goal,{state:evaluationState,knownClaimIds:new Set(),realizedCanonicalEventIds:new Set()});
 const activated=evaluateCharacterGoal(goal,{state:evaluationState,knownClaimIds:new Set(),realizedCanonicalEventIds:new Set(['event-gears-activate-001',invitation.id])});
 if(dormant.active||!activated.active)throw Error('Invitation activation boundary failed');
 const batch=`host-yesheng-retreat-goal-${state.sourceId}-v1`,reviewPath='run-records/2026-09-11-codex-compile-loop/host-review-yesheng-retreat-goal.json';
 await fs.writeFile(new URL('host-review-yesheng-retreat-goal.json',dir),JSON.stringify({reviewedAt:new Date().toISOString(),priorState:state,originalBatch,originalReceipt:old.fingerprint,report,ledgers,invitation,proposal:goal,sourceLines:lines.slice(1948,1956),reason:'Host searched all per-target ledgers for Ye Sheng and the gear-jam event and found no corresponding model deferral. Preserve and verify the original Yaji companion report as history, without relabeling it as a Ye Sheng report. The previous companion repair is present. Immutable source lines 1949-1956 independently and explicitly narrate Ye Shengs urgent retreat intention after he observes the gears start. Add this source-stated goal only after gear activation is realized. Do not invent exit routes, rescue outcomes, private knowledge, numeric psychological intensity or force later canon. Neutral priority is policy ranking. Existing models, events, knowledge, goals, reports, receipts and publication gates remain intact.',validation:'Goal activation and development, compiler finish, proposal obligation and loop regressions; normal typed proposal, evidence validation, convergence and immutable predecessor verification.'},null,2),{flag:'wx'});
 const toolset=createCompilerProposalToolset(root);await toolset.beginBatch([],batch,state.sourceId);
 const call=(name:string,input:unknown)=>toolset.tools.find(t=>t.name===name)!.execute(name,input as never,undefined,undefined,{} as never);
 const {evidence,...payload}=goal,segment='a28585b1cf867f3e3a16-00011-80174f0bd7d3';
 await call('propose_character_goal',{proposal_id:'goal-yesheng-retreat-bronze-city-host-v1',payload,evidence_segment_ids:[segment],evidence_selectors:['/description','/actorId','/targetIds','/activation'].flatMap(target_path=>[context,quote].map(exact=>({segment_id:segment,exact,target_path,relation:'supports',strength:'strong-inference',interpretation:'Narrator explicitly states Ye Sheng immediate retreat intention after he observes gears activate. No guaranteed escape, exit route or knowledge mutation.'}))) });
 await call('finish_compiler_batch',{outcome:'complete',reviewed_segments:[],summary:'Host source-reviewed explicit retreat goal for Ye Sheng, activated after gear crisis; no world-state or knowledge mutations.'});
 const receipts=new CompilerFinishReceipts(root,state.sourceId,batch),receipt=await receipts.read();if(receipt?.state!=='completed')throw Error('Finish incomplete');await receipts.verify(receipt);
 const result=await convergeWorldProposals(root,state.sourceId);if(result.canonical.blocked.length||result.possibilities.blocked.length)throw Error(JSON.stringify(result));
 const current=await actors.listGoals();if(current.length!==goals.length+1||contentHash(current.find(g=>g.id===goal.id))!==contentHash(goal))throw Error('Unexpected goal result');
 for(const oldGoal of goals)if(contentHash(current.find(g=>g.id===oldGoal.id))!==contentHash(oldGoal))throw Error('Existing goal changed');
 if(contentHash(await canon.listEvents())!==contentHash(events)||contentHash(await actors.listModels())!==contentHash(models))throw Error('Unrelated world/model changes');
 await predecessor.verify(old);
 let gate=false;try{await assertReconciliationDeferralsReviewed(root,state.sourceId);}catch(e){if(String(e).includes('host source review'))gate=true;else throw e;}if(!gate)throw Error('Original review gate lost');
 state.appliedRepairHistory.push(state.appliedRepair);state.appliedRepair={repairId:'yesheng-source-reviewed-retreat-goal-v1',failureFingerprint:compilerFailureCauseFingerprint({category:'source-crisis-retreat-goal-omitted',targetIds:['char-yesheng'],dependencyIds:['event-gears-activate-001']}),reviewPath,appliedAt:new Date().toISOString()};
 await fs.writeFile(new URL('host-review-yesheng-retreat-goal-result.json',dir),JSON.stringify({receipt:receipt.fingerprint,gateRetained:gate,existingEventsModelsGoalsUnchanged:true}));
 await fs.writeFile(new URL('state.tmp.json',dir),JSON.stringify(state,null,2));await fs.rename(new URL('state.tmp.json',dir),new URL('state.json',dir));console.log(JSON.stringify({ready:true,receipt:receipt.fingerprint,gateRetained:gate}));
});
