import fs from 'node:fs/promises';
import { CanonicalModelStore } from '../../src/world/canonical-model.js';
import { characterEntryCheckpointSchema } from '../../src/world/model.js';
import { worldStorageRoot } from '../../src/world/paths.js';
import { contentHash } from '../../src/world/canonical.js';
import { WorkspaceStore } from '../../src/storage/workspace-store.js';
import { SourceMaterialStore } from '../../src/storage/source-material-store.js';
import { inspectCompilerStatus } from '../../src/compiler/status.js';
import { CompilerFinishReceipts } from '../../src/compiler/finish-receipts.js';
import { EvidenceAssertionStore } from '../../src/compiler/evidence-assertions.js';
import { createCompilerProposalToolset } from '../../src/compiler/proposal-tools.js';
import { convergeWorldProposals } from '../../src/compiler/converge.js';
import { assertReconciliationDeferralsReviewed } from '../../src/compiler/reconciliation-review-ledger.js';
import { compilerFailureCauseFingerprint } from '../../src/runtime/codex-compile-loop.js';
import { withWorkspaceOperationLock } from '../../src/util/workspace-lock.js';
const root=process.cwd(),dir=new URL('./',import.meta.url);
await withWorkspaceOperationLock(root,'compiler',async()=>{
 const state=JSON.parse(await fs.readFile(new URL('state.json',dir),'utf8'));
 if(state.attempt!==67||state.status!=='needs-review'||state.knowledgeRepair.pending)throw Error('Incident changed');
 const status=(await inspectCompilerStatus(root,state.sourceId)).sources[0]!;
 if(status.sourceIntegrity!=='verified'||status.hasUnresolvedObligations||status.worldProposalInventory.pending)throw Error('Unreviewed obligations');
 const canon=new CanonicalModelStore(root),events=await canon.listEvents();
 const event=events.find(e=>e.id==='event-zhao-confession-00004');if(!event||event.characterEntryCheckpoints?.length!==1||event.characterEntryCheckpoints[0]?.actorId!=='char-zhaomenghua')throw Error('Entry target changed');
 if(!events.find(e=>e.id==='event-laotang-coaching-00003')?.characterEntryCheckpoints?.some(c=>c.actorId==='char-lumingze'))throw Error('Prior targeted failure recurred; stop');
 const entities=await canon.listEntities();const location={id:'loc-cinema-screening-room-00004',kind:'location' as const,canonicalName:'放映厅',aliases:[]};if(entities.some(e=>e.id===location.id||e.canonicalName===location.canonicalName))throw Error('Location already exists');
 const sorted=events.slice().sort((a,b)=>Math.min(...a.evidence.map(r=>r.span.startLine))-Math.min(...b.evidence.map(r=>r.span.startLine))||(a.narrativeContext?.discourseOrder??0)-(b.narrativeContext?.discourseOrder??0)||a.id.localeCompare(b.id));
 for(const actor of ['char-chendouwen','char-suxiaoqiang'])if(sorted.find(e=>(!e.narrativeContext||e.narrativeContext.mode==='scene')&&e.participantPresence?.some(p=>p.entityId===actor&&p.mode==='physical'))?.id!==event.id)throw Error('First-entry target changed');
 const originalBatch=`reconcile-${state.sourceId}-bounded-codex-target-review-v1-20260912-1`,predecessor=new CompilerFinishReceipts(root,state.sourceId,originalBatch),old=await predecessor.read();if(old?.state!=='completed')throw Error('Original finish missing');await predecessor.verify(old);
 const reports=old.identity.input.target_reviews?.filter(r=>['event:event-zhao-confession-00004'].includes(r.target));if(reports?.length!==1||reports.some(r=>r.disposition!=='unsupported'))throw Error('Original reports changed');
 const ledgerDir=worldStorageRoot(root)+'/compiler/reconciliation-reviews/'+state.sourceId;
 const ledgers=[];for(const file of await fs.readdir(ledgerDir)){const ledger=JSON.parse(await fs.readFile(ledgerDir+'/'+file,'utf8'));const results=ledger.results?.filter((r:{target:string})=>r.target==='event:event-zhao-confession-00004');if(results?.length)ledgers.push({file,finishFingerprint:ledger.finishFingerprint,results});}if(!ledgers.length)throw Error('Original target ledger missing');
 const source=await WorkspaceStore.openReadOnly(root).getSource(state.sourceId);if(!source)throw Error('Source missing');const bytes=await new SourceMaterialStore().read(source);if(!bytes)throw Error('Immutable source missing');const lines=bytes.toString('utf8').split('\n');
 const exact=(needle:string)=>{const matches=lines.slice(650,662).filter(l=>l.includes(needle));if(matches.length!==1)throw Error('Anchor not unique');return matches[0]!.trim();};
 const room=exact('路明非走进放映厅，苏晓樯的声音'),chen=exact('陈雯雯冲他微微点头'),audience=exact('各自占据位置正在喝可乐吃爆米花');
 const checkpoints=[...event.characterEntryCheckpoints,...['char-chendouwen','char-suxiaoqiang'].map(actorId=>characterEntryCheckpointSchema.parse({actorId,readerSetup:'文学社电影聚会中，陈雯雯和苏晓樯已在放映厅内。这里停在投影表白环节开始之前，赵孟华尚未公开告白，陈雯雯尚未回应。',actorObservation:'你在文学社电影聚会的放映厅里。',participantPresence:[{entityId:actorId,mode:'physical'}],delta:{version:1,operations:[{op:'set',entityId:actorId,field:'character.location',value:location.id}]}}))];
 const next={...event,characterEntryCheckpoints:checkpoints};
 const batch=`host-cinema-audience-entry-${state.sourceId}-v1`,reviewPath='run-records/2026-09-11-codex-compile-loop/host-review-cinema-audience-entry-checkpoints.json';
 await fs.writeFile(new URL('host-review-cinema-audience-entry-checkpoints.json',dir),JSON.stringify({reviewedAt:new Date().toISOString(),priorState:state,originalBatch,originalReceipt:old.fingerprint,reports,ledgers,original:event,next,location,sourceQuotes:{room,chen,audience},reason:'Host reviewed the original unsupported confession report and later accepted knowledge ledger against immutable source lines 651-662. Su speaks as Lumingfei enters the screening room; Chen responds to his glance before the projection starts. Both are explicitly present in that same room. Add the source-exact screening-room entity with an exact nominal mention and validated resolution, then append only location checkpoints for Chen and Su. Preserve Zhao existing checkpoint and Chen post-confession attributed knowledge. Do not seed either girls private intentions, advance awareness of the surprise, acceptance, tears or inferred emotions. All original fields, source anchors, reports, receipts and publication gates remain intact.',validation:'Character entry, entry-context, compiler finish/obligation and loop regressions plus strict type check and normal schema/evidence/commit verification.'},null,2),{flag:'wx'});
 const toolset=createCompilerProposalToolset(root);await toolset.beginBatch([],batch,state.sourceId);const call=(name:string,input:unknown)=>toolset.tools.find(t=>t.name===name)!.execute(name,input as never,undefined,undefined,{} as never);
 const segment='a28585b1cf867f3e3a16-00004-f50b153c1580';
 await call('propose_entity',{proposal_id:'entity-cinema-screening-room-host-v1',payload:location,evidence_segment_ids:[segment],evidence_selectors:['/canonicalName','/kind'].map(target_path=>({segment_id:segment,exact:room,target_path,relation:'supports',strength:'explicit'}))});
 const mention='em-cinema-screening-room-host-v1';
 await call('propose_entity_mention',{proposal_id:mention,annotation_id:mention,selector:{segment_id:segment,exact:'放映厅',prefix:'路明非走进'},surface:'放映厅',form:'nominal',kind_candidates:['location'],confidence:1});
 await call('propose_entity_resolution',{proposal_id:'res-cinema-screening-room-host-v1',resolution_id:'res-cinema-screening-room-host-v1',mention_id:mention,status:'new-entity',entity_id:location.id,candidates:[{entity_id:location.id,confidence:1,basis_mention_ids:[mention],evidence_assertion_ids:[],rationale:'Exact named room in the literary society cinema gathering; no existing screening-room entity found.'}],rationale:'Host source-reviewed stable location for the pre-confession gathering.'});
 const assertions=await new EvidenceAssertionStore(root).listForArtifact('canonical-event',event.id);
 const selectors=assertions.flatMap(a=>a.anchors.map(anchor=>{
  const exact=bytes.subarray(anchor.startByte,anchor.endByte).toString('utf8'),needle=Buffer.from(exact),hits:number[]=[];
  for(let offset=54279;offset<103369;){const at=bytes.indexOf(needle,offset);if(at<0||at+needle.length>103369)break;hits.push(at);offset=at+1;}
  const occurrence=hits.indexOf(anchor.startByte)+1;if(!occurrence)throw Error('Original evidence outside reviewed segment');
  return {segment_id:segment,exact,...(hits.length>1?{occurrence}:{}),target_path:a.target.jsonPointer,relation:a.relation,strength:a.strength,...(a.interpretation?{interpretation:a.interpretation}:{})};
 }));
 for(let index=event.characterEntryCheckpoints.length;index<checkpoints.length;index++)for(const field of ['readerSetup','actorObservation','participantPresence','delta'])for(const quote of [room,chen,audience])selectors.push({segment_id:segment,exact:quote,target_path:`/characterEntryCheckpoints/${index}/${field}`,relation:'supports',strength:'strong-inference',interpretation:'Both girls are present in the screening room before projection and confession. Location only; no future response or private motive.'});
 const {evidence,...payload}=next;await call('propose_canonical_event',{proposal_id:'event-cinema-audience-host-checkpoints-v1',payload,evidence_segment_ids:[segment],evidence_selectors:selectors});
 await call('finish_compiler_batch',{outcome:'complete',reviewed_segments:[],summary:'Source-reviewed screening room and pre-confession location checkpoints for Chen and Su; Zhao checkpoint and later knowledge unchanged.'});
 const receipts=new CompilerFinishReceipts(root,state.sourceId,batch),receipt=await receipts.read();if(receipt?.state!=='completed')throw Error('Finish incomplete');await receipts.verify(receipt);
 const result=await convergeWorldProposals(root,state.sourceId);if(result.canonical.blocked.length||result.possibilities.blocked.length)throw Error(JSON.stringify(result));
 const current=await canon.listEvents();for(const e of events)if(contentHash(current.find(c=>c.id===e.id))!==contentHash(e.id===event.id?next:e))throw Error('Unexpected event change');
 const updatedEntities=await canon.listEntities();if(updatedEntities.length!==entities.length+1||!updatedEntities.some(e=>e.id===location.id&&e.kind==='location'&&e.canonicalName===location.canonicalName))throw Error('Location commit missing');for(const e of entities)if(contentHash(updatedEntities.find(c=>c.id===e.id))!==contentHash(e))throw Error('Existing entity changed');
 await predecessor.verify(old);
 let gate=false;try{await assertReconciliationDeferralsReviewed(root,state.sourceId);}catch(e){if(String(e).includes('host source review'))gate=true;else throw e;}if(!gate)throw Error('Original review gate lost');
 state.appliedRepairHistory.push(state.appliedRepair);state.appliedRepair={repairId:'cinema-audience-source-reviewed-location-checkpoints-v1',failureFingerprint:compilerFailureCauseFingerprint({category:'missing-source-backed-cinema-audience-entry',targetIds:['char-chendouwen','char-suxiaoqiang'],dependencyIds:[event.id]}),reviewPath,appliedAt:new Date().toISOString()};
 await fs.writeFile(new URL('host-review-cinema-audience-entry-checkpoints-result.json',dir),JSON.stringify({receipt:receipt.fingerprint,gateRetained:gate,onlyEntryCheckpointAdded:true}));
 await fs.writeFile(new URL('state.tmp.json',dir),JSON.stringify(state,null,2));await fs.rename(new URL('state.tmp.json',dir),new URL('state.json',dir));console.log(JSON.stringify({ready:true,receipt:receipt.fingerprint,gateRetained:gate}));
});
