import fs from 'node:fs/promises';
import { CanonicalModelStore } from '../../src/world/canonical-model.js';
import { characterEntryCheckpointSchema } from '../../src/world/model.js';
import { contentHash } from '../../src/world/canonical.js';
import { WorkspaceStore } from '../../src/storage/workspace-store.js';
import { SourceMaterialStore } from '../../src/storage/source-material-store.js';
import { inspectCompilerStatus } from '../../src/compiler/status.js';
import { CompilerFinishReceipts } from '../../src/compiler/finish-receipts.js';
import { EvidenceAssertionStore } from '../../src/compiler/evidence-assertions.js';
import { createCompilerProposalToolset } from '../../src/compiler/proposal-tools.js';
import { convergeWorldProposals } from '../../src/compiler/converge.js';
import { assertReconciliationDeferralsReviewed } from '../../src/compiler/reconciliation-review-ledger.js';
import { compilerFailureCauseFingerprint } from '../../src/runtime/codex-compile-loop.js';
import { withWorkspaceOperationLock } from '../../src/util/workspace-lock.js';
const root=process.cwd(),dir=new URL('./',import.meta.url);
await withWorkspaceOperationLock(root,'compiler',async()=>{
 const state=JSON.parse(await fs.readFile(new URL('state.json',dir),'utf8'));
 if(state.attempt!==51||state.status!=='needs-review'||state.knowledgeRepair.pending)throw Error('Incident changed');
 const status=(await inspectCompilerStatus(root,state.sourceId)).sources[0]!;
 if(status.sourceIntegrity!=='verified'||status.hasUnresolvedObligations||status.worldProposalInventory.pending)throw Error('Unreviewed obligations');
 const canon=new CanonicalModelStore(root),events=await canon.listEvents();
 const event=events.find(e=>e.id==='event-lumingfei-interview-00003');if(!event||event.characterEntryCheckpoints?.length)throw Error('Entry target changed');
 const sorted=events.slice().sort((a,b)=>Math.min(...a.evidence.map(r=>r.span.startLine))-Math.min(...b.evidence.map(r=>r.span.startLine))||(a.narrativeContext?.discourseOrder??0)-(b.narrativeContext?.discourseOrder??0)||a.id.localeCompare(b.id));
 for(const actor of ['char-yesheng','char-jiudeyaji'])if(sorted.find(e=>(!e.narrativeContext||e.narrativeContext.mode==='scene')&&e.participantPresence?.some(p=>p.entityId===actor&&p.mode==='physical'))?.id!==event.id)throw Error('First-entry target changed');
 const originalBatch=`reconcile-${state.sourceId}-bounded-codex-target-review-v1-20260912-1`,predecessor=new CompilerFinishReceipts(root,state.sourceId,originalBatch),old=await predecessor.read();if(old?.state!=='completed')throw Error('Original finish missing');await predecessor.verify(old);
 const reports=old.identity.input.target_reviews?.filter(r=>['event:event-lumingfei-interview-00003'].includes(r.target));if(reports?.length!==1||reports.some(r=>r.disposition!=='unsupported'))throw Error('Original reports changed');
 const source=await WorkspaceStore.openReadOnly(root).getSource(state.sourceId);if(!source)throw Error('Source missing');const bytes=await new SourceMaterialStore().read(source);if(!bytes)throw Error('Immutable source missing');const lines=bytes.toString('utf8').split('\n');
 const exact=(needle:string)=>{const matches=lines.slice(217,265).filter(l=>l.includes(needle));if(matches.length!==1)throw Error('Anchor not unique');return matches[0]!.trim();};
 const examiner=exact('我是考官叶胜，请跟我来。'),callNext=exact('路明非，下一个是你。'),room=exact('他跟着叶胜进了会议室。'),yaji=exact('我叫酒德亚纪，也是这次的考官。');
 const checkpoints=[
  {actorId:'char-yesheng',actorObservation:'你在会议室门口招呼下一名考生路明非，准备带他进来。',plan:'继续担任考官，为路明非进行学院面试'},
  {actorId:'char-jiudeyaji',actorObservation:'你坐在会议室的大型会议桌旁，准备继续担任这次面试的考官。',plan:'继续担任学院面试的考官'},
 ].map(({actorId,actorObservation,plan})=>characterEntryCheckpointSchema.parse({actorId,readerSetup:'此前已有考生依次进出会议室，现在轮到路明非。叶胜在门口叫他，酒德亚纪已在会议室桌边。检查点位于路明非进门、正式接受本轮问答之前。',actorObservation,participantPresence:[{entityId:'char-yesheng',mode:'physical'},{entityId:'char-jiudeyaji',mode:'physical'}],delta:{version:1,operations:[{op:'set',entityId:actorId,field:'character.plan',value:plan}]}}));
 const next={...event,characterEntryCheckpoints:checkpoints};
 const batch=`host-interview-pre-entry-${state.sourceId}-v1`,reviewPath='run-records/2026-09-11-codex-compile-loop/host-review-interview-entry-checkpoints.json';
 await fs.writeFile(new URL('host-review-interview-entry-checkpoints.json',dir),JSON.stringify({reviewedAt:new Date().toISOString(),priorState:state,originalBatch,originalReceipt:old.fingerprint,reports,original:event,next,sourceQuotes:{examiner,callNext,room,yaji},reason:'Host compared the exact unsupported report with immutable source. Lack of numeric event effects does not preclude source-grounded pre-entry plans: Ye Sheng explicitly identifies himself as examiner, calls prior candidates and calls Lumingfei next; Yaji is already seated at the table when Lumingfei enters and identifies herself as the other examiner. Her preexisting role and seating are supported without importing her later questions or their result. Set each own plan to conduct the examination, with pre-entry physical presence and limited observations. No assessment result, secret selection criteria, hidden institutional knowledge, future event outcome, location entity or resource quantity is fabricated. The first modeled embodied entry remains this event. Preserve every baseline event field, original report and all publication gates. Prior duel checkpoints succeeded; their aggregate percentage is not a failure identity.',validation:'Character entry, entry-context, compiler finish/obligation and loop regressions plus strict type check and normal schema/evidence/commit verification.'},null,2),{flag:'wx'});
 const toolset=createCompilerProposalToolset(root);await toolset.beginBatch([],batch,state.sourceId);const call=(name:string,input:unknown)=>toolset.tools.find(t=>t.name===name)!.execute(name,input as never,undefined,undefined,{} as never);
 const segment='a28585b1cf867f3e3a16-00003-5c70d7864d11';
 const assertions=await new EvidenceAssertionStore(root).listForArtifact('canonical-event',event.id);
 const selectors=assertions.flatMap(a=>a.anchors.map(anchor=>({segment_id:segment,exact:bytes.subarray(anchor.startByte,anchor.endByte).toString('utf8'),target_path:a.target.jsonPointer,relation:a.relation,strength:a.strength,...(a.interpretation?{interpretation:a.interpretation}:{})})));
 for(let index=0;index<checkpoints.length;index++)for(const field of ['readerSetup','actorObservation','participantPresence','delta'])for(const quote of [examiner,callNext,room,yaji])selectors.push({segment_id:segment,exact:quote,target_path:`/characterEntryCheckpoints/${index}/${field}`,relation:'supports',strength:'strong-inference',interpretation:'Before Lumingfei enters for his interview: examiner roles and seating already exist. Do not import subsequent questions, answers or selection outcomes.'});
 const {evidence,...payload}=next;await call('propose_canonical_event',{proposal_id:'event-interview-host-checkpoints-v1',payload,evidence_segment_ids:[segment],evidence_selectors:selectors});
 await call('finish_compiler_batch',{outcome:'complete',reviewed_segments:[],summary:'Source-reviewed examiner checkpoints for Ye Sheng and Yaji before Lumingfei enters; only preexisting examination plans are added.'});
 const receipts=new CompilerFinishReceipts(root,state.sourceId,batch),receipt=await receipts.read();if(receipt?.state!=='completed')throw Error('Finish incomplete');await receipts.verify(receipt);
 const result=await convergeWorldProposals(root,state.sourceId);if(result.canonical.blocked.length||result.possibilities.blocked.length)throw Error(JSON.stringify(result));
 const current=await canon.listEvents();for(const e of events)if(contentHash(current.find(c=>c.id===e.id))!==contentHash(e.id===event.id?next:e))throw Error('Unexpected event change');
 await predecessor.verify(old);
 let gate=false;try{await assertReconciliationDeferralsReviewed(root,state.sourceId);}catch(e){if(String(e).includes('host source review'))gate=true;else throw e;}if(!gate)throw Error('Original review gate lost');
 state.appliedRepairHistory.push(state.appliedRepair);state.appliedRepair={repairId:'interview-source-reviewed-examiner-checkpoints-v1',failureFingerprint:compilerFailureCauseFingerprint({category:'missing-source-backed-examiner-entry',targetIds:['char-yesheng','char-jiudeyaji'],dependencyIds:[event.id]}),reviewPath,appliedAt:new Date().toISOString()};
 await fs.writeFile(new URL('host-review-interview-entry-checkpoints-result.json',dir),JSON.stringify({receipt:receipt.fingerprint,gateRetained:gate,onlyEntryCheckpointAdded:true}));
 await fs.writeFile(new URL('state.tmp.json',dir),JSON.stringify(state,null,2));await fs.rename(new URL('state.tmp.json',dir),new URL('state.json',dir));console.log(JSON.stringify({ready:true,receipt:receipt.fingerprint,gateRetained:gate}));
});
