import fs from "node:fs/promises";
import { WorkspaceStore } from "../../src/storage/workspace-store.js";
import { SourceMaterialStore } from "../../src/storage/source-material-store.js";
import { CanonicalModelStore } from "../../src/world/canonical-model.js";
import { SourceAnnotationStore } from "../../src/compiler/annotations.js";
import { EntityResolutionStore } from "../../src/compiler/entity-resolution.js";
import { inspectCompilerStatus } from "../../src/compiler/status.js";
import { CompilerFinishReceipts } from "../../src/compiler/finish-receipts.js";
import { createCompilerProposalToolset } from "../../src/compiler/proposal-tools.js";
import { writeKnowledgeRepairPlan, buildKnowledgeRepairPrompt } from "../../src/compiler/knowledge-repair.js";
import { assertReconciliationDeferralsReviewed } from "../../src/compiler/reconciliation-review-ledger.js";
import { validateCommittedAttributionTrace } from "../../src/compiler/attribution-trace.js";
import { contentHash } from "../../src/world/canonical.js";
import { compilerFailureFingerprint } from "../../src/runtime/codex-compile-loop.js";
import { withWorkspaceOperationLock } from "../../src/util/workspace-lock.js";
const root=process.cwd(),dir=new URL("./",import.meta.url);
await withWorkspaceOperationLock(root,"compiler",async()=>{
  const state=JSON.parse(await fs.readFile(new URL("state.json",dir),"utf8"));
  if(state.attempt!==27||state.status!=="needs-review"||state.knowledgeRepair.pending)throw Error("Incident changed.");
  const source=(await inspectCompilerStatus(root,state.sourceId)).sources.find(s=>s.sourceId===state.sourceId)!;
  if(source.sourceIntegrity!=="verified"||source.hasUnresolvedObligations||source.worldProposalInventory.pending)throw Error("Unreviewed source or obligations.");
  const canon=new CanonicalModelStore(root), annotations=new SourceAnnotationStore(root);
  for(const a of await canon.listAttributions())if((await validateCommittedAttributionTrace(root,state.sourceId,a)).length)throw Error("Prior trace repair has not passed.");
  const events=await canon.listEvents(),event=events.find(e=>e.id==="event-lumingfei-emergency-signal-00021")!;
  if(!event||event.observedKnowledge?.operations.length||event.observedOutcome.operations.length)throw Error("Target changed.");
  const oldBatch=`reconcile-${state.sourceId}-bounded-codex-target-review-v1-20260912-4`;
  const oldStore=new CompilerFinishReceipts(root,state.sourceId,oldBatch),old=await oldStore.read();
  if(old?.state!=="completed")throw Error("Original batch unfinished.");await oldStore.verify(old);
  const report=old.identity.input.target_reviews?.find(r=>r.target===`event:${event.id}`);
  if(report?.disposition!=="capability-gap"||report.summary!=="The source explicitly shows Lumingfei invoking Black Sheep Wall, contacting Fingel, and asking for the map. The information outcome cannot be added as a knowledge delta without a compatible source-grounded claim/proposition, and no deterministic state-field effect is stated by the event.")throw Error("Original report changed.");
  const doc=await WorkspaceStore.openReadOnly(root).getSource(state.sourceId);if(!doc)throw Error("Missing source.");
  const bytes=await new SourceMaterialStore().read(doc);if(!bytes)throw Error("Missing immutable bytes.");
  const lines=bytes.toString("utf8").split("\n");
  const exact="芬格尔！快把以前那份地图调出来！找出现在的位置！我们迷路了，在龙王家里迷路了！";
  if(!lines[4458]?.includes(`“${exact}”路明非`)||!lines[4459]?.includes('芬格尔在校园新闻网'))throw Error("Original call and response changed");
  const speaker="m_lu_mingfei",listener="m_fingel",quoteId="q-lumingfei-emergency-map-00021",segmentId="a28585b1cf867f3e3a16-00021-0343cf842992";
  const mappings=await new EntityResolutionStore(root).list(state.sourceId);
  if(!mappings.some(r=>r.mentionId===speaker&&r.entityId==="char-lumingfei")||mappings.some(r=>r.mentionId===listener))throw Error("Identity trace changed");
  const annotationBefore=await annotations.list(state.sourceId);
  const mention=annotationBefore.find(a=>a.id===listener);if(!mention||mention.annotationType!=="entity-mention"||mention.surface!=="芬格尔"||mention.anchor.startLine!==4442)throw Error("Listener source mention changed");
  if(!(await canon.listEntities()).some(e=>e.id==="char-fingel"&&e.canonicalName==="芬格尔·冯·弗林斯"))throw Error("Listener identity changed");
  if(annotationBefore.some(a=>a.id===quoteId))throw Error("Quotation already reviewed");
  const dependencies={claims:await canon.listClaims(),propositions:await canon.listPropositions(),attributions:await canon.listAttributions()};
  const batchId=`reconcile-${state.sourceId}-knowledge-effects-${state.semanticRunId}-14`,reviewPath="run-records/2026-09-11-codex-compile-loop/host-review-emergency-knowledge.json";
  const review={reviewedAt:new Date().toISOString(),sourceId:state.sourceId,batchId,report,originalFinishFingerprint:old.fingerprint,exact,sourceLines:lines.slice(4439,4465),mappings:mappings.filter(r=>[speaker,listener].includes(r.mentionId)),dependencies,baseline:event,
    finding:"Host reviewed the original capability-gap report and full emergency exchange. Lumingfei explicitly tells Fingel they are lost in the dragon king's home and requests the prior map; Fingel answers that he needs to print. The source already records Fingel waiting at his computer and responding through the microphone. Resolve the existing unbound literal Fingel mention to the established canonical character, then add the exact spoken report. Permit only Fingel hearing this reported location predicament via told acquisition and required claim/proposition/attribution dependencies. No magical ability, map ownership, completed localization, rescue outcome, numeric state, or checkpoint is asserted; preserve every baseline event field and original deferral.",
    priorKnowledgeRepair:state.knowledgeRepair,priorAppliedRepair:state.appliedRepair,namespaceUnchanged:state.semanticRunId,validation:"Knowledge scope, quotation trace, normal finish and obligation regression tests and type checks passed before application."};
  await fs.writeFile(new URL("host-review-emergency-knowledge.json",dir),JSON.stringify(review,null,2),{flag:"wx"});
  const observationBatch=`host-emergency-call-${state.sourceId}-v1`,tools=createCompilerProposalToolset(root);
  await tools.beginBatch([],observationBatch,state.sourceId);
  const call=(name:string,input:unknown)=>tools.tools.find(t=>t.name===name)!.execute(name,input as never,undefined,undefined,{} as never);
  await call("propose_entity_resolution",{proposal_id:"res-fingel-emergency-host-v1",resolution_id:"res-fingel-emergency-host-v1",mention_id:listener,status:"resolved",entity_id:"char-fingel",candidates:[{entity_id:"char-fingel",confidence:1,basis_mention_ids:[listener],evidence_assertion_ids:[],rationale:"Exact named Fingel is waiting at the computer and answers the connected emergency call in the same source passage."}],rationale:"Host source review resolves the original literal mention to existing Fingel; no new identity."});
  await call("propose_quotation",{proposal_id:"q-lumingfei-emergency-map-host-v1",annotation_id:quoteId,selector:{segment_id:segmentId,exact},mode:"direct",speaker_mention_id:speaker,addressee_mention_ids:[listener],attribution_confidence:1});
  await call("finish_compiler_batch",{outcome:"complete",reviewed_segments:[],summary:"Host source review resolves existing Fingel mention and adds the exact emergency report, preserving original event fields and deferrals."});
  const observationStore=new CompilerFinishReceipts(root,state.sourceId,observationBatch),receipt=await observationStore.read();if(receipt?.state!=="completed")throw Error("Observation finish incomplete");await observationStore.verify(receipt);
  for(const a of annotationBefore)if(contentHash(await annotations.read(state.sourceId,a.id))!==contentHash(a))throw Error("Existing annotation changed");
  await writeKnowledgeRepairPlan(root,{version:1,sourceId:state.sourceId,batchId,predecessorBatchId:oldBatch,predecessorFingerprint:old.fingerprint,reviewRef:reviewPath,events:[event],quotationIds:[quoteId]});
  const prompt=await buildKnowledgeRepairPrompt(root,state.sourceId,batchId);if(!prompt.includes(quoteId))throw Error("Scoped quotation missing from prompt.");
  let gateRetained=false;try{await assertReconciliationDeferralsReviewed(root,state.sourceId);}catch(e){if(String(e).includes("host source review"))gateRetained=true;else throw e;}if(!gateRetained)throw Error("Original deferral gate disappeared.");
  const diagnostic=`Knowledge acquisition remains unresolved for ${event.id}; predecessor=${old.fingerprint}. Host source review required; do not retry unchanged.`;
  state.knowledgeRepairHistory=[...(state.knowledgeRepairHistory??[]),state.knowledgeRepair];
  state.knowledgeRepair={batchId,pending:true,reviewPath};
  state.appliedRepairHistory=[...(state.appliedRepairHistory??[]),state.appliedRepair];
  state.appliedRepair={repairId:"emergency-call-source-reviewed-knowledge-dependencies-v1",failureFingerprint:compilerFailureFingerprint(diagnostic),reviewPath,appliedAt:new Date().toISOString(),fingerprintBasis:"Original deferred event knowledge gap, not aggregate percentages"};
  await fs.writeFile(new URL("state.tmp.json",dir),JSON.stringify(state,null,2));await fs.rename(new URL("state.tmp.json",dir),new URL("state.json",dir));
  console.log(JSON.stringify({ready:true,target:event.id,gateRetained,namespaceUnchanged:true}));
});
