import fs from 'node:fs/promises';
import { CanonicalModelStore } from '../../src/world/canonical-model.js';
import { characterEntryCheckpointSchema } from '../../src/world/model.js';
import { worldStorageRoot } from '../../src/world/paths.js';
import { contentHash } from '../../src/world/canonical.js';
import { WorkspaceStore } from '../../src/storage/workspace-store.js';
import { SourceMaterialStore } from '../../src/storage/source-material-store.js';
import { inspectCompilerStatus } from '../../src/compiler/status.js';
import { CompilerFinishReceipts } from '../../src/compiler/finish-receipts.js';
import { EvidenceAssertionStore } from '../../src/compiler/evidence-assertions.js';
import { createCompilerProposalToolset } from '../../src/compiler/proposal-tools.js';
import { convergeWorldProposals } from '../../src/compiler/converge.js';
import { assertReconciliationDeferralsReviewed } from '../../src/compiler/reconciliation-review-ledger.js';
import { compilerFailureCauseFingerprint } from '../../src/runtime/codex-compile-loop.js';
import { withWorkspaceOperationLock } from '../../src/util/workspace-lock.js';
const root=process.cwd(),dir=new URL('./',import.meta.url);
await withWorkspaceOperationLock(root,'compiler',async()=>{
 const state=JSON.parse(await fs.readFile(new URL('state.json',dir),'utf8'));
 if(state.attempt!==71||state.status!=='needs-review'||state.knowledgeRepair.pending)throw Error('Incident changed');
 const status=(await inspectCompilerStatus(root,state.sourceId)).sources[0]!;
 if(status.sourceIntegrity!=='verified'||status.hasUnresolvedObligations||status.worldProposalInventory.pending)throw Error('Unreviewed obligations');
 const canon=new CanonicalModelStore(root),events=await canon.listEvents();
 const event=events.find(e=>e.id==='event-lumingze-visit-001');if(!event||event.characterEntryCheckpoints?.length)throw Error('Entry target changed');
 if(events.some(e=>e.participantPresence?.some(p=>p.entityId==='char-eva-00008'&&p.mode==='physical')))throw Error('Prior EVA failure recurred; stop');
 const sorted=events.slice().sort((a,b)=>Math.min(...a.evidence.map(r=>r.span.startLine))-Math.min(...b.evidence.map(r=>r.span.startLine))||(a.narrativeContext?.discourseOrder??0)-(b.narrativeContext?.discourseOrder??0)||a.id.localeCompare(b.id));
 for(const actor of ['char-lumingze-boy'])if(sorted.find(e=>(!e.narrativeContext||e.narrativeContext.mode==='scene')&&e.participantPresence?.some(p=>p.entityId===actor&&p.mode==='physical'))?.id!==event.id)throw Error('First-entry target changed');
 const originalBatch=`reconcile-${state.sourceId}-bounded-codex-target-review-v1-20260912-3`,predecessor=new CompilerFinishReceipts(root,state.sourceId,originalBatch),old=await predecessor.read();if(old?.state!=='completed')throw Error('Original finish missing');await predecessor.verify(old);
 const reports=old.identity.input.target_reviews?.filter(r=>['event:event-lumingze-visit-001'].includes(r.target));if(reports?.length!==1||reports.some(r=>r.disposition!=='capability-gap'))throw Error('Original reports changed');
 const ledgerDir=worldStorageRoot(root)+'/compiler/reconciliation-reviews/'+state.sourceId;
 const ledgers=[];for(const file of await fs.readdir(ledgerDir)){const ledger=JSON.parse(await fs.readFile(ledgerDir+'/'+file,'utf8'));const results=ledger.results?.filter((r:{target:string})=>r.target==='event:event-lumingze-visit-001');if(results?.length)ledgers.push({file,finishFingerprint:ledger.finishFingerprint,results});}if(!ledgers.length)throw Error('Original target ledger missing');
 const source=await WorkspaceStore.openReadOnly(root).getSource(state.sourceId);if(!source)throw Error('Source missing');const bytes=await new SourceMaterialStore().read(source);if(!bytes)throw Error('Immutable source missing');const lines=bytes.toString('utf8').split('\n');
 const exact=(needle:string)=>{const matches=lines.slice(1959,1971).filter(l=>l.includes(needle));if(matches.length!==1)throw Error('Anchor not unique');return matches[0]!.trim();};
 const window=exact('男孩正坐在他的窗台上'),purpose=exact('我不能呆太多的时间，只是提醒你'),uncertainty=exact('你现在看到的不是真实世界');
 const checkpoints=[characterEntryCheckpointSchema.parse({actorId:'char-lumingze-boy',readerSetup:'在这段真实性受到人物质疑的窗边相遇中，同名男孩准备提醒路明非做好准备。这里停在对话开始前；不据此判定相遇属于现实或梦境。',actorObservation:'你准备提醒路明非做好准备。',participantPresence:[{entityId:'char-lumingze-boy',mode:'physical'}],delta:{version:1,operations:[{op:'set',entityId:'char-lumingze-boy',field:'character.plan',value:'提醒路明非做好准备'}]}})];
 const next={...event,characterEntryCheckpoints:checkpoints};
 const batch=`host-boy-warning-pre-entry-${state.sourceId}-v1`,reviewPath='run-records/2026-09-11-codex-compile-loop/host-review-boy-warning-entry-checkpoint.json';
 await fs.writeFile(new URL('host-review-boy-warning-entry-checkpoint.json',dir),JSON.stringify({reviewedAt:new Date().toISOString(),priorState:state,originalBatch,originalReceipt:old.fingerprint,reports,ledgers,original:event,next,sourceQuotes:{window,purpose,uncertainty},reason:'Host reviewed the exact original capability-gap report, later accepted report-only knowledge ledger, and immutable source lines 1960-1971. The boy explicitly states his visit purpose is to remind Lumingfei to prepare. This supports only a strong-inference immediate pre-dialogue reminder plan, without endorsing claims of imminent events or actual cheats. Retain the already source-separated boy identity and existing event presence semantics; this entry repair does not adjudicate the scene reality/dream ambiguity, and reader setup expressly retains that uncertainty. No cousin knowledge, hidden identity, map ability, future danger, complete worldview or received dialogue is seeded. Existing post-dialogue reported knowledge, all original fields, reports, receipts and publication gates remain intact.',validation:'Character entry, entry-context, compiler finish/obligation and loop regressions plus strict type check and normal schema/evidence/commit verification.'},null,2),{flag:'wx'});
 const toolset=createCompilerProposalToolset(root);await toolset.beginBatch([],batch,state.sourceId);const call=(name:string,input:unknown)=>toolset.tools.find(t=>t.name===name)!.execute(name,input as never,undefined,undefined,{} as never);
 const segment='a28585b1cf867f3e3a16-00011-80174f0bd7d3';
 const assertions=await new EvidenceAssertionStore(root).listForArtifact('canonical-event',event.id);
 const selectors=assertions.flatMap(a=>a.anchors.map(anchor=>{
  const exact=bytes.subarray(anchor.startByte,anchor.endByte).toString('utf8'),needle=Buffer.from(exact),hits:number[]=[];
  for(let offset=305615;offset<330964;){const at=bytes.indexOf(needle,offset);if(at<0||at+needle.length>330964)break;hits.push(at);offset=at+1;}
  const occurrence=hits.indexOf(anchor.startByte)+1;if(!occurrence)throw Error('Original evidence outside reviewed segment');
  return {segment_id:segment,exact,...(hits.length>1?{occurrence}:{}),target_path:a.target.jsonPointer,relation:a.relation,strength:a.strength,...(a.interpretation?{interpretation:a.interpretation}:{})};
 }));
 for(let index=0;index<checkpoints.length;index++)for(const field of ['readerSetup','actorObservation','participantPresence','delta'])for(const quote of [window,purpose,uncertainty])selectors.push({segment_id:segment,exact:quote,target_path:`/characterEntryCheckpoints/${index}/${field}`,relation:'supports',strength:'strong-inference',interpretation:'Stated visit purpose supports only a pre-dialogue reminder intention; the scene reality remains disputed and no future knowledge or power is seeded.'});
 const {evidence,...payload}=next;await call('propose_canonical_event',{proposal_id:'event-boy-warning-host-checkpoint-v1',payload,evidence_segment_ids:[segment],evidence_selectors:selectors});
 await call('finish_compiler_batch',{outcome:'complete',reviewed_segments:[],summary:'Source-reviewed pre-dialogue reminder plan for the separate boy; scene ambiguity and report-only later knowledge retained.'});
 const receipts=new CompilerFinishReceipts(root,state.sourceId,batch),receipt=await receipts.read();if(receipt?.state!=='completed')throw Error('Finish incomplete');await receipts.verify(receipt);
 const result=await convergeWorldProposals(root,state.sourceId);if(result.canonical.blocked.length||result.possibilities.blocked.length)throw Error(JSON.stringify(result));
 const current=await canon.listEvents();for(const e of events)if(contentHash(current.find(c=>c.id===e.id))!==contentHash(e.id===event.id?next:e))throw Error('Unexpected event change');
 await predecessor.verify(old);
 let gate=false;try{await assertReconciliationDeferralsReviewed(root,state.sourceId);}catch(e){if(String(e).includes('host source review'))gate=true;else throw e;}if(!gate)throw Error('Original review gate lost');
 state.appliedRepairHistory.push(state.appliedRepair);state.appliedRepair={repairId:'boy-source-reviewed-pre-warning-checkpoint-v1',failureFingerprint:compilerFailureCauseFingerprint({category:'missing-source-backed-boy-warning-entry',targetIds:['char-lumingze-boy'],dependencyIds:[event.id]}),reviewPath,appliedAt:new Date().toISOString()};
 await fs.writeFile(new URL('host-review-boy-warning-entry-checkpoint-result.json',dir),JSON.stringify({receipt:receipt.fingerprint,gateRetained:gate,onlyEntryCheckpointAdded:true}));
 await fs.writeFile(new URL('state.tmp.json',dir),JSON.stringify(state,null,2));await fs.rename(new URL('state.tmp.json',dir),new URL('state.json',dir));console.log(JSON.stringify({ready:true,receipt:receipt.fingerprint,gateRetained:gate}));
});
