import fs from "node:fs/promises";
import { WorkspaceStore } from "../../src/storage/workspace-store.js";
import { SourceMaterialStore } from "../../src/storage/source-material-store.js";
import { CanonicalModelStore } from "../../src/world/canonical-model.js";
import { SourceAnnotationStore } from "../../src/compiler/annotations.js";
import { EntityResolutionStore } from "../../src/compiler/entity-resolution.js";
import { inspectCompilerStatus } from "../../src/compiler/status.js";
import { CompilerFinishReceipts } from "../../src/compiler/finish-receipts.js";
import { createCompilerProposalToolset } from "../../src/compiler/proposal-tools.js";
import { writeKnowledgeRepairPlan, buildKnowledgeRepairPrompt } from "../../src/compiler/knowledge-repair.js";
import { assertReconciliationDeferralsReviewed } from "../../src/compiler/reconciliation-review-ledger.js";
import { validateCommittedAttributionTrace } from "../../src/compiler/attribution-trace.js";
import { contentHash } from "../../src/world/canonical.js";
import { compilerFailureFingerprint, compilerFailureCauseFingerprint } from "../../src/runtime/codex-compile-loop.js";
import { withWorkspaceOperationLock } from "../../src/util/workspace-lock.js";
const root=process.cwd(),dir=new URL("./",import.meta.url);
await withWorkspaceOperationLock(root,"compiler",async()=>{
  const state=JSON.parse(await fs.readFile(new URL("state.json",dir),"utf8"));
  if(state.attempt!==34||state.status!=="needs-review"||state.knowledgeRepair.pending)throw Error("Incident changed.");
  const source=(await inspectCompilerStatus(root,state.sourceId)).sources.find(s=>s.sourceId===state.sourceId)!;
  if(source.sourceIntegrity!=="verified"||source.hasUnresolvedObligations||source.worldProposalInventory.pending)throw Error("Unreviewed source or obligations.");
  const canon=new CanonicalModelStore(root), annotations=new SourceAnnotationStore(root);
  for(const a of await canon.listAttributions())if((await validateCommittedAttributionTrace(root,state.sourceId,a)).length)throw Error("Prior trace repair has not passed.");
  const events=await canon.listEvents(),event=events.find(e=>e.id==="event-cheatmap-001")!;
  if(!event||event.observedKnowledge?.operations.length||event.observedOutcome.operations.length)throw Error("Target changed.");
  const oldBatch=`reconcile-${state.sourceId}-bounded-codex-target-review-v1-20260912-3`;
  const oldStore=new CompilerFinishReceipts(root,state.sourceId,oldBatch),old=await oldStore.read();
  if(old?.state!=="completed")throw Error("Original batch unfinished.");await oldStore.verify(old);
  const report=old.identity.input.target_reviews?.find(r=>r.target===`event:${event.id}`);
  if(report?.disposition!=="capability-gap"||report.summary!=="The source explicitly says the three-dimensional Bronze City map appears and is marked as Lumingfei's interpretation. No map artifact/entity or field exists to represent acquiring/displaying it, and no compatible claim exists for knowledge.")throw Error("Original report changed.");
  const doc=await WorkspaceStore.openReadOnly(root).getSource(state.sourceId);if(!doc)throw Error("Missing source.");
  const bytes=await new SourceMaterialStore().read(doc);if(!bytes)throw Error("Missing immutable bytes.");
  const lines=bytes.toString("utf8").split("\n");
  const exact="几秒钟之后，所有人的界面都变了，变成了黑屏。从上而下，一幅巨大的三维地图刷新，所有人都呆住了，不敢相信自己的眼睛。这张地图上，巨大的青铜城被解析为一个一个的机件，那些机件正在运转，旧的道路封死，新的道路生成。";
  if(lines[2040]?.trim()!==exact||!lines[2042]?.includes("路明非解读结果"))throw Error("Original visual observation changed");
  if(!event.participants.includes("char-lumingfei")||event.participantPresence?.find(p=>p.entityId==="char-lumingfei")?.mode!=="physical")throw Error("Observer changed");
  const dependencies={claims:await canon.listClaims(),propositions:await canon.listPropositions(),attributions:await canon.listAttributions()};
  const batchId=`reconcile-${state.sourceId}-knowledge-effects-${state.semanticRunId}-19`,reviewPath="run-records/2026-09-11-codex-compile-loop/host-review-map-observation.json";
  const review={reviewedAt:new Date().toISOString(),sourceId:state.sourceId,batchId,report,originalFinishFingerprint:old.fingerprint,exact,sourceLines:lines.slice(2038,2045),dependencies,baseline:event,
    finding:"Host reviewed the original model deferral and exact visual-display passage. It explicitly states that all present see their interfaces change and the rendered city mechanisms and roads moving. The absent map artifact blocks inventory/ownership, not the existing observed acquisition mode. Permit only Lumingfei observing that his interface displays a dynamic three-dimensional city map with old roads closing and new roads appearing, using a source-grounded proposition and compatible claim. Keep content about the visible display; do not turn map predictions into committed city topology, grant omniscient route knowledge, invent a map entity, ownership, numeric skill, or magical ability. This is visual observation, not a spoken report or reading a document; no quotation whitelist or fictitious speaker is supplied. Preserve every baseline event field, source evidence, original proposal history and publication gate.",
    priorKnowledgeRepair:state.knowledgeRepair,priorAppliedRepair:state.appliedRepair,namespaceUnchanged:state.semanticRunId,validation:"Knowledge scope, quotation trace, normal finish and obligation regression tests and type checks passed before application."};
  await fs.writeFile(new URL("host-review-map-observation.json",dir),JSON.stringify(review,null,2),{flag:"wx"});
  await writeKnowledgeRepairPlan(root,{version:1,sourceId:state.sourceId,batchId,predecessorBatchId:oldBatch,predecessorFingerprint:old.fingerprint,reviewRef:reviewPath,events:[event]});
  const prompt=await buildKnowledgeRepairPrompt(root,state.sourceId,batchId);if(!prompt.includes(event.id))throw Error("Scoped quotation missing from prompt.");
  let gateRetained=false;try{await assertReconciliationDeferralsReviewed(root,state.sourceId);}catch(e){if(String(e).includes("host source review"))gateRetained=true;else throw e;}if(!gateRetained)throw Error("Original deferral gate disappeared.");
  const diagnostic=`Knowledge acquisition remains unresolved for ${event.id}; predecessor=${old.fingerprint}. Host source review required; do not retry unchanged.`;
  state.knowledgeRepairHistory=[...(state.knowledgeRepairHistory??[]),state.knowledgeRepair];
  state.knowledgeRepair={batchId,pending:true,reviewPath};
  state.appliedRepairHistory=[...(state.appliedRepairHistory??[]),state.appliedRepair];
  state.appliedRepair={repairId:"map-display-source-reviewed-knowledge-v1",failureFingerprint:compilerFailureCauseFingerprint({category:"knowledge-not-produced-with-verified-evidence",targetIds:[event.id],dependencyIds:[]}),reviewPath,appliedAt:new Date().toISOString(),fingerprintBasis:"Original deferred event knowledge gap, not aggregate percentages"};
  await fs.writeFile(new URL("state.tmp.json",dir),JSON.stringify(state,null,2));await fs.rename(new URL("state.tmp.json",dir),new URL("state.json",dir));
  console.log(JSON.stringify({ready:true,target:event.id,gateRetained,namespaceUnchanged:true}));
});
