import fs from 'node:fs/promises';
import { CanonicalModelStore } from '../../src/world/canonical-model.js';
import { characterEntryCheckpointSchema } from '../../src/world/model.js';
import { contentHash } from '../../src/world/canonical.js';
import { WorkspaceStore } from '../../src/storage/workspace-store.js';
import { SourceMaterialStore } from '../../src/storage/source-material-store.js';
import { inspectCompilerStatus } from '../../src/compiler/status.js';
import { CompilerFinishReceipts } from '../../src/compiler/finish-receipts.js';
import { EvidenceAssertionStore } from '../../src/compiler/evidence-assertions.js';
import { createCompilerProposalToolset } from '../../src/compiler/proposal-tools.js';
import { convergeWorldProposals } from '../../src/compiler/converge.js';
import { assertReconciliationDeferralsReviewed } from '../../src/compiler/reconciliation-review-ledger.js';
import { compilerFailureCauseFingerprint } from '../../src/runtime/codex-compile-loop.js';
import { withWorkspaceOperationLock } from '../../src/util/workspace-lock.js';
const root=process.cwd(),dir=new URL('./',import.meta.url);
await withWorkspaceOperationLock(root,'compiler',async()=>{
 const state=JSON.parse(await fs.readFile(new URL('state.json',dir),'utf8'));
 if(state.attempt!==50||state.status!=='needs-review'||state.knowledgeRepair.pending)throw Error('Incident changed');
 const status=(await inspectCompilerStatus(root,state.sourceId)).sources[0]!;
 if(status.sourceIntegrity!=='verified'||status.hasUnresolvedObligations||status.worldProposalInventory.pending)throw Error('Unreviewed obligations');
 const canon=new CanonicalModelStore(root),events=await canon.listEvents();
 const event=events.find(e=>e.id==='event-duel-00007');if(!event||event.characterEntryCheckpoints?.length||event.narrativeContext?.discourseOrder!==1066)throw Error('Entry target changed');
 const sorted=events.slice().sort((a,b)=>Math.min(...a.evidence.map(r=>r.span.startLine))-Math.min(...b.evidence.map(r=>r.span.startLine))||(a.narrativeContext?.discourseOrder??0)-(b.narrativeContext?.discourseOrder??0)||a.id.localeCompare(b.id));
 for(const actor of ['char-caesar','char-chuzi-hang'])if(sorted.find(e=>(!e.narrativeContext||e.narrativeContext.mode==='scene')&&e.participantPresence?.some(p=>p.entityId===actor&&p.mode==='physical'))?.id!==event.id)throw Error('First-entry target changed');
 const originalBatch=`reconcile-${state.sourceId}-bounded-codex-target-review-v1-20260912-1`,predecessor=new CompilerFinishReceipts(root,state.sourceId,originalBatch),old=await predecessor.read();if(old?.state!=='completed')throw Error('Original finish missing');await predecessor.verify(old);
 const reports=old.identity.input.target_reviews?.filter(r=>['event:event-duel-00007'].includes(r.target));if(reports?.length!==1||reports.some(r=>r.disposition!=='unsupported'))throw Error('Original reports changed');
 const source=await WorkspaceStore.openReadOnly(root).getSource(state.sourceId);if(!source)throw Error('Source missing');const bytes=await new SourceMaterialStore().read(source);if(!bytes)throw Error('Immutable source missing');const lines=bytes.toString('utf8').split('\n');
 const exact=(needle:string)=>{const matches=lines.slice(1065,1071).filter(l=>l.includes(needle));if(matches.length!==1)throw Error('Anchor not unique');return matches[0]!.trim();};
 const approach=exact('两人向着停车场走去'),facing=exact('深红色作战服的人站在停车场一侧'),caesar=exact('能走到我面前，你比我想的强。'),chu=exact('能让恺撒这么夸奖，很荣幸。');
 const checkpoints=[
  {actorId:'char-caesar',actorObservation:'你持着猎刀站在停车场一侧，对面的人持着长刀，双方已摘下面罩。',plan:'在停车场与楚子航进行刀战'},
  {actorId:'char-chuzi-hang',actorObservation:'你持着长刀站在停车场，对面的恺撒拿着猎刀；你们已相互交谈。',plan:'在停车场与恺撒进行刀战'},
 ].map(({actorId,actorObservation,plan})=>characterEntryCheckpointSchema.parse({actorId,readerSetup:'双方持刀来到停车场，站在对面并摘下面罩，已经开始交谈。这是第一轮近身攻击之前；没有人已在这轮交手中受伤或获胜。',actorObservation,participantPresence:[{entityId:'char-caesar',mode:'physical'},{entityId:'char-chuzi-hang',mode:'physical'}],delta:{version:1,operations:[{op:'set',entityId:actorId,field:'character.plan',value:plan}]}}));
 const next={...event,characterEntryCheckpoints:checkpoints};
 const batch=`host-duel-pre-entry-${state.sourceId}-v1`,reviewPath='run-records/2026-09-11-codex-compile-loop/host-review-duel-entry-checkpoints.json';
 await fs.writeFile(new URL('host-review-duel-entry-checkpoints.json',dir),JSON.stringify({reviewedAt:new Date().toISOString(),priorState:state,originalBatch,originalReceipt:old.fingerprint,reports,original:event,next,sourceQuotes:{approach,facing,caesar,chu},reason:'Host reread the original unsupported report and immutable pre-combat passage. Unknown global story-time and absent numerical battle effects remain unresolved. They do not preclude a plan checkpoint: the two armed opponents explicitly walk to the parking lot, stand opposite one another, remove masks and exchange words before the first lunge. Checkpoint boundary is immediately before that first attack, not before the completed walk. Their intent to duel is strong inference from these concrete preparations, not a newly invented permanent trait or automatic victory. Set only each own character.plan, with reader setup and physical observations of visible weapons/opponent. Do not add health values, inventory assignments, hidden skills, post-lunge results, or give Lumingfei the narrator explanation. Existing event effects, observer knowledge, discourse ordering, original reports, checkpoints elsewhere and all publication gates remain unchanged. Prior Nono checkpoint is intact; increased entry coverage supports successful prior repair.',validation:'Character entry, entry-context, compiler finish/obligation and loop regressions plus strict type check and normal schema/evidence/commit verification.'},null,2),{flag:'wx'});
 const toolset=createCompilerProposalToolset(root);await toolset.beginBatch([],batch,state.sourceId);const call=(name:string,input:unknown)=>toolset.tools.find(t=>t.name===name)!.execute(name,input as never,undefined,undefined,{} as never);
 const segment='a28585b1cf867f3e3a16-00007-26df32014434';
 const assertions=await new EvidenceAssertionStore(root).listForArtifact('canonical-event',event.id);
 const selectors=assertions.flatMap(a=>a.anchors.map(anchor=>({segment_id:segment,exact:bytes.subarray(anchor.startByte,anchor.endByte).toString('utf8'),target_path:a.target.jsonPointer,relation:a.relation,strength:a.strength,...(a.interpretation?{interpretation:a.interpretation}:{})})));
 for(let index=0;index<checkpoints.length;index++)for(const field of ['readerSetup','actorObservation','participantPresence','delta'])for(const quote of [approach,facing,caesar,chu])selectors.push({segment_id:segment,exact:quote,target_path:`/characterEntryCheckpoints/${index}/${field}`,relation:'supports',strength:'strong-inference',interpretation:'Pre-first-attack boundary after the explicitly completed armed approach and dialogue. Intent is bounded to this encounter; no fighting result or narrator-only knowledge is imported.'});
 const {evidence,...payload}=next;await call('propose_canonical_event',{proposal_id:'event-duel-host-checkpoints-v1',payload,evidence_segment_ids:[segment],evidence_selectors:selectors});
 await call('finish_compiler_batch',{outcome:'complete',reviewed_segments:[],summary:'Source-reviewed pre-first-attack checkpoints for Caesar and Chu, with preparation plans only; all existing event and knowledge effects preserved.'});
 const receipts=new CompilerFinishReceipts(root,state.sourceId,batch),receipt=await receipts.read();if(receipt?.state!=='completed')throw Error('Finish incomplete');await receipts.verify(receipt);
 const result=await convergeWorldProposals(root,state.sourceId);if(result.canonical.blocked.length||result.possibilities.blocked.length)throw Error(JSON.stringify(result));
 const current=await canon.listEvents();for(const e of events)if(contentHash(current.find(c=>c.id===e.id))!==contentHash(e.id===event.id?next:e))throw Error('Unexpected event change');
 await predecessor.verify(old);
 let gate=false;try{await assertReconciliationDeferralsReviewed(root,state.sourceId);}catch(e){if(String(e).includes('host source review'))gate=true;else throw e;}if(!gate)throw Error('Original review gate lost');
 state.appliedRepairHistory.push(state.appliedRepair);state.appliedRepair={repairId:'duel-source-reviewed-pre-attack-checkpoints-v1',failureFingerprint:compilerFailureCauseFingerprint({category:'missing-source-backed-pre-attack-entry',targetIds:['char-caesar','char-chuzi-hang'],dependencyIds:[event.id]}),reviewPath,appliedAt:new Date().toISOString()};
 await fs.writeFile(new URL('host-review-duel-entry-checkpoints-result.json',dir),JSON.stringify({receipt:receipt.fingerprint,gateRetained:gate,onlyEntryCheckpointAdded:true}));
 await fs.writeFile(new URL('state.tmp.json',dir),JSON.stringify(state,null,2));await fs.rename(new URL('state.tmp.json',dir),new URL('state.json',dir));console.log(JSON.stringify({ready:true,receipt:receipt.fingerprint,gateRetained:gate}));
});
