import fs from 'node:fs/promises';
import { CanonicalModelStore } from '../../src/world/canonical-model.js';
import { characterEntryCheckpointSchema } from '../../src/world/model.js';
import { worldStorageRoot } from '../../src/world/paths.js';
import { contentHash } from '../../src/world/canonical.js';
import { WorkspaceStore } from '../../src/storage/workspace-store.js';
import { SourceMaterialStore } from '../../src/storage/source-material-store.js';
import { inspectCompilerStatus } from '../../src/compiler/status.js';
import { CompilerFinishReceipts } from '../../src/compiler/finish-receipts.js';
import { EvidenceAssertionStore } from '../../src/compiler/evidence-assertions.js';
import { createCompilerProposalToolset } from '../../src/compiler/proposal-tools.js';
import { convergeWorldProposals } from '../../src/compiler/converge.js';
import { assertReconciliationDeferralsReviewed } from '../../src/compiler/reconciliation-review-ledger.js';
import { compilerFailureCauseFingerprint } from '../../src/runtime/codex-compile-loop.js';
import { withWorkspaceOperationLock } from '../../src/util/workspace-lock.js';
const root=process.cwd(),dir=new URL('./',import.meta.url);
import { generateEntityResolutionCandidates, EntityResolutionStore } from '../../src/compiler/entity-resolution.js';
await withWorkspaceOperationLock(root,'compiler',async()=>{
 const state=JSON.parse(await fs.readFile(new URL('state.json',dir),'utf8'));if(state.attempt!==80||state.status!=='needs-review')throw Error('Incident changed');const status=(await inspectCompilerStatus(root,state.sourceId)).sources[0]!;if(status.sourceIntegrity!=='verified'||status.hasUnresolvedObligations||status.worldProposalInventory.pending)throw Error('Unreviewed obligations');
 const canon=new CanonicalModelStore(root),events=await canon.listEvents(),entities=await canon.listEntities(),resolutions=new EntityResolutionStore(root),before=await resolutions.list(state.sourceId);const priorReview=JSON.parse(await fs.readFile(new URL(state.appliedRepair.reviewPath.split('/').at(-1)!,dir),'utf8'));for(const t of priorReview.targets)if(!before.some(r=>r.mentionId===t.mention.id&&r.entityId===t.entity.id&&r.status==='resolved'))throw Error('Previous targeted failure recurred');
 const batch=`host-manshtein-identity-links-${state.sourceId}-v1`,specs=[
 ['m-manshtein','char-manshtein','Guderian explicitly names Professor Manshtein as his colleague in a calculation; same professor, without endorsing the calculation or bloodline speculation.'],
 ['m-manstein-1','char-manshtein','Guderian addresses Manshtein and the next line explicitly identifies the disciplinary chairman as Professor Manshtein.'],
 ['m-manstein-current','char-manshtein','Separate existing observation of the same library greeting; preserve both annotation IDs and link independently.'],
 ['m-mannstein-01-v2','char-manshtein','The narrator names Professor Manshtein reading the academy forum and subsequently uses the short name; identity only, no new mental-state or ancestry facts.'],
 ['m-mannstein-02','char-manshtein','Nono explicitly names Professor Manshtein as her course instructor while talking to Caesar; a reference, not physical presence.'],
 ['em-mannstein-1','char-manshtein','Nono identifies the disciplinary-committee professor as invigilator, followed immediately by Professor Manshtein appearing.'],
 ['m-mansht-1','char-manshtein','The narrator explicitly names Professor Manshtein at the library with Guderian after the preceding scene about Mans. Preserve distinct Mans and Manshtein identities across the scene transition.'],
 ['m-mansht','char-manshtein','Manshtein enters the library control room with Guderian and addresses the emergency; same named professor.'],
 ['em-manst','char-manshtein','Schneider turns to Manshtein in the continuing control-room exchange. Resolve the named respondent without validating the ability claim.'],
 ['em-mannstein','char-manshtein','Manshtein addresses Schneider about disciplinary-committee access during the same command-room scene. Identity only, not new permissions or character knowledge.'],
 ['em-manstein-1','char-manshtein','The ship captain explicitly self-names Manshtein and the narrator calls him Professor Manshtein in the same sentence. Not Mans or Angier.'],
 ['m_mansht','char-manshtein','The same named expedition captain watches the connection monitor with Caesar in Monigar forecabin. Preserve the reported survival estimate without certifying it.'],
 ['m-manshtain-00022','char-manshtein','The narrator explicitly locates Manshtein in Monigar forecabin in the continuing rescue scene. Resolve him without merging him with Nono whose voice is reported from his mouth or adding an ability.'],
 ] as const;
 const source=await WorkspaceStore.openReadOnly(root).getSource(state.sourceId);if(!source)throw Error('Source missing');const bytes=await new SourceMaterialStore().read(source);if(!bytes)throw Error('Source missing');const lines=bytes.toString('utf8').split('\n');
 const targets=[];for(const [mentionId,entityId,rationale] of specs){if(before.some(r=>r.mentionId===mentionId))throw Error('Resolution already exists');const discovery=await generateEntityResolutionCandidates(root,state.sourceId,mentionId,batch),mention=discovery.mention,entity=entities.find(e=>e.id===entityId);if(!entity||!mention.kindCandidates.includes(entity.kind)||bytes.subarray(mention.anchor.startByte,mention.anchor.endByte).toString('utf8')!==mention.surface)throw Error('Source/identity mismatch');const context=lines.slice(Math.max(0,mention.anchor.startLine-18),mention.anchor.endLine+7);targets.push({mention,entity,discovery,context,rationale});}
 const expectedLines=[990,1328,1328,1562,1585,1623,2305,2604,2821,3129,4088,4423,4611];if(targets.some((t,i)=>t.mention.anchor.startLine!==expectedLines[i]))throw Error('Reviewed context moved');
 const legacyOrigins:string[]=[],receipts=[];for(const batchId of new Set(targets.map(t=>t.mention.derivation.compilerBatchId))){if(!batchId)throw Error('Observation origin missing');const store=new CompilerFinishReceipts(root,state.sourceId,batchId),receipt=await store.read();if(!receipt){if(!status.completedBatchIds.includes(batchId))throw Error('Origin neither receipted nor legacy checkpointed');legacyOrigins.push(batchId);continue;}if(receipt.state!=='completed')throw Error('Incomplete observation receipt');await store.verify(receipt);receipts.push({store,receipt});}
 const ledgerDir=worldStorageRoot(root)+'/compiler/reconciliation-reviews/'+state.sourceId,ledgers=[];for(const file of await fs.readdir(ledgerDir)){const l=JSON.parse(await fs.readFile(ledgerDir+'/'+file,'utf8'));const results=l.results?.filter((r:{target:string})=>specs.some(([m,e])=>r.target.includes(m)||r.target==='character:'+e));if(results?.length)ledgers.push({file,results});}
 const reviewPath='run-records/2026-09-11-codex-compile-loop/host-review-manshtein-identity-links.json';await fs.writeFile(new URL('host-review-manshtein-identity-links.json',dir),JSON.stringify({reviewedAt:new Date().toISOString(),priorState:state,targets,identityIntroduction:{startLine:1328,endLine:1329,context:lines.slice(1327,1329)},ledgers,legacyOrigins,legacyPolicy:'Existing completed observation checkpoints without modern receipts are readable under docs/agent-tool-recovery.md; do not synthesize, replace or certify their missing receipts. All new resolution proposals require a verified completed finish. Initial preflight stopped before any proposal mutation.',originalReceipts:receipts.map(r=>r.receipt),reason:'Thirteen source-reviewed Manshtein references have explicit professor-name, disciplinary-chairman or continuous dialogue support. Preserve separate observations at line 1328. Scene changes do not merge Mans with Manshtein; the reported Nono voice does not merge the two characters either. No identity inference from opaque IDs alone. Add links only, preserving all goals, claims, abilities, physical participation, original observations, available receipts and legacy provenance. No relevant original target deferral was found; all unrelated deferrals, source-accounting obligations, canonical artifacts and checkpoints remain intact.'},null,2),{flag:'wx'});
 const toolset=createCompilerProposalToolset(root);await toolset.beginBatch([],batch,state.sourceId);const call=(name:string,input:unknown)=>toolset.tools.find(t=>t.name===name)!.execute(name,input as never,undefined,undefined,{} as never);
 for(const t of targets){const id='res-'+t.mention.id+'-host-v1';await call('propose_entity_resolution',{proposal_id:id,resolution_id:id,mention_id:t.mention.id,status:'resolved',entity_id:t.entity.id,candidates:[{entity_id:t.entity.id,confidence:1,basis_mention_ids:[t.mention.id],evidence_assertion_ids:[],rationale:t.rationale}],rationale:t.rationale});}
 await call('finish_compiler_batch',{outcome:'complete',reviewed_segments:[],summary:'Host source-reviewed thirteen separate Professor Manshtein name references. No entity, event, evidence or accounting waiver.'});
 const store=new CompilerFinishReceipts(root,state.sourceId,batch),receipt=await store.read();if(receipt?.state!=='completed')throw Error('Finish incomplete');await store.verify(receipt);const result=await convergeWorldProposals(root,state.sourceId);if(result.canonical.blocked.length||result.possibilities.blocked.length)throw Error(JSON.stringify(result));
 const after=await resolutions.list(state.sourceId);if(after.length!==before.length+specs.length)throw Error('Unexpected resolution count');for(const old of before)if(contentHash(after.find(r=>r.id===old.id))!==contentHash(old))throw Error('Prior resolution changed');for(const t of targets)if(!after.some(r=>r.mentionId===t.mention.id&&r.entityId===t.entity.id&&r.status==='resolved'))throw Error('Resolution missing');if(contentHash(await canon.listEvents())!==contentHash(events)||contentHash(await canon.listEntities())!==contentHash(entities))throw Error('World artifacts changed');for(const r of receipts)await r.store.verify(r.receipt);
 let gate=false;try{await assertReconciliationDeferralsReviewed(root,state.sourceId);}catch(e){if(String(e).includes('host source review'))gate=true;else throw e;}if(!gate)throw Error('Review gate lost');state.appliedRepairHistory.push(state.appliedRepair);state.appliedRepair={repairId:'source-reviewed-manshtein-identity-links-v1',failureFingerprint:compilerFailureCauseFingerprint({category:'missing-context-supported-entity-resolutions',targetIds:specs.map(s=>s[0]),dependencyIds:[...new Set(specs.map(s=>s[1]))]}),reviewPath,appliedAt:new Date().toISOString()};
 await fs.writeFile(new URL('host-review-manshtein-identity-links-result.json',dir),JSON.stringify({receipt:receipt.fingerprint,gateRetained:gate,addedResolutions:specs.length,canonicalArtifactsUnchanged:true}));await fs.writeFile(new URL('state.tmp.json',dir),JSON.stringify(state,null,2));await fs.rename(new URL('state.tmp.json',dir),new URL('state.json',dir));console.log(JSON.stringify({ready:true,receipt:receipt.fingerprint,gateRetained:gate}));
});
