import fs from 'node:fs/promises';
import { CanonicalModelStore } from '../../src/world/canonical-model.js';
import { ActorModelStore, characterGoalSchema, evaluateCharacterGoal } from '../../src/world/actors.js';
import { worldStorageRoot } from '../../src/world/paths.js';
import { contentHash } from '../../src/world/canonical.js';
import { WorkspaceStore } from '../../src/storage/workspace-store.js';
import { SourceMaterialStore } from '../../src/storage/source-material-store.js';
import { inspectCompilerStatus } from '../../src/compiler/status.js';
import { CompilerFinishReceipts } from '../../src/compiler/finish-receipts.js';
import { createCompilerProposalToolset } from '../../src/compiler/proposal-tools.js';
import { convergeWorldProposals } from '../../src/compiler/converge.js';
import { assertReconciliationDeferralsReviewed } from '../../src/compiler/reconciliation-review-ledger.js';
import { compilerFailureCauseFingerprint } from '../../src/runtime/codex-compile-loop.js';
import { withWorkspaceOperationLock } from '../../src/util/workspace-lock.js';
const root=process.cwd(),dir=new URL('./',import.meta.url);
await withWorkspaceOperationLock(root,'compiler',async()=>{
 const state=JSON.parse(await fs.readFile(new URL('state.json',dir),'utf8'));
 if(state.attempt!==63||state.status!=='needs-review'||state.knowledgeRepair.pending)throw Error('Incident changed');
 const status=(await inspectCompilerStatus(root,state.sourceId)).sources[0]!;
 if(status.sourceIntegrity!=='verified'||status.hasUnresolvedObligations||status.worldProposalInventory.pending)throw Error('Unreviewed obligations');
 const canon=new CanonicalModelStore(root),actors=new ActorModelStore(root),events=await canon.listEvents(),goals=await actors.listGoals(),models=await actors.listModels();
 const invitation=events.find(e=>e.id==='event-email-open-001');if(!invitation||!invitation.participants.includes('char-lumingfei'))throw Error('Invitation changed');
 if(!events.find(e=>e.id==='event-norton-capture-00017')?.characterEntryCheckpoints?.some(c=>c.actorId==='char-angier'))throw Error('Previous targeted failure recurred; stop');
 const originalBatch=`reconcile-${state.sourceId}-bounded-codex-target-review-v1-20260912-1`;
 const predecessor=new CompilerFinishReceipts(root,state.sourceId,originalBatch),old=await predecessor.read();if(old?.state!=='completed')throw Error('Original finish missing');await predecessor.verify(old);
 const report=old.identity.input.target_reviews?.find(r=>r.target==='character:char-caesar');
 if(report?.disposition!=='unsupported'||report.summary!=='The current model is already character-v1. The cited text characterizes Caesar, but does not establish a bounded psychological-development transition requiring a new model or goal.')throw Error('Original report changed');
 const ledgerDir=worldStorageRoot(root)+'/compiler/reconciliation-reviews/'+state.sourceId,ledgers=[];for(const file of await fs.readdir(ledgerDir)){const l=JSON.parse(await fs.readFile(ledgerDir+'/'+file,'utf8'));const results=l.results?.filter((r:{target:string})=>r.target==='character:char-caesar');if(results?.length)ledgers.push({file,results});}if(!ledgers.length)throw Error('Target ledger missing');
 const source=await WorkspaceStore.openReadOnly(root).getSource(state.sourceId);if(!source)throw Error('Source missing');const bytes=await new SourceMaterialStore().read(source);if(!bytes)throw Error('Immutable source missing');const lines=bytes.toString('utf8').split('\n');
 const matches=lines.slice(2378,2387).filter(l=>l.includes('恺撒说他想和你交流'));if(matches.length!==1)throw Error('Source quote changed');const quote=matches[0]!.trim();
 const goal=characterGoalSchema.parse({id:'goal-caesar-exchange-lumingfei-00013',actorId:'char-caesar',description:'诺诺的邀请邮件转述恺撒想与路明非交流；在这次晚宴邀请已实现后的会面阶段，争取与路明非交流。该转述不证明招揽动机，也不保证会面完成。',priority:0.5,requiresKnowledge:[],targetIds:['char-lumingfei'],activation:{preconditions:[],afterCanonicalEventIds:[invitation.id]},evidence:invitation.evidence});
 if(goals.some(g=>g.id===goal.id))throw Error('Goal already exists; inspect original scope instead of retrying');
 const evaluationState={atCommit:'host-review',logicalTime:{step:0},values:{},activeRuleIds:[]};
 const dormant=evaluateCharacterGoal(goal,{state:evaluationState,knownClaimIds:new Set(),realizedCanonicalEventIds:new Set()});
 const activated=evaluateCharacterGoal(goal,{state:evaluationState,knownClaimIds:new Set(),realizedCanonicalEventIds:new Set([invitation.id])});
 if(dormant.active||!activated.active)throw Error('Invitation activation boundary failed');
 const batch=`host-caesar-exchange-goal-${state.sourceId}-v1`,reviewPath='run-records/2026-09-11-codex-compile-loop/host-review-caesar-exchange-goal.json';
 await fs.writeFile(new URL('host-review-caesar-exchange-goal.json',dir),JSON.stringify({reviewedAt:new Date().toISOString(),priorState:state,originalBatch,originalReceipt:old.fingerprint,report,ledgers,invitation,proposal:goal,sourceLines:lines.slice(2378,2387),reason:'Host reviewed the exact unsupported Caesar goal report against the immutable invitation email. The email attributes to Caesar a desire to speak with Lumingfei. Represent only this attributed communication goal as a policy input after the invitation event is realized, not an objective psychological measurement, faction recruitment, completed conversation or inevitable future action. Explicitly preserve its reported provenance in the goal description. Priority 0.5 is neutral policy ranking, not measured intensity. Do not activate at opening or infer a calendar expiry without a validated time boundary. No character model, event, committed state, membership or other goal is changed; all original reports and publication gates remain.',validation:'Goal activation and development, compiler finish, proposal obligation and loop regressions; normal typed proposal, evidence validation, convergence and immutable predecessor verification.'},null,2),{flag:'wx'});
 const toolset=createCompilerProposalToolset(root);await toolset.beginBatch([],batch,state.sourceId);
 const call=(name:string,input:unknown)=>toolset.tools.find(t=>t.name===name)!.execute(name,input as never,undefined,undefined,{} as never);
 const {evidence,...payload}=goal,segment='a28585b1cf867f3e3a16-00013-2df5b1eb46fa';
 await call('propose_character_goal',{proposal_id:'goal-caesar-exchange-lumingfei-host-v1',payload,evidence_segment_ids:[segment],evidence_selectors:['/description','/actorId','/targetIds','/activation'].map(target_path=>({segment_id:segment,exact:quote,target_path,relation:'supports',strength:'strong-inference',interpretation:'Email directly reports Caesar desire to communicate; bounded policy goal preserves reported provenance, not proof of private motive.'}))});
 await call('finish_compiler_batch',{outcome:'complete',reviewed_segments:[],summary:'Host source-reviewed attributed communication goal for Caesar, activated only after the invitation; no private motive or world-state mutations.'});
 const receipts=new CompilerFinishReceipts(root,state.sourceId,batch),receipt=await receipts.read();if(receipt?.state!=='completed')throw Error('Finish incomplete');await receipts.verify(receipt);
 const result=await convergeWorldProposals(root,state.sourceId);if(result.canonical.blocked.length||result.possibilities.blocked.length)throw Error(JSON.stringify(result));
 const current=await actors.listGoals();if(current.length!==goals.length+1||contentHash(current.find(g=>g.id===goal.id))!==contentHash(goal))throw Error('Unexpected goal result');
 for(const oldGoal of goals)if(contentHash(current.find(g=>g.id===oldGoal.id))!==contentHash(oldGoal))throw Error('Existing goal changed');
 if(contentHash(await canon.listEvents())!==contentHash(events)||contentHash(await actors.listModels())!==contentHash(models))throw Error('Unrelated world/model changes');
 await predecessor.verify(old);
 let gate=false;try{await assertReconciliationDeferralsReviewed(root,state.sourceId);}catch(e){if(String(e).includes('host source review'))gate=true;else throw e;}if(!gate)throw Error('Original review gate lost');
 state.appliedRepairHistory.push(state.appliedRepair);state.appliedRepair={repairId:'caesar-source-reviewed-exchange-goal-v1',failureFingerprint:compilerFailureCauseFingerprint({category:'source-reported-communication-goal-omitted',targetIds:['char-caesar'],dependencyIds:[invitation.id]}),reviewPath,appliedAt:new Date().toISOString()};
 await fs.writeFile(new URL('host-review-caesar-exchange-goal-result.json',dir),JSON.stringify({receipt:receipt.fingerprint,gateRetained:gate,existingEventsModelsGoalsUnchanged:true}));
 await fs.writeFile(new URL('state.tmp.json',dir),JSON.stringify(state,null,2));await fs.rename(new URL('state.tmp.json',dir),new URL('state.json',dir));console.log(JSON.stringify({ready:true,receipt:receipt.fingerprint,gateRetained:gate}));
});
