import fs from 'node:fs/promises';
import { CanonicalModelStore } from '../../src/world/canonical-model.js';
import { characterEntryCheckpointSchema } from '../../src/world/model.js';
import { worldStorageRoot } from '../../src/world/paths.js';
import { contentHash } from '../../src/world/canonical.js';
import { WorkspaceStore } from '../../src/storage/workspace-store.js';
import { SourceMaterialStore } from '../../src/storage/source-material-store.js';
import { inspectCompilerStatus } from '../../src/compiler/status.js';
import { CompilerFinishReceipts } from '../../src/compiler/finish-receipts.js';
import { EvidenceAssertionStore } from '../../src/compiler/evidence-assertions.js';
import { createCompilerProposalToolset } from '../../src/compiler/proposal-tools.js';
import { convergeWorldProposals } from '../../src/compiler/converge.js';
import { assertReconciliationDeferralsReviewed } from '../../src/compiler/reconciliation-review-ledger.js';
import { compilerFailureCauseFingerprint } from '../../src/runtime/codex-compile-loop.js';
import { withWorkspaceOperationLock } from '../../src/util/workspace-lock.js';
const root=process.cwd(),dir=new URL('./',import.meta.url);
await withWorkspaceOperationLock(root,'compiler',async()=>{
 const state=JSON.parse(await fs.readFile(new URL('state.json',dir),'utf8'));
 if(state.attempt!==66||state.status!=='needs-review'||state.knowledgeRepair.pending)throw Error('Incident changed');
 const status=(await inspectCompilerStatus(root,state.sourceId)).sources[0]!;
 if(status.sourceIntegrity!=='verified'||status.hasUnresolvedObligations||status.worldProposalInventory.pending)throw Error('Unreviewed obligations');
 const canon=new CanonicalModelStore(root),events=await canon.listEvents();
 const event=events.find(e=>e.id==='event-laotang-coaching-00003');if(!event||event.characterEntryCheckpoints?.length!==1||event.characterEntryCheckpoints[0]?.actorId!=='char-lumingfei')throw Error('Entry target changed');
 if(!(await import('../../src/world/actors.js').then(m=>new m.ActorModelStore(root).listGoals())).some(g=>g.id==='goal-yesheng-retreat-bronze-city-00011'))throw Error('Prior targeted failure recurred; stop');
 const entities=await canon.listEntities();const location={id:'loc-lu-cousins-bedroom-00003',kind:'location' as const,canonicalName:'路明非和路鸣泽共同的卧室',aliases:[]};if(entities.some(e=>e.id===location.id||e.canonicalName===location.canonicalName))throw Error('Location already exists');
 const sorted=events.slice().sort((a,b)=>Math.min(...a.evidence.map(r=>r.span.startLine))-Math.min(...b.evidence.map(r=>r.span.startLine))||(a.narrativeContext?.discourseOrder??0)-(b.narrativeContext?.discourseOrder??0)||a.id.localeCompare(b.id));
 for(const actor of ['char-lumingze'])if(sorted.find(e=>(!e.narrativeContext||e.narrativeContext.mode==='scene')&&e.participantPresence?.some(p=>p.entityId===actor&&p.mode==='physical'))?.id!==event.id)throw Error('First-entry target changed');
 const originalBatch=`reconcile-${state.sourceId}-bounded-codex-target-review-v1-20260912-1`,predecessor=new CompilerFinishReceipts(root,state.sourceId,originalBatch),old=await predecessor.read();if(old?.state!=='completed')throw Error('Original finish missing');await predecessor.verify(old);
 const reports=old.identity.input.target_reviews?.filter(r=>['event:event-laotang-coaching-00003'].includes(r.target));if(reports?.length!==1||reports.some(r=>r.disposition!=='unsupported'))throw Error('Original reports changed');
 const ledgerDir=worldStorageRoot(root)+'/compiler/reconciliation-reviews/'+state.sourceId;
 const ledgers=[];for(const file of await fs.readdir(ledgerDir)){const ledger=JSON.parse(await fs.readFile(ledgerDir+'/'+file,'utf8'));const results=ledger.results?.filter((r:{target:string})=>r.target==='event:event-laotang-coaching-00003');if(results?.length)ledgers.push({file,finishFingerprint:ledger.finishFingerprint,results});}if(!ledgers.length)throw Error('Original target ledger missing');
 const source=await WorkspaceStore.openReadOnly(root).getSource(state.sourceId);if(!source)throw Error('Source missing');const bytes=await new SourceMaterialStore().read(source);if(!bytes)throw Error('Immutable source missing');const lines=bytes.toString('utf8').split('\n');
 const exact=(needle:string)=>{const matches=lines.slice(167,203).filter(l=>l.includes(needle));if(matches.length!==1)throw Error('Anchor not unique');return matches[0]!.trim();};
 const room=exact('路鸣泽走进他和路明非共同的卧室时'),sleep=exact('路明非看了一眼旁边床上睡着的路鸣泽');
 const checkpoints=[...event.characterEntryCheckpoints,characterEntryCheckpointSchema.parse({actorId:'char-lumingze',readerSetup:'面试前夜的语音辅导开始之前，堂弟路鸣泽已在他和路明非共用的卧室床上睡着。此处的路鸣泽是堂弟，不是后文同名男孩。',actorObservation:'你正在自己与堂哥共用的卧室里睡觉。',participantPresence:[{entityId:'char-lumingze',mode:'physical'}],delta:{version:1,operations:[{op:'set',entityId:'char-lumingze',field:'character.location',value:location.id}]}})];
 const next={...event,characterEntryCheckpoints:checkpoints};
 const batch=`host-cousin-bedroom-entry-${state.sourceId}-v1`,reviewPath='run-records/2026-09-11-codex-compile-loop/host-review-cousin-bedroom-entry-checkpoint.json';
 await fs.writeFile(new URL('host-review-cousin-bedroom-entry-checkpoint.json',dir),JSON.stringify({reviewedAt:new Date().toISOString(),priorState:state,originalBatch,originalReceipt:old.fingerprint,reports,ledgers,original:event,next,location,sourceQuotes:{room,sleep},reason:'Host reviewed the exact original unsupported coaching report and per-target ledger. Immutable source explicitly names the shared bedroom and places the cousin asleep on the adjacent bed before voice coaching starts. Introduce only this source-attested stable location through propose_entity, then append a location-only checkpoint for the existing cousin identity. Sleep is reader setup, not a new numeric state or awareness of the ongoing conversation. Do not add a plan, overheard knowledge, dreams, or the unrelated boys identity. Preserve Lumingfei existing checkpoint byte-for-byte, all original event fields, old evidence anchors, reports, receipts and publication gates. The two actor boundaries are explicitly before the initial question and before voice coaching respectively; neither seeds coached knowledge.',validation:'Character entry, entry-context, compiler finish/obligation and loop regressions plus strict type check and normal schema/evidence/commit verification.'},null,2),{flag:'wx'});
 const toolset=createCompilerProposalToolset(root);await toolset.beginBatch([],batch,state.sourceId);const call=(name:string,input:unknown)=>toolset.tools.find(t=>t.name===name)!.execute(name,input as never,undefined,undefined,{} as never);
 const segment='a28585b1cf867f3e3a16-00003-5c70d7864d11';
 await call('propose_entity',{proposal_id:'entity-lu-cousins-bedroom-host-v1',payload:location,evidence_segment_ids:[segment],evidence_selectors:['/canonicalName','/kind'].map(target_path=>({segment_id:segment,exact:room,target_path,relation:'supports',strength:'explicit'}))});
 const assertions=await new EvidenceAssertionStore(root).listForArtifact('canonical-event',event.id);
 const selectors=assertions.flatMap(a=>a.anchors.map(anchor=>{
  const exact=bytes.subarray(anchor.startByte,anchor.endByte).toString('utf8'),needle=Buffer.from(exact),hits:number[]=[];
  for(let offset=5290;offset<54279;){const at=bytes.indexOf(needle,offset);if(at<0||at+needle.length>54279)break;hits.push(at);offset=at+1;}
  const occurrence=hits.indexOf(anchor.startByte)+1;if(!occurrence)throw Error('Original evidence outside reviewed segment');
  return {segment_id:segment,exact,...(hits.length>1?{occurrence}:{}),target_path:a.target.jsonPointer,relation:a.relation,strength:a.strength,...(a.interpretation?{interpretation:a.interpretation}:{})};
 }));
 for(let index=event.characterEntryCheckpoints.length;index<checkpoints.length;index++)for(const field of ['readerSetup','actorObservation','participantPresence','delta'])for(const quote of [room,sleep])selectors.push({segment_id:segment,exact:quote,target_path:`/characterEntryCheckpoints/${index}/${field}`,relation:'supports',strength:'strong-inference',interpretation:'Explicit shared bedroom and cousin sleeping beside Lumingfei before voice coaching. Location only; no learned dialogue or invented plan.'});
 const {evidence,...payload}=next;await call('propose_canonical_event',{proposal_id:'event-cousin-bedroom-host-checkpoint-v1',payload,evidence_segment_ids:[segment],evidence_selectors:selectors});
 await call('finish_compiler_batch',{outcome:'complete',reviewed_segments:[],summary:'Source-reviewed shared bedroom entity and pre-voice-coaching cousin location checkpoint; Lumingfei checkpoint unchanged.'});
 const receipts=new CompilerFinishReceipts(root,state.sourceId,batch),receipt=await receipts.read();if(receipt?.state!=='completed')throw Error('Finish incomplete');await receipts.verify(receipt);
 const result=await convergeWorldProposals(root,state.sourceId);if(result.canonical.blocked.length||result.possibilities.blocked.length)throw Error(JSON.stringify(result));
 const current=await canon.listEvents();for(const e of events)if(contentHash(current.find(c=>c.id===e.id))!==contentHash(e.id===event.id?next:e))throw Error('Unexpected event change');
 const updatedEntities=await canon.listEntities();if(updatedEntities.length!==entities.length+1||!updatedEntities.some(e=>e.id===location.id&&e.kind==='location'&&e.canonicalName===location.canonicalName))throw Error('Location commit missing');for(const e of entities)if(contentHash(updatedEntities.find(c=>c.id===e.id))!==contentHash(e))throw Error('Existing entity changed');
 await predecessor.verify(old);
 let gate=false;try{await assertReconciliationDeferralsReviewed(root,state.sourceId);}catch(e){if(String(e).includes('host source review'))gate=true;else throw e;}if(!gate)throw Error('Original review gate lost');
 state.appliedRepairHistory.push(state.appliedRepair);state.appliedRepair={repairId:'cousin-source-reviewed-bedroom-checkpoint-v1',failureFingerprint:compilerFailureCauseFingerprint({category:'missing-source-backed-cousin-bedroom-entry',targetIds:['char-lumingze'],dependencyIds:[event.id]}),reviewPath,appliedAt:new Date().toISOString()};
 await fs.writeFile(new URL('host-review-cousin-bedroom-entry-checkpoint-result.json',dir),JSON.stringify({receipt:receipt.fingerprint,gateRetained:gate,onlyEntryCheckpointAdded:true}));
 await fs.writeFile(new URL('state.tmp.json',dir),JSON.stringify(state,null,2));await fs.rename(new URL('state.tmp.json',dir),new URL('state.json',dir));console.log(JSON.stringify({ready:true,receipt:receipt.fingerprint,gateRetained:gate}));
});
