import fs from 'node:fs/promises';
import { CanonicalModelStore } from '../../src/world/canonical-model.js';
import { ActorModelStore, characterGoalSchema, evaluateCharacterGoal } from '../../src/world/actors.js';
import { contentHash } from '../../src/world/canonical.js';
import { WorkspaceStore } from '../../src/storage/workspace-store.js';
import { SourceMaterialStore } from '../../src/storage/source-material-store.js';
import { inspectCompilerStatus } from '../../src/compiler/status.js';
import { CompilerFinishReceipts } from '../../src/compiler/finish-receipts.js';
import { createCompilerProposalToolset } from '../../src/compiler/proposal-tools.js';
import { convergeWorldProposals } from '../../src/compiler/converge.js';
import { assertReconciliationDeferralsReviewed } from '../../src/compiler/reconciliation-review-ledger.js';
import { compilerFailureCauseFingerprint } from '../../src/runtime/codex-compile-loop.js';
import { withWorkspaceOperationLock } from '../../src/util/workspace-lock.js';
const root=process.cwd(),dir=new URL('./',import.meta.url);
await withWorkspaceOperationLock(root,'compiler',async()=>{
 const state=JSON.parse(await fs.readFile(new URL('state.json',dir),'utf8'));
 if(state.attempt!==46||state.status!=='needs-review'||state.knowledgeRepair.pending)throw Error('Incident changed');
 const status=(await inspectCompilerStatus(root,state.sourceId)).sources[0]!;
 if(status.sourceIntegrity!=='verified'||status.hasUnresolvedObligations||status.worldProposalInventory.pending)throw Error('Unreviewed obligations');
 const canon=new CanonicalModelStore(root),actors=new ActorModelStore(root),events=await canon.listEvents(),goals=await actors.listGoals(),models=await actors.listModels();
 const invitation=events.find(e=>e.id==='event-chu-invite-001');if(!invitation||!invitation.participants.includes('char-chuzi-hang'))throw Error('Invitation changed');
 for(const [id,order] of [['event-email-open-001',48],['event-nono-appears-001',48.5]] as const){const e=events.find(e=>e.id===id);if(e?.storyTime.kind!=='ordinal'||e.storyTime.orderHint!==order)throw Error('Prior time repair failed');}
 const originalBatch=`reconcile-${state.sourceId}-bounded-codex-target-review-v1-20260912-1`;
 const predecessor=new CompilerFinishReceipts(root,state.sourceId,originalBatch),old=await predecessor.read();if(old?.state!=='completed')throw Error('Original finish missing');await predecessor.verify(old);
 const report=old.identity.input.target_reviews?.find(r=>r.target==='character:char-chuzi-hang');
 if(report?.disposition!=='unsupported'||report.summary!=='The current model is already character-v1. The cited account describes prior motivation and recruitment, not a source-bounded development transition suitable for a new phase or goal.')throw Error('Original report changed');
 const source=await WorkspaceStore.openReadOnly(root).getSource(state.sourceId);if(!source)throw Error('Source missing');const bytes=await new SourceMaterialStore().read(source);if(!bytes)throw Error('Immutable source missing');const lines=bytes.toString('utf8').split('\n');
 const quote=lines[2370]!.trim(),context=lines[2374]!.trim();
 if(!quote.includes('楚子航邀请我加入狮心会了，还说我会是他之后的下一任会长')||!context.includes('他是要培养你为他的继承人'))throw Error('Source text changed');
 const goal=characterGoalSchema.parse({id:'goal-chu-recruit-lumingfei-00013',actorId:'char-chuzi-hang',description:'在已向路明非发出邀请的招揽阶段，争取他加入狮心会，并将他作为下一任会长的人选。邀请不等于入会或继任已完成。',priority:0.5,requiresKnowledge:[],targetIds:['char-lumingfei','faction-lionheart-001'],activation:{preconditions:[],afterCanonicalEventIds:[invitation.id]},evidence:invitation.evidence});
 if(goals.some(g=>g.id===goal.id))throw Error('Goal already exists; inspect original scope instead of retrying');
 const evaluationState={atCommit:'host-review',logicalTime:{step:0},values:{},activeRuleIds:[]};
 const dormant=evaluateCharacterGoal(goal,{state:evaluationState,knownClaimIds:new Set(),realizedCanonicalEventIds:new Set()});
 const activated=evaluateCharacterGoal(goal,{state:evaluationState,knownClaimIds:new Set(),realizedCanonicalEventIds:new Set([invitation.id])});
 if(dormant.active||!activated.active)throw Error('Invitation activation boundary failed');
 const batch=`host-chu-recruitment-goal-${state.sourceId}-v1`,reviewPath='run-records/2026-09-11-codex-compile-loop/host-review-chu-recruitment-goal.json';
 await fs.writeFile(new URL('host-review-chu-recruitment-goal.json',dir),JSON.stringify({reviewedAt:new Date().toISOString(),priorState:state,originalBatch,originalReceipt:old.fingerprint,report,invitation,proposal:goal,sourceLines:lines.slice(2359,2377),reason:'The exact deferred report conflates personality development with a bounded actor goal. The source explicitly reports the invitation and succession offer. Represent only the recruitment objective after that invitation is realized; future compiler knowledge alone does not activate it. This is a policy input, not a committed membership, leadership transition, psychological numeric change, guaranteed action or mandatory canon scheduler. Priority 0.5 is a neutral policy ranking, not a source-measured psychological intensity. No executable membership action or expiry is fabricated where the source/catalog supplies none; lifecycle remains limited to the evidenced activation boundary. Keep the original unsupported report and source-wide host review gate. The prior time repair remains intact and no longer appears in the audit error.',validation:'Goal activation and development, compiler finish, proposal obligation and loop regressions; normal typed proposal, evidence validation, convergence and immutable predecessor verification.'},null,2),{flag:'wx'});
 const toolset=createCompilerProposalToolset(root);await toolset.beginBatch([],batch,state.sourceId);
 const call=(name:string,input:unknown)=>toolset.tools.find(t=>t.name===name)!.execute(name,input as never,undefined,undefined,{} as never);
 const {evidence,...payload}=goal,segment='a28585b1cf867f3e3a16-00013-2df5b1eb46fa';
 await call('propose_character_goal',{proposal_id:'goal-chu-recruit-lumingfei-host-v1',payload,evidence_segment_ids:[segment],evidence_selectors:['/description','/actorId','/targetIds','/activation'].map(target_path=>({segment_id:segment,exact:quote,target_path,relation:'supports',strength:'explicit'}))});
 await call('finish_compiler_batch',{outcome:'complete',reviewed_segments:[],summary:'Host source-reviewed recruitment goal, activated only after the invitation; no membership, personality or event mutations.'});
 const receipts=new CompilerFinishReceipts(root,state.sourceId,batch),receipt=await receipts.read();if(receipt?.state!=='completed')throw Error('Finish incomplete');await receipts.verify(receipt);
 const result=await convergeWorldProposals(root,state.sourceId);if(result.canonical.blocked.length||result.possibilities.blocked.length)throw Error(JSON.stringify(result));
 const current=await actors.listGoals();if(current.length!==goals.length+1||contentHash(current.find(g=>g.id===goal.id))!==contentHash(goal))throw Error('Unexpected goal result');
 for(const oldGoal of goals)if(contentHash(current.find(g=>g.id===oldGoal.id))!==contentHash(oldGoal))throw Error('Existing goal changed');
 if(contentHash(await canon.listEvents())!==contentHash(events)||contentHash(await actors.listModels())!==contentHash(models))throw Error('Unrelated world/model changes');
 await predecessor.verify(old);
 let gate=false;try{await assertReconciliationDeferralsReviewed(root,state.sourceId);}catch(e){if(String(e).includes('host source review'))gate=true;else throw e;}if(!gate)throw Error('Original review gate lost');
 state.appliedRepairHistory.push(state.appliedRepair);state.appliedRepair={repairId:'chu-source-reviewed-recruitment-goal-v1',failureFingerprint:compilerFailureCauseFingerprint({category:'source-explicit-recruitment-goal-omitted',targetIds:['char-chuzi-hang'],dependencyIds:[invitation.id]}),reviewPath,appliedAt:new Date().toISOString()};
 await fs.writeFile(new URL('host-review-chu-recruitment-goal-result.json',dir),JSON.stringify({receipt:receipt.fingerprint,gateRetained:gate,existingEventsModelsGoalsUnchanged:true}));
 await fs.writeFile(new URL('state.tmp.json',dir),JSON.stringify(state,null,2));await fs.rename(new URL('state.tmp.json',dir),new URL('state.json',dir));console.log(JSON.stringify({ready:true,receipt:receipt.fingerprint,gateRetained:gate}));
});
