import fs from 'node:fs/promises';
import { CanonicalModelStore } from '../../src/world/canonical-model.js';
import { characterEntryCheckpointSchema } from '../../src/world/model.js';
import { contentHash } from '../../src/world/canonical.js';
import { WorkspaceStore } from '../../src/storage/workspace-store.js';
import { SourceMaterialStore } from '../../src/storage/source-material-store.js';
import { inspectCompilerStatus } from '../../src/compiler/status.js';
import { CompilerFinishReceipts } from '../../src/compiler/finish-receipts.js';
import { EvidenceAssertionStore } from '../../src/compiler/evidence-assertions.js';
import { createCompilerProposalToolset } from '../../src/compiler/proposal-tools.js';
import { convergeWorldProposals } from '../../src/compiler/converge.js';
import { assertReconciliationDeferralsReviewed } from '../../src/compiler/reconciliation-review-ledger.js';
import { compilerFailureCauseFingerprint } from '../../src/runtime/codex-compile-loop.js';
import { withWorkspaceOperationLock } from '../../src/util/workspace-lock.js';
const root=process.cwd(),dir=new URL('./',import.meta.url);
await withWorkspaceOperationLock(root,'compiler',async()=>{
 const state=JSON.parse(await fs.readFile(new URL('state.json',dir),'utf8'));
 if(state.attempt!==49||state.status!=='needs-review'||state.knowledgeRepair.pending)throw Error('Incident changed');
 const status=(await inspectCompilerStatus(root,state.sourceId)).sources[0]!;
 if(status.sourceIntegrity!=='verified'||status.hasUnresolvedObligations||status.worldProposalInventory.pending)throw Error('Unreviewed obligations');
 const canon=new CanonicalModelStore(root),events=await canon.listEvents();
 const event=events.find(e=>e.id==='event-nono-entry-00005');if(!event||event.characterEntryCheckpoints?.length||event.narrativeContext?.discourseOrder!==701)throw Error('Entry target changed');
 const sorted=events.slice().sort((a,b)=>Math.min(...a.evidence.map(r=>r.span.startLine))-Math.min(...b.evidence.map(r=>r.span.startLine))||(a.narrativeContext?.discourseOrder??0)-(b.narrativeContext?.discourseOrder??0)||a.id.localeCompare(b.id));
 if(sorted.find(e=>(!e.narrativeContext||e.narrativeContext.mode==='scene')&&e.participantPresence?.some(p=>p.entityId==='char-nuonuo'&&p.mode==='physical'))?.id!==event.id)throw Error('First-entry correction failed');
 const originalBatch=`reconcile-${state.sourceId}-bounded-codex-target-review-v1-20260912-1`,predecessor=new CompilerFinishReceipts(root,state.sourceId,originalBatch),old=await predecessor.read();if(old?.state!=='completed')throw Error('Original finish missing');await predecessor.verify(old);
 const reports=old.identity.input.target_reviews?.filter(r=>['event:event-nono-entry-00005','event:event-accept-00005'].includes(r.target));if(reports?.length!==2||reports.some(r=>r.disposition!=='unsupported'))throw Error('Original reports changed');
 const source=await WorkspaceStore.openReadOnly(root).getSource(state.sourceId);if(!source)throw Error('Source missing');const bytes=await new SourceMaterialStore().read(source);if(!bytes)throw Error('Immutable source missing');const lines=bytes.toString('utf8').split('\n');
 const exact=(needle:string)=>{const matches=lines.slice(692,788).filter(l=>l.includes(needle));if(matches.length!==1)throw Error('Anchor not unique');return matches[0]!.trim();};
 const entry=exact('有人用力推开放映厅的门。'),recall=exact('知道你给人耍，就临时开车去买了套衣服'),address=exact('李嘉图，我们的时间不够了，还要继续参加活动么？'),prior=exact('去当他的“i”。');
 const checkpoint=characterEntryCheckpointSchema.parse({actorId:'char-nuonuo',readerSetup:'文学社聚会仍在放映厅进行。路明非被同学叫回去充当字母；诺诺已临时换装赶来，即将推门介入。这里是她进门之前，不是两人已经离开聚会之后。',actorObservation:'你已临时换好衣服赶到放映厅门前，准备进去接路明非。',participantPresence:[{entityId:'char-nuonuo',mode:'physical'}],delta:{version:1,operations:[{op:'set',entityId:'char-nuonuo',field:'character.plan',value:'进入放映厅接路明非离开活动'}]}});
 const next={...event,characterEntryCheckpoints:[checkpoint]};
 const batch=`host-nono-pre-entry-${state.sourceId}-v1`,reviewPath='run-records/2026-09-11-codex-compile-loop/host-review-nono-entry-checkpoint.json';
 await fs.writeFile(new URL('host-review-nono-entry-checkpoint.json',dir),JSON.stringify({reviewedAt:new Date().toISOString(),priorState:state,originalBatch,originalReceipt:old.fingerprint,reports,original:event,next,sourceQuotes:{prior,entry,recall,address},reason:'Earlier reports address missing event effects and the incorrectly selected roadside entry. The actual first embodied entry is now verified at the cinema. Nono later explicitly recounts buying clothes after learning of the prank and running in; that retrospection supports preexisting preparation and intent, not newly acquired future knowledge. At the immediate pre-door boundary her own arrival is a strong spatial inference; the invitation immediately after entry and the retrospective account support her plan to collect Lumingfei. Store only that plan. Do not copy the event outcome, give Lumingfei the subsequent invitation early, infer a completed rescue, add membership/resources/health, or grant narrator knowledge. Reader-only prior context is separate from Nono observation. Original reports, checkpoints on other events, knowledge, timeline, namespace and publication gates remain.',validation:'Character entry, entry-context, compiler finish/obligation and loop regressions plus strict type check and normal schema/evidence/commit verification.'},null,2),{flag:'wx'});
 const toolset=createCompilerProposalToolset(root);await toolset.beginBatch([],batch,state.sourceId);const call=(name:string,input:unknown)=>toolset.tools.find(t=>t.name===name)!.execute(name,input as never,undefined,undefined,{} as never);
 const segment='a28585b1cf867f3e3a16-00005-12c9137e67cf';
 const assertions=await new EvidenceAssertionStore(root).listForArtifact('canonical-event',event.id);
 const selectors=assertions.flatMap(a=>a.anchors.map(anchor=>({segment_id:segment,exact:bytes.subarray(anchor.startByte,anchor.endByte).toString('utf8'),target_path:a.target.jsonPointer,relation:a.relation,strength:a.strength,...(a.interpretation?{interpretation:a.interpretation}:{})})));
 for(const [field,quotes] of [['readerSetup',[prior,entry,recall]],['actorObservation',[entry,recall,address]],['participantPresence',[entry]],['delta',[recall,address]]] as const)for(const quote of quotes)selectors.push({segment_id:segment,exact:quote,target_path:`/characterEntryCheckpoints/0/${field}`,relation:'supports',strength:'strong-inference',interpretation:'Immediate pre-door entry boundary; later retrospective dialogue supplies only preparation already completed before entry. No event outcome or future knowledge is projected backward.'});
 const {evidence,...payload}=next;await call('propose_canonical_event',{proposal_id:'event-nono-entry-host-checkpoint-v1',payload,evidence_segment_ids:[segment],evidence_selectors:selectors});
 await call('finish_compiler_batch',{outcome:'complete',reviewed_segments:[],summary:'Source-reviewed pre-door Nono checkpoint with preparation plan only; all existing event and knowledge effects preserved.'});
 const receipts=new CompilerFinishReceipts(root,state.sourceId,batch),receipt=await receipts.read();if(receipt?.state!=='completed')throw Error('Finish incomplete');await receipts.verify(receipt);
 const result=await convergeWorldProposals(root,state.sourceId);if(result.canonical.blocked.length||result.possibilities.blocked.length)throw Error(JSON.stringify(result));
 const current=await canon.listEvents();for(const e of events)if(contentHash(current.find(c=>c.id===e.id))!==contentHash(e.id===event.id?next:e))throw Error('Unexpected event change');
 await predecessor.verify(old);
 let gate=false;try{await assertReconciliationDeferralsReviewed(root,state.sourceId);}catch(e){if(String(e).includes('host source review'))gate=true;else throw e;}if(!gate)throw Error('Original review gate lost');
 state.appliedRepairHistory.push(state.appliedRepair);state.appliedRepair={repairId:'nono-source-reviewed-pre-door-checkpoint-v1',failureFingerprint:compilerFailureCauseFingerprint({category:'missing-source-backed-pre-door-entry',targetIds:['char-nuonuo'],dependencyIds:[event.id]}),reviewPath,appliedAt:new Date().toISOString()};
 await fs.writeFile(new URL('host-review-nono-entry-checkpoint-result.json',dir),JSON.stringify({receipt:receipt.fingerprint,gateRetained:gate,onlyEntryCheckpointAdded:true}));
 await fs.writeFile(new URL('state.tmp.json',dir),JSON.stringify(state,null,2));await fs.rename(new URL('state.tmp.json',dir),new URL('state.json',dir));console.log(JSON.stringify({ready:true,receipt:receipt.fingerprint,gateRetained:gate}));
});
